### ISSUE TITLE
Existing EF migrations broke when I migrated from .NET 6 to .NET 8 (byte[] and Guid)

### ISSUE THREAD

**Issue by YumeiTenerife** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1823] opened 2023-12-15 21:59 UTC
### Steps to reproduce
I had some existing EF migrations (code first) generated using .NET 6 (and Pomelo 6.0.2). These migrations had some Guid properties that were mapped with the following code:
```
  migrationBuilder.CreateTable(
      name: "MyTable",
      columns: table => new
      {
          Id = table.Column<int>(type: "int", nullable: false)
              .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
          SomeGuid = table.Column<byte[]>(type: "binary(16)", nullable: false),
      }
```

After upgrading to .NET 8 and started using Pomelo 8.0.0-beta.2, my existing migrations stopped working.
When running the migrations to create a new database using the following command:

`
 dotnet ef database update
` 

 I get an exception. Look at "The issue" for more details.

NOTE: I was able to fix it replacing in all the existing migrations < byte[] > for < Guid >. But ideally it should be backward compatible.

### The issue

Exception issue:
```
Build started...
Build succeeded.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindCollectionMapping(RelationalTypeMappingInfo info, Type modelType, Type providerType, CoreTypeMapping elementMapping)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<>c.<FindMappingWithConversion>b__8_0(ValueTuple`4 k, RelationalTypeMappingSource self)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, Type providerClrType, ValueConverter customConverter)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, IReadOnlyList`1 principals)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(IProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.<>c.<get_TypeMapping>b__91_0(IProperty property)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.get_TypeMapping()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.Microsoft.EntityFrameworkCore.Metadata.IReadOnlyProperty.FindTypeMapping()
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.FindRelationalTypeMapping(IReadOnlyProperty property)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetColumnType(IReadOnlyProperty property)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetColumnType(IProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.AddDefaultMappings(RelationalModel databaseModel, IEntityType entityType, IRelationalTypeMappingSource relationalTypeMappingSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Create(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, IRelationalTypeMappingSource relationalTypeMappingSource, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Add(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, IRelationalTypeMappingSource relationalTypeMappingSource, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelRuntimeInitializer.InitializeModel(IModel model, Boolean designTime, Boolean prevalidation)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.FinalizeModel(IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.GenerateScript(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigrationImpl(String fromMigration, String toMigration, Boolean idempotent, Boolean noTransactions, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Object reference not set to an instance of an object.
```

### Further technical details

MySQL version: 8.0
Operating system:  Windows
Pomelo.EntityFrameworkCore.MySql version: 8.0.0-beta.2
Microsoft.AspNetCore.App version: .NET 8

Other details about my project setup:

**Comment by sushilmate** [comment] 2023-12-18 22:45
facing the same issue. not sure when this will be released. we cant used in beta version in prod. few users suggesting to downgrade to version 6.

**Comment by YumeiTenerife** [comment] 2023-12-19 17:37
> facing the same issue. not sure when this will be released. we cant used in beta version in prod. few users suggesting to downgrade to version 6.

Yeah definitely not for production code, i would downgrade until then. I am hoping that there is a fix by the time we go to production.

**Comment by lauxjpn** [comment] 2024-03-02 08:05
@YumeiTenerife @sushilmate I am unable to reproduce this issue in Pomelo `8.0.x`. Has this been fixed between `8.0.0-beta.2` and `8.0.0`?

If not, please post a sample model class with this issue, its configuration/Fluent API and your `.UseMySql()` call (including the connection string, without sensitive information), so we can reproduce the issue. Thanks!

**Comment by sushilmate** [comment] 2024-03-03 06:55
> [lauxjpn](/lauxjpn)

it was in the older version. beta & 8.0 look better. tested on both. works fine. thank you

**Comment by YumeiTenerife** [comment] 2024-03-05 13:43
Hello @lauxjpn , I still have the same issue. We use code first approeach

1) Using .NET 6 (and Pomelo 6.0.2), I created a database model:

```
public class MyTable {
    [Key]
    public int Id { get; set; }

    [Required]
    public **Guid** SomeGuid { get; set; }
}

```
2) Created the migration using:
` dotnet ef migrations add NewMigration`

3) This created the following migration file:

```
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.AlterDatabase()
            .Annotation("MySql:CharSet", "utf8mb4");
            
        migrationBuilder.CreateTable(
              name: "MyTable",
              columns: table => new
              {
                  Id = table.Column<int>(type: "int", nullable: false)
                      .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                  SomeGuid = table.Column<**byte[]**>(type: "binary(16)", nullable: false),
              },
              constraints: table =>
              {
                  table.PrimaryKey("PK_MyTable", x => x.Id);
              })
              .Annotation("MySql:CharSet", "utf8mb4");
    }
```

4) I upgraded to .NET 8, using Pomelo 8.0.0. Then I tried to run my existing migration to create a new DB:
From the console: `dotnet ef database update`
OR, to generate the script instead:
`dotnet ef migrations script`

In both cases, we get the following error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindCollectionMapping(RelationalTypeMappingInfo info, Type modelType, Type providerType, CoreTypeMapping elementMapping)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<>c.<FindMappingWithConversion>b__8_0(ValueTuple`4 k, RelationalTypeMappingSource self)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, Type providerClrType, ValueConverter customConverter)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, IReadOnlyList`1 principals)
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(IProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.<>c.<get_TypeMapping>b__91_0(IProperty property)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.get_TypeMapping()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Property.Microsoft.EntityFrameworkCore.Metadata.IReadOnlyProperty.FindTypeMapping()
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.FindRelationalTypeMapping(IReadOnlyProperty property)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetColumnType(IReadOnlyProperty property)
   at Microsoft.EntityFrameworkCore.RelationalPropertyExtensions.GetColumnType(IProperty property)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.AddDefaultMappings(RelationalModel databaseModel, IEntityType entityType, IRelationalTypeMappingSource relationalTypeMappingSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Create(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, IRelationalTypeMappingSource relationalTypeMappingSource, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalModel.Add(IModel model, IRelationalAnnotationProvider relationalAnnotationProvider, IRelationalTypeMappingSource relationalTypeMappingSource, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelRuntimeInitializer.InitializeModel(IModel model, Boolean designTime, Boolean prevalidation)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.FinalizeModel(IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.GenerateUpSql(Migration migration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateScript(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.GenerateScript(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.ScriptMigration(String fromMigration, String toMigration, MigrationsSqlGenerationOptions options, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigrationImpl(String fromMigration, String toMigration, Boolean idempotent, Boolean noTransactions, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScriptMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

I also tried to create a NEW migration using the new pomelo version, and the migration generated was similar, except that now the Guid was no longer a byte[], but now we get:
                  SomeGuid = table.Column<**Guid**>(type: "binary(16)", nullable: false),

This script works fine, but the old one generated with the previous version no longer works.

**Comment by YumeiTenerife** [comment] 2024-03-05 13:44
I will try to setup an example and send that to you. Thank you!

**Comment by lauxjpn** [comment] 2024-03-05 14:14
> I will try to setup an example and send that to you. Thank you!

Might not be necessary. We will try to reproduce the issue with the information you provided.

**Comment by lauxjpn** [comment] 2024-03-05 14:26
By default, Pomelo `6.0.2` should have generated the following line in the migration `Up()` method:

```c#
SomeGuid = table.Column<Guid>(type: "char(36)", nullable: false, collation: "ascii_general_ci")
```

Your migration's `Up()` method contains the following line instead:

```c#
SomeGuid = table.Column<byte[]>(type: "binary(16)", nullable: false),
```

@YumeiTenerife Please provide us with the following information marked in **bold**:

> If not, please post a sample model class with this issue, its configuration/Fluent API and your **.UseMySql() call (including the connection string, without sensitive information)**, so we can reproduce the issue.

**Comment by YumeiTenerife** [comment] 2024-03-05 14:42
Yes, sorry, I missed that. The connection string looks like this:
$"server={host};port={port};database={database};uid={username};pwd={password};GuidFormat=Binary16";

**Comment by lauxjpn** [comment] 2024-03-05 15:30
I am still unable to reproduce this issue.

I created the following console project using Pomelo `6.0.2`:

<details>
<summary>Program.cs</summary>

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

public class MyTable
{
    public int Id { get; set; }
    public Guid SomeGuid { get; set; }
}

public class Context : DbContext
{
    public DbSet<MyTable> MyTables { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1823_01;GuidFormat=Binary16";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(connectionString, serverVersion)
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MyTable>(
            entity =>
            {
                entity.Property(e => e.SomeGuid)
                    .IsRequired();

                entity.HasData(
                    new MyTable
                    {
                        Id = 1,
                        SomeGuid = Guid.Parse("5aa12cf0-bae3-406e-9ab6-92b1cf5fa9e1"),
                    });
            });
    }
}

internal static class Program
{
    private static void Main()
    {
        using var context = new Context();
        
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();
        
        var vanillaIceCream = context.MyTables
            .Single(i => i.SomeGuid == Guid.Parse("5aa12cf0-bae3-406e-9ab6-92b1cf5fa9e1"));
        
        Trace.Assert(vanillaIceCream.Id == 1);
    }
}
```

</details>

I then ran the following CLI command (using `dotnet-ef` version `6.0.7`):

```
dotnet ef migrations add 'Pomelo6'
```

It generated the following file (similar to yours):

<details>
<summary>20240305151045_Pomelo6.cs</summary>

```c#
using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IssueConsoleTemplate.Migrations
{
    public partial class Pomelo6 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "MyTables",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    SomeGuid = table.Column<Guid>(type: "binary(16)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MyTables", x => x.Id);
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.InsertData(
                table: "MyTables",
                columns: new[] { "Id", "SomeGuid" },
                values: new object[] { 1, new Guid("5aa12cf0-bae3-406e-9ab6-92b1cf5fa9e1") });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MyTables");
        }
    }
}
```

</details>

I then switched to Pomelo `8.0.0`.

Finally, I ran the following CLI command (using `dotnet-ef` version `8.0.2`):

```
dotnet ef migrations script
```

It generated the following output without any exception:

<details>
<summary>Output (SQL)</summary>

```sql
Build started...
Build succeeded.
warn: 05.03.2024 16:22:56.607 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET=utf8mb4;

START TRANSACTION;

ALTER DATABASE CHARACTER SET utf8mb4;

CREATE TABLE `MyTables` (
    `Id` int NOT NULL AUTO_INCREMENT,
    `SomeGuid` binary(16) NOT NULL,
    CONSTRAINT `PK_MyTables` PRIMARY KEY (`Id`)
) CHARACTER SET=utf8mb4;

INSERT INTO `MyTables` (`Id`, `SomeGuid`)
VALUES (1, 0x5AA12CF0BAE3406E9AB692B1CF5FA9E1);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20240305151045_Pomelo6', '8.0.0');

COMMIT;
```

</details>

I did not change the connection string in any way between upgrading from Pomelo `6.0.2` to `8.0.0`.

@YumeiTenerife Please verify my code and steps on your end, to ensure that you get the same result as I do.

**Comment by YumeiTenerife** [comment] 2024-03-05 18:03
That's so strange! I am looking again at the differences and I can see that I also have in the context the following:
   ```
     modelBuilder.Entity<MyTable>()
            .Property(a => a.SomeGuid)
            .HasColumnType("binary(16)");
```

would you mind trying that,  in the model creating, when using .NET 6?
                entity.Property(e => e.SomeGuid)
                   .HasColumnType("binary(16)");
                   .IsRequired();
                   
Thank you so much for trying to reproduce this!

**Comment by lauxjpn** [comment] 2024-03-05 18:23
Using `.HasColumnType("binary(16)")` doesn't make a difference, which makes sense, because as you can see in the `20240305151045_Pomelo6.cs` file, `binary(16)` was already used without specifying it explicitly (because of your `GuidFormat=Binary16` connection string option):

```c#
SomeGuid = table.Column<Guid>(type: "binary(16)", nullable: false)
```

---

Independent of that, your `Up()` method shows `table.Column<byte[]>`, while the one that was generated for me uses `table.Column<Guid>`:

Your line:

```c#
SomeGuid = table.Column<byte[]>(type: "binary(16)", nullable: false)
```

My line:
```c#
SomeGuid = table.Column<Guid>(type: "binary(16)", nullable: false)
```

**Comment by YumeiTenerife** [comment] 2024-03-05 18:33
Thanks for replying! No converters are used... In fact, that script works fine in .NET 6 (with byte[]) but fails with .NET 8. That's so weird, I have no idea how it got that byte[] there. In fact, all the migration scripts generated while using .NET 6 had that same issue. I'll try to reproduce it with your code and see if I can figure out why it generated the byte[]. 

Thanks and sorry for the trouble!

**Comment by lauxjpn** [comment] 2024-03-16 08:33
@YumeiTenerife Any update on this issue?

**Comment by YumeiTenerife** [comment] 2024-03-26 19:28
Sorry! I went away on vacation and I just returned. I will try to start over and see if I am able to reproduce it. It seems like all projects had the same issue but maybe that was caused by a different setting that it was set at that time?
If you did all those steps and could not reproduce it, no worries, please feel free to close this ticket. I'll reopen it if I can reproduce it.

Thank you so much!

**Closed** 2024-04-01 17:46 UTC
Labels: needs-more-info, could-not-reproduce

**Comment by mangal1234567** [comment] 2024-12-17 05:53
@YumeiTenerife  
this can be reason of this exception ?, this migration was working fine in .net 6.0 but in 8.0 same exception is coming
.HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

**Comment by lauxjpn** [comment] 2024-12-20 00:41
@mangal1234567 If this is an issue for you, please post some code, so we can reproduce the issue. Some skeleton code (used to reproduce a different migration issue), that you could use and modify for a minimal reproducible example, can be found in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1941#issuecomment-2547277602.

**Comment by kirylbokach** [comment] 2025-08-15 20:01
Having the same issue with EF Core 9. The migrations were working fine until adding the `GuidFormat=Binary16` in the connection string, then migrations started failing with NRE

**Comment by lauxjpn** [comment] 2025-08-17 00:04
@kirylbokach Is your intention to change the `GuidFormat` between migrations?

Please post us a sample C#/POCO entity (before migration and after migration), so we get an idea about what you are trying to do and also post the _full_ NRE exception (including stack trace) and the exact version of Pomelo you are using.

**Comment by kirylbokach** [comment] 2025-08-18 16:09
@lauxjpn Here is my sequence of steps that led to the NRE with the same call stack as [posted above](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1823#issuecomment-1978805294) 

1. Create a migration containing a table with a binary(16) column that maps to a Guid C# record property with no `GuidFormat` set in the command line.
2. Apply the migration to the database.
3. The integration test that reads a row by Guid value that was just inserted was returning 0 rows, so I started digging and found `GuidFormat=Binary16` option. I set it in the command line and the integration test with `SELECT * FROM abc WHERE Id = @GuidId` started passing
4. The other integration test, that was generating the full migration script started falling with NRE mentioned above. It would be falling until I'd remove the `GuidFormat=Binary16`

Workaround
I had to start fresh with all migrations and recreate the database from the point when the first Guid column was introduced, first setting `GuidFormat=Binary16`

It would be great to have a more descriptive exception thrown in these cases. Wonder if some try/catch could be introduced in `Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.GenerateUpSql` to wrap and rethrow.

**Comment by lauxjpn** [comment] 2025-08-18 21:09
@kirylbokach The default [GuidFormat](https://mysqlconnector.net/connection-options/#GuidFormat) is `Char36`, which is quite different from `Binary16`.

I'm not sure I follow steps `3.` and `4`. Please post the entity and tests in question.

Is it you _intention_ to change the `GuidFormat` connection string option between migrations, or are you just changing it to try to solve a different issue? If it is your intention, why are you changing it?
