### ISSUE TITLE
Memory leak in version 1.1.1

### ISSUE THREAD

**Issue by jemiller0** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#262] opened 2017-04-20 00:38 UTC
I upgraded to version 1.1.1 the other day. Then, I noticed that the following consumed 28 GB RAM and looked like it was never going to complete. The problem occurs with multiple different large tables that I have (around 8 million rows). The same query on version 1.1.0 completes with 370 MB RAM.

            using (var oc = new OleLibrary.OleEntityFrameworkCoreContext())
            {
                var l = oc.Bibs.Select(b => b.Id).ToArray();
                Console.WriteLine("Press any key...");
                Console.ReadLine();
            }

MySQL version: 5.7.18
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.1.1

**Comment by caleblloyd** [comment] 2017-04-20 00:53
This may be due to [Buffered Result Sets](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/226), which were added for `1.1.1`

I wonder if Entity Framework is querying the entire row, then just reading the `Id` column from the reader.  Could you post the generated SQL from the `SELECT` statement?  An example of how to turn `Microsoft` logging level to `Information` can be found in [this comment](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/259#issuecomment-294293559) if you need an example.

**Comment by jemiller0** [comment] 2017-04-20 01:14
It looked like it pulled the data down at first I could see network activity. But, then, it seems to do a lot of processing in memory where there isn't much network activity, but, memory climbs a lot.

I had a similar problem with the SQL Server provider, but, found out that it was because I had EnableRetryOnFailure() enabled, which causes the provider to buffer the results. However, I'm not doing that with the Pomelo provider. I've been using version 1.1.0 for awhile now and haven't really had any issues until I upgraded to Pomelo 1.1.1. Note, 1.1.0, seems to work alright with EF Core 1.1.1.

![image](https://cloud.githubusercontent.com/assets/15931877/25208759/480c1f92-253c-11e7-85b3-e47a3aeb47b2.png)

**Comment by bgrainger** [comment] 2017-04-20 01:31
Do you have access to a memory profiling tool such as [dotMemory](https://www.jetbrains.com/dotmemory/), [ANTS Memory Profiler](http://www.red-gate.com/products/dotnet-development/ants-memory-profiler/), [.NET Memory Profiler](http://memprofiler.com/), or similar?

Providing more detailed information about the type and number of managed objects in the heap will be helpful in troubleshooting this.

(There are also free tools that can provide this information that are a little harder to use.)

**Comment by jemiller0** [comment] 2017-04-20 01:38
I have Visual Studio 2017 Enterprise, which has a profiler built into it. However, I don't have a lot of experience with it, but, I can see what I can figure out tomorrow. I ran it earlier today with the SQL Server provider when I ran into the problem with EnableRetryOnFailure(). I posted some screen shots of that at 
https://github.com/aspnet/EntityFramework/issues/7363. I'm not sure if a screenshot such as that would help, or, if you would need something more detailed. I think you could probably reproduce the problem pretty easily with any context. The only catch is that you would need to have a lot of rows in the table. Not sure how wide the table would need to be. I could probably provide an example context. I would need to trim things down though as the one that I'm using is big and complicated since it was generated from a legacy database that has a lot of composite keys, etc..

**Comment by bgrainger** [comment] 2017-04-20 01:48
A complete code sample that reproduces the problem is probably much more helpful. (I don't personally have any experience with EF Core, so I can't easily attempt to recreate this problem; my experience is with the underlying MySqlConnector library. A repro could show me where the problem lies.)

**Comment by caleblloyd** [comment] 2017-04-20 02:11
I'm able to recreate.  I think the issue may be with Buffered Result Sets.  I just ran a test before and after 240aae7281220e8ac5f47e97084546755f9b9e81, which added Buffered Result Sets.

Before: Read completes in 4 seconds, memory stays relatively
After: Read completes in 17 seconds (including buffering), memory spikes to 5GB

I wonder if [ArrayPool.Shared.Rent/Return](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/Results/Row.cs#L33) is to blame here.  I can't find good documentation on ArrayPool.Shared.Rent/Return, except for https://github.com/dotnet/corefx/issues/4547 where it was initially implemented.  That documentation does say:

> The Pool is guaranteed to return a Buffer of at least the specified size; the actual size may be larger to due buffer availability

Maybe we are getting very large buffers and hardly filling them with very small rows (like these rows that simply select an ID).  I'll do more testing and submit a fix over the next few days.  @Kagamine we will likely need a patch release for this (such as `1.1.1-update1`).

For what it's worth, I don't think this is so much a "Memory Leak" as it is "Excess Allocation".

**Comment by caleblloyd** [comment] 2017-04-20 02:30
```
      SELECT `m`.`Id`
      FROM `Blogs` AS `m`
      LIMIT 1000
```
Here are the actual links allocated by ArrayPool.Shared.Rent/Return:

```
bufferDataLengths: Wanted 1 Got 16
bufferedDataOffsets: Wanted 1 Got 16
bufferedPayload: Wanted 16384 Got 16384
bufferDataLengths: Wanted 1 Got 16
bufferedDataOffsets: Wanted 1 Got 16
bufferedPayload: Wanted 16384 Got 16384
bufferDataLengths: Wanted 1 Got 16
bufferedDataOffsets: Wanted 1 Got 16
bufferedPayload: Wanted 16384 Got 16384
```

I think that `bufferedPayload` must span multiple MySQL rows and the whole thing should not be buffered like this.  I'll open an issue in MySqlConnector and work it over the next couple of days.

**Comment by jemiller0** [comment] 2017-04-20 03:23
Yeah, I did notice that the memory jump around. It went up to 28 GB and then came back down again, then, went back up a lot. It wasn't like it got allocated and was never released. I let it run awhile, but, it didn't complete. I cancelled out after 5 minutes or so.

**Comment by Kagamine** [comment] 2017-04-20 05:03
> Maybe we are getting very large buffers and hardly filling them with very small rows (like these rows that simply select an ID). I'll do more testing and submit a fix over the next few days. @Kagamine we will likely need a patch release for this (such as 1.1.1-update1).

In nuget version rule, `1.1.1-update1 < 1.1.1`, maybe we can release 1.1.2?

**Comment by jemiller0** [comment] 2017-04-20 14:00
On an unrelated note, that I can submit a different issue on for the lower-level driver. I've been noticing that if an exception occurs, and Dipose() is called a lot of times, I've been finding that it will give an error about the session not being connected like below. However, I think this is an exception that happens after another exception and the original exception gets masked. It seems like maybe there needs to be a check in the Dipose() method to see if the connection is in a state that it needs to be closed. If I remember correctly, Dispose() is never supposed to throw exceptions, but, I would have to double check that. I've also seen various strange issues where if you are streaming/iterating over a results set, that if an exception occurs in the foreach, it will wait until after all the results have been iterated before throwing the exception. Not at all relevant to this bug, just something I've been running into as of late. The Dispose() problem is an annoying one because it seems to mask the original exception. I will have to come up with repros for those issues.

System.InvalidOperationException: MySqlSession is not connected.
   at MySql.Data.Serialization.MySqlSession.VerifyConnected()
   at MySql.Data.Serialization.MySqlSession.TryAsync(Func`3 func, IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySql.Data.Serialization.MySqlSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Results.ResultSet.ScanRowAsync(IOBehavior ioBehavior, Row row, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadEntireAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<NextResultAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.DoClose()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing)
   at MySql.Data.MySqlClient.MySqlConnection.CloseDatabase()
   at MySql.Data.MySqlClient.MySqlConnection.DoClose()
   at MySql.Data.MySqlClient.MySqlConnection.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Dispose()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalConnection.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at Microsoft.EntityFrameworkCore.DbContext.Dispose()
   at OleLibrary.OleEntityFrameworkCoreContext.Dispose() in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Ole\OleLibrary\OleEntityFrameworkCoreContext.g.cs:line 215970
   at LibraryConsoleApplication.Program2.LoadExtents() in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Library\LibraryConsoleApplication\Program2.cs:line 1972
   at LibraryConsoleApplication.Program2.Main(String[] args) in C:\Users\jemiller\Documents\Visual Studio 2017\Projects\Library\LibraryConsoleApplication\Program2.cs:line 201

**Comment by caleblloyd** [comment] 2017-04-20 14:07
I believe that was already fixed in https://github.com/mysql-net/MySqlConnector/commit/be4c54f7d2c93475b0266e83eaefe2c92b2a76da and is in MySqlConnector 0.16.2.  Version 1.1.1 of this library uses MySqlConnector 0.16.1 however.

**Comment by caleblloyd** [comment] 2017-04-21 00:59
A fix is inbound https://github.com/mysql-net/MySqlConnector/pull/247

**Comment by bgrainger** [comment] 2017-04-21 14:45
Fixed in [MySqlConnector 0.18.0](https://www.nuget.org/packages/MySqlConnector/0.18.2).

**Comment by jemiller0** [comment] 2017-04-21 15:01
Thanks guys. Will test this out soon, probably today.

**Comment by caleblloyd** [comment] 2017-04-23 18:09
I tested on 8 million rows and hit around 1GB of Memory Usage, command completed as expected. @jemiller0 does the latest `1.1.2-*` work for you?

@Kagamine I think we need to do a bugfix release for this issue.  It just built [1.1.2-preview-10038](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/1.1.2-preview-10038), that should be a good release candidate.  It's got some additional performance improvements that @bgrainger added in https://github.com/mysql-net/MySqlConnector/pull/245

Should we call the bugfix release `1.1.1-update1`, or should we go ahead and release `1.1.2`?

**Comment by Kagamine** [comment] 2017-04-23 23:35
1.1.2 is better

**Closed** 2017-04-26 03:37 UTC
Labels: type-bug

**Comment by jemiller0** [comment] 2017-05-05 19:33
Sorry for not replying to this sooner. I just did a test. I used the latest MySqlConnector for both tests.

`<package id="MySqlConnector" version="0.19.2" targetFramework="net47" />`

With  `<package id="Pomelo.EntityFrameworkCore.MySql" version="1.1.0" targetFramework="net47" />` I get 370.4 MB.

With `<package id="Pomelo.EntityFrameworkCore.MySql" version="1.1.2-preview-10038" targetFramework="net47" />` I get 2490.4 MB.

So, it looks like there is still something wrong.

2490.4 MB

**Comment by jemiller0** [comment] 2017-05-05 19:37
Not as bad as before though. It actually works now, although it's using an extra 2 GB RAM.

**Comment by caleblloyd** [comment] 2017-05-05 20:00
Buffering the entire result set will naturally consume more memory, because we read all MySqlConnector row objects into memory upfront now.  I don't think this is a "leak" anymore, it is just what happens when you buffer millions of MySqlConnector rows.

Using an ORM for huge data operations like this is generally a bad idea.  I'm glad that you did to find the initial memory leak, but this is not a case we should optimize for.

**Comment by jemiller0** [comment] 2017-05-05 20:29
Note, I'm selecting around 8 million INT values doing a projection. I'm not querying for entire entities. I just tried the same query with the latest SQL Server provider and it uses 371.9 MB, almost identical to what I get with the Pomelo 1.1.0 provider. If I enable `options.EnableRetryOnFailure()` on the SQL Server provider, it uses 1,070.7 MB. I learned that enabling retry on failure with the SQL Server provider does do additional buffering. The SQL Server provider is still using less than half of what the Pomelo provider is.

I just tried the same query using Dapper. It uses 214.1 MB.

**Comment by jemiller0** [comment] 2017-05-05 20:35
I just tested it with the latest PostgreSQL EF Core provider. 373.6 MB on that.

**Comment by caleblloyd** [comment] 2017-05-05 21:58
We use buffering to get around the fact that MySQL does not support Multiple Active Result Sets. SQL Server can use less memory because it supports keeping multiple result sets open on a single connection and therefore does not have to buffer them.

If we switch back to the behavior pre-buffering, we would have to add back in the complicated locking hacks to ensure that an entire result set was read before we let another query execute. In my opinion, it's worth the extra memory usage to avoid these hacks. It makes it much easier to track upstream Entity Framework, because when they update, often these hacks would break and need to be re-worked.

That being said, we could probably lower the memory fooyprint of buffered results, however that would need to take place in MySqlConnector. I'll open an issue to track this there.

**Comment by masums** [comment] 2018-03-15 15:44
For 2M rows, it takes 31GB of RAM for me. Is there have any solution?

**Comment by mguinness** [comment] 2018-03-15 16:55
@masums Try posting your specific issue at the underlying library [repo](https://github.com/mysql-net/MySqlConnector/) as this issue is closed.
