### ISSUE TITLE
Scaffold-DbContext issue

### ISSUE THREAD

**Issue by JoSaint13** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#109] opened 2016-11-07 22:16 UTC
### Steps to reproduce
I am trying to make reverse engineering and create classes from existing database by using Scaffold
command:
Scaffold-DbContext "connection string" Pomelo.EntityFrameworkCore.MySql -Verbose

This is working for Microsft.EntityFrameworkCore.
![verbose log](https://cloud.githubusercontent.com/assets/14937013/20078265/8019c8b8-a548-11e6-9093-347044d6ddc3.png)

**Comment by Kagamine** [comment] 2016-11-07 23:14
Dupe of #55

**Closed by Kagamine** 2016-11-07 23:14 UTC

**Comment by Kagamine** [comment] 2016-11-22 03:11
@JoSaint13 We have supported DbContext Scaffolding in 1.1.0-rtm-10003.
