### ISSUE TITLE
Remove-Migration GUID PK Snapshot Conflicts

### ISSUE THREAD

**Issue by amro93** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1212] opened 2020-10-24 06:29 UTC
### Steps to reproduce

1- Create a migration on top of an existing migration for Dbsets of a GUID PK
2= Remove this migration
3= Create the same migration again

exception thrown
No mapping to a relational type can be found for property 'Abp.Webhooks.WebhookSubscriptionInfo.Id' with the CLR type 'string'.

![image](https://user-images.githubusercontent.com/34315258/97069796-eab55580-15d2-11eb-9980-ce8ad5bd5b7a.png)

Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.9 initialized 'BrisklyDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 8.0.21 MySql SensitiveDataLoggingEnabled DetailedErrorsEnabled 
System.InvalidOperationException: No mapping to a relational type can be found for property 'Abp.Webhooks.WebhookSubscriptionInfo.Id' with the CLR type 'string'.
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSourceExtensions.GetMapping(IRelationalTypeMappingSource typeMappingSource, IProperty property)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IProperty source, IProperty target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(TableMapping source, TableMapping target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Other details about my project setup:

**Comment by lauxjpn** [comment] 2020-10-24 08:47
This is a duplicate of #1002. We reported the issue to the EF Core team with https://github.com/dotnet/efcore/issues/19637.
It is possible, that this issue has been resolved for 5.0 (we have not checked that yet).

**Closed by lauxjpn** 2020-10-24 08:47 UTC
Labels: closed-duplicate, type-bug
