### ISSUE TITLE
Count()=>System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by csurn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#34] opened 2016-08-02 08:53 UTC
### Steps to reproduce
```
public ActionResult Users(PagedModel<User> model)
{
    var query = this._userRepo.Query();
    if (!string.IsNullOrWhiteSpace(model.Keyword))
    {
        var keyword = model.Keyword.Trim();
        query = query.Where(o => o.UserName.Contains(keyword));
    }
    model.Total = query.Count();
    model.List = query.OrderByDescending(o => o.CreateAt)
        .Skip(model.PageSize * (model.PageIndex - 1)).Take(model.PageSize)
        .ToList();
    return View(model);
}
```

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
{System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.BitConverter.ToUInt16(Byte[] value, Int32 startIndex)
   at Pomelo.Data.MySql.MySqlPacket.ReadLong(Int32 numbytes)
   at Pomelo.Data.MySql.NativeDriver.GetColumnData(MySqlField field)
   at Pomelo.Data.MySql.NativeDriver.GetColumnsData(MySqlField[] columns)
   at Pomelo.Data.MySql.Driver.GetColumns(Int64 count)
   at Pomelo.Data.MySql.ResultSet.LoadColumns(Int64 numCols)
   at Pomelo.Data.MySql.ResultSet..ctor(Driver d, Int32 statementId, Int64 numCols)
   at Pomelo.Data.MySql.Driver.NextResult(Int32 statementId, Boolean force)
   at Pomelo.Data.MySql.MySqlDataReader.NextResult()
   at Pomelo.Data.MySql.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at Web.Controllers.AdminController.Users(PagedModel`1 model) in C:\Users\wanggang\Documents\Visual Studio 2015\Projects2\ARBookServer\ARBookServer\Controllers\AdminController.cs:line 100
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()}
Stack trace:
```

### Further technical details

MySQL version: MySQL 55
Operating system: windows 10 x64

Other details about my project setup:
this error do not appear when I swith database to sqlite.

**Comment by Kagamine** [comment] 2016-08-02 09:20
Hi @csurn, Are you sure the database default charset is `utf8`?

Could you run the following command in your mysql?
```sql
show variables like 'character_set_database';
```

**Comment by Kagamine** [comment] 2016-08-02 09:26
![image](https://cloud.githubusercontent.com/assets/2216750/17323817/23886212-58d6-11e6-8742-dd74081c6cfb.png)

I made a simple console application, but could not reproduce your issue.

**Comment by csurn** [comment] 2016-08-03 01:58
Hi there,thanks for your libiary and response.
I have changed  MySQL 5.5 up to 5.7 and database set is utf-8,but still have problem.
With this code:
`public JsonResult NotHasUserName(string userName, Guid? id)
{
    if (id.HasValue)
    {
        var userId = id.Value;
        return Json(!this._userRepo.Query().Any(o => o.Id != userId && o.UserName == userName));
    }
    else
    {
        return Json(!this._userRepo.Query().Any(o => o.UserName == userName));
    }
}`
When I run many requests which url is "http://localhost:8002/Remote/NotHasUserName?UserName=gsuser1&Id=f1d7de91-c002-49a5-b6a8-c3e875d57c99". Some of request will throw exception at code 'Any()' 'System.FormatException':Input string was not in a correct format.

   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Pomelo.Data.Types.MySqlInt64.Pomelo.Data.Types.IMySqlValue.ReadValue(MySqlPacket packet, Int64 length, Boolean nullVal)
   at Pomelo.Data.MySql.ResultSet.ReadColumnData(Boolean outputParms)
   at Pomelo.Data.MySql.ResultSet.NextRow(CommandBehavior behavior)
   at Pomelo.Data.MySql.MySqlDataReader.Read()
   at Pomelo.Data.MySql.Driver.LoadCharacterSets(MySqlConnection connection)
   at Pomelo.Data.MySql.Driver.Configure(MySqlConnection connection)
   at Pomelo.Data.MySql.MySqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at Web.Controllers.RemoteController.NotHasUserName(String userName, Nullable`1 id) in C:\Users\wanggang\documents\visual studio 2015\Projects2\ARBookServer\ARBookServer\Controllers\RemoteController.cs:line 51
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()

And then if I skip the exception,if I request url "http://localhost:8002/Admin/Users",the exception what I post here yesterday will appeard.
The code is :
`public ActionResult Users(PagedModel<User> model)
{
    var query = this._userRepo.Query();
    if (!string.IsNullOrWhiteSpace(model.Keyword))
    {
        var keyword = model.Keyword.Trim();
        query = query.Where(o => o.UserName.Contains(keyword));
    }
    model.Total = query.Count();
    model.List = query.OrderByDescending(o => o.CreateAt)
        .Skip(model.PageSize * (model.PageIndex - 1)).Take(model.PageSize)
        .ToList();
    return View(model);
}`
query.Count() throw 'omelo.Data.MySql.MySqlException':Fatal error encountered during command execution.

{Pomelo.Data.MySql.MySqlException: Fatal error encountered during command execution. ---> System.IO.IOException: Unable to write data to the transport connection: 你的主机中的软件中止了一个已建立的连接。. ---> System.Net.Sockets.SocketException: 你的主机中的软件中止了一个已建立的连接。
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at Pomelo.Data.Common.MyNetworkStream.HandleOrRethrowException(Exception e)
   at Pomelo.Data.Common.MyNetworkStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Pomelo.Data.MySql.TimedStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Pomelo.Data.MySql.MySqlStream.SendPacket(MySqlPacket packet)
   at Pomelo.Data.MySql.NativeDriver.ExecutePacket(MySqlPacket packetToExecute)
   at Pomelo.Data.MySql.NativeDriver.SendQuery(MySqlPacket queryPacket)
   at Pomelo.Data.MySql.Driver.SendQuery(MySqlPacket p)
   at Pomelo.Data.MySql.Statement.ExecuteNext()
   at Pomelo.Data.MySql.PreparableStatement.Execute()
   at Pomelo.Data.MySql.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   --- End of inner exception stack trace ---
   at Pomelo.Data.MySql.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
   at Web.Controllers.AdminController.Users(PagedModel`1 model) in C:\Users\wanggang\documents\visual studio 2015\Projects2\ARBookServer\ARBookServer\Controllers\AdminController.cs:line 100
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()}

In my code,'Query()' is like this:

`public IQueryable<T> Query(params Expression<Func<T, object>>[] includeExpressions)
{
    IQueryable<T> query = _entities;
    foreach (var includeExpression in includeExpressions)
    {
        query = query.Include(includeExpression);
    }

    return query;
}`

**Comment by Kagamine** [comment] 2016-08-03 02:05
Can you upload your full source?

**Comment by Kagamine** [comment] 2016-08-03 02:08
What's your qq number?

**Comment by csurn** [comment] 2016-08-03 02:13
76527413

**Comment by Kagamine** [comment] 2016-08-03 02:14
@csurn  ![image](https://cloud.githubusercontent.com/assets/2216750/17351640/ff5da342-5962-11e6-9f98-aeec3589680a.png)

**Comment by csurn** [comment] 2016-08-03 02:14
13694306530

**Comment by Kagamine** [comment] 2016-08-03 02:18
![image](https://cloud.githubusercontent.com/assets/2216750/17351706/8d6b3d02-5963-11e6-9f01-aef5a05a3d73.png)

**Comment by csurn** [comment] 2016-08-03 02:18
sorry.the answer is '我也不知道'

**Comment by Kagamine** [comment] 2016-08-03 03:37
@csurn I saw you have registered the db context as singleton,. MySQL doesn't support use singleton dbcontext yet.

```
            services.AddSingleton<DbContext, EfDbContext>();
            services.AddTransient(typeof(IRepository<>), typeof(Repository<>));
            services.AddSingleton<IXmlRepository, ConfigXmlRepository>();
```

So, closed this by design.

**Closed by Kagamine** 2016-08-03 03:38 UTC
Labels: type-investigation

**Comment by csurn** [comment] 2016-08-03 04:11
thanks.
