### ISSUE TITLE
Unknown column 'GENERATION_EXPRESSION' in 'field list'

### ISSUE THREAD

**Issue by Rainson12** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1400] opened 2021-04-23 15:31 UTC
### Steps to reproduce
I tried to scaffold a mysql table.

### The issue
scaffolding the table didnt work and threw the following error:
```
MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'GENERATION_EXPRESSION' in 'field list'
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown column 'GENERATION_EXPRESSION' in 'field list'
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 130
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 210
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetColumns(DbConnection connection, IReadOnlyList`1 tables, Func`3 tableFilter)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.GetTables(DbConnection connection, Func`3 filter)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, DatabaseModelFactoryOptions options)
   at Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, DatabaseModelFactoryOptions options)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unknown column 'GENERATION_EXPRESSION' in 'field list'
```

### Further technical details

MySQL version: 5.1.38-community
Operating system: Windows Server 2012
Pomelo.EntityFrameworkCore.MySql version: i have tried all versions
Microsoft.AspNetCore.App version: tried 5.0 and 3.1

**Comment by lauxjpn** [comment] 2021-04-23 15:36
@Rainson12 Please post the result of the `` SHOW CREATE TABLE `YourTable` `` command, so we get an idea of how the table looks.

> Pomelo.EntityFrameworkCore.MySql version: i have tried all versions

That is not precise enough for us to investigate this. What exact version of Pomelo did you use that generated the exception that you posted?

**Comment by Rainson12** [comment] 2021-04-23 15:39
I just tried again with 5.0.0-beta.1, 3.2.5 and 3.2.4

heres the show create table:
```
CREATE TABLE `tab_pat` (
  `IndexNr` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `MatchNr` varchar(255) NOT NULL,
  `OPDatum` varchar(45) DEFAULT NULL,
  `Timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `WeitereOP1Organ` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`IndexNr`)
) ENGINE=InnoDB AUTO_INCREMENT=21985 DEFAULT CHARSET=utf8
```

**Comment by lauxjpn** [comment] 2021-04-23 15:42
> MySQL version:

What version of MySQL/MariaDB/Aurora are you using?

**Comment by Rainson12** [comment] 2021-04-23 15:44
sorry seems like i forgot to paste it: its 5.1.38-community

**Comment by lauxjpn** [comment] 2021-04-23 15:54
> its 5.1.38-community

That is the issue. MySQL is complaining, that we use the `GENERATION_EXPRESSION` field of the `INFORMATION_SCHEMA.COLUMNS` table/view.

That should be supported in MySQL 5.7, which is the lowest version that we officially support.

Support for MySQL 5.1 from Oracle ended 8.5 years ago on 2013-12-31 (from [MySQL Product Support EOL Announcements: MySQL 5.1 covered under Oracle Lifetime Sustaining Support](https://www.mysql.com/support/eol-notice.html)):

> #### December 4, 2013
>
>## MySQL 5.1 covered under Oracle Lifetime Sustaining Support
>Per [Oracle's Lifetime Support policy](https://www.mysql.com/support/), as of December 31, 2013, MySQL 5.1 is covered under Oracle Sustaining Support.
>
>Users are encouraged to upgrade to MySQL 5.6.

So you need to upgrade your database server, if you want to use it with Pomelo.

**Comment by lauxjpn** [comment] 2021-04-23 16:10
For the 5.0 branch, the usage of the `GENERATION_EXPRESSION` field was introduced with #1260. So no public 5.0 release will work in your case.

For the 3.2 branch (targeting EF Core 3.1), the field was added with #1257, so the 3.2.4 release should work for you.

You mentioned, that you tried 3.2.4 as well and it failed too. Did it fail with the same error, or a different one?

**Comment by Rainson12** [comment] 2021-04-23 16:18
> @Rainson12 You mentioned, that you tried 3.2.4 as well and it failed too. Did it fail with the same error, or a different one?

it failed with the same message. But its fair to say its a pretty old database. I got it working using the official mysql dotnet core package.

**Comment by lauxjpn** [comment] 2021-04-23 16:38
> I got it working using the official mysql dotnet core package.

I am glad that you found a practical solution for you that works.

---

> You mentioned, that you tried 3.2.4 as well and it failed too. Did it fail with the same error, or a different one?

> it failed with the same message. [...]

That is not possible. Release [3.2.4](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/releases/tag/3.2.4) went public on 2020-11-02, but the PR that introduced the usage of `GENERATION_EXPRESSION` was pushed 3 weeks later on 2020-11-24.

I also manually checked [the code](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/b5f0983a9713ab719c76ea7730d2bf9aeaeb2fb4/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs) and even scaffolded a database with 3.2.4 successfully (against MySQL 5.6, which does not support the `GENERATION_EXPRESSION` column yet as well), before I made my post above.

So I am absolutely certain, that you don't get this error message, when you scaffold with 3.2.4.

If you get the error message, you are not using 3.2.4 when you scaffold, but a newer version (3.2.5 or a 5.0.0 prerelease).

**Comment by mguinness** [comment] 2021-04-23 18:32
Probably not worth it, but I guess we could substitute `GENERATION_EXPRESSION` w/ `NULL AS GENERATION_EXPRESSION` for version < 5.7

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/6aac749dc0190cd16e3869f05dee4694eafdf75f/src/EFCore.MySql/Scaffolding/Internal/MySqlDatabaseModelFactory.cs#L259

**Comment by lauxjpn** [comment] 2021-04-24 02:34
> I guess we could substitute `GENERATION_EXPRESSION` w/ `NULL AS GENERATION_EXPRESSION` for version < 5.7

I was thinking about something similar, but not much because of MySQL 5.1, but because the GENERATED ... STORED support broke backwards compatibility with MySQL 5.6, which I unofficially tried to maintain as much as possible (even though it reached EOL this February as well).

**Comment by KiristonK** [comment] 2021-04-27 08:05
Hi, what compatibilty of Pomelo with MariaDB? Asking this because i'm getting same error while trying to Scaffold DbContext with EF core (v. 5.0.5). Db ver.: 10.1.21-MariaDB. Will Pomelo work if i'll write all models and context by myself, without auto generating code by EF commands?

**Comment by lauxjpn** [comment] 2021-04-28 13:39
@Rainson12 The fix is part of the 5.0.0 GA release today (and will be part of the next 3.1 servicing release, though there is no date for that yet). While this fix is intended for MySQL 5.6, it will also fix the issue for 5.1.

**Comment by Rainson12** [comment] 2021-04-29 07:46
> @Rainson12 The fix is part of the 5.0.0 GA release today (and will be part of the next 3.1 servicing release, though there is no date for that yet). While this fix is intended for MySQL 5.6, it will also fix the issue for 5.1.

congrats on the release. I can confirm it works now. Thanks a lot!

**Comment by lauxjpn** [comment] 2021-04-29 08:08
> I can confirm it works now.

For an overview about limitations you might encounter when still on MySQL 5.1, take a look a the [MySqlServerVersion.MySqlServerVersionSupport](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/5b518baffb7f9f47086dfdcb0a0d64c24ee90e1f/src/EFCore.MySql/Infrastructure/MySqlServerVersion.cs#L45-L85) class.

> is there anyway to buy/or the project you a coffee? ;)

No worries, I am glad it works for you. Currently, the only way to thank us/the project is by participating (especially the wiki needs some love). If you gain any MySQL 5.1 specific insights over the next few weeks/month in regards to Pomelo, feel free to make them part of the wiki.

**Comment by gao-artur** [comment] 2021-07-06 12:53
Still reproduced with v3.2.6 on Aurora MySql 5.6.10

**Comment by mguinness** [comment] 2021-07-06 16:54
@gao-artur If you are stuck on MySQL 5.6 then you could try 3.2.4 of Pomelo.

Is there a reason you cannot [upgrade to 5.7](https://aws.amazon.com/about-aws/whats-new/2021/01/amazon-aurora-supports-in-place-upgrades-mysql-5-6-to-5-7/)?  I know Amazon are force updating RDS instances, see [Announcement: Amazon Relational Database Service (RDS) for MySQL 5.6 End-of-Life date is August 3, 2021](https://forums.aws.amazon.com/ann.jspa?annID=8498).

**Comment by gao-artur** [comment] 2021-07-06 21:50
Hey @mguinness, we are definitely going to upgrade, just wanted to let you know that this issue still exist even so it was stated that it was fixed for versions below 5.7.

**Comment by mguinness** [comment] 2021-07-07 00:16
You misunderstood, it was stated that it was fixed for 5.0 and the earlier version would be fixed at a later date (not specified).

> The fix is part of the 5.0.0 GA release today (and will be part of the next 3.1 servicing release, though there is no date for that yet).

**Comment by gao-artur** [comment] 2021-07-07 05:50
You right. Just saw it as closed under 3.2.6 milestone and thought it was merged.

**Comment by lauxjpn** [comment] 2021-07-07 07:11
> [...] will be part of the next 3.1 servicing release [...]

> Just saw it as closed under 3.2.6 milestone and thought it was merged.

Looks to me we just forgot about that part.

**Comment by lauxjpn** [comment] 2021-07-07 10:12
The backport will be part of `3.2.7`.
Use the latest `3.2` [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) until then.

**Closed by lauxjpn** 2021-07-07 10:12 UTC
Labels: type-enhancement

**Comment by gao-artur** [comment] 2021-07-07 17:46
Thank you!
