### ISSUE TITLE
Reevaluate DateTimeOffset support

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#819] opened 2019-09-10 16:36 UTC
At this point in time, MySQL does not have any native support to store a `DateTimeOffset` (basically a `DateTime` + its offset from UTC).

The current provider implementation is not working **[Update] with all tests[/Update]**. On the one hand, it just returns a `DateTime`, where the offset is already applied. On the other hand, because EF expects a `DateTimeOffset` returned instead of a `DateTime`, an exception is thrown.

We should discuss the way to go from here. I think there are at least three possible directions:

1. Remove the faulty `DateTimeOffset` implementation entirely. If the user wants to use a `DateTimeOffset`, he needs to implement his own `ValueConverter` on his model.
2. Implement a proprietary representation of a `DateTimeOffset` on the MySQL storage side (e.g. 64 bit uint, with the highest 5 bits representing the offset, or a string representation of the date + offset).
3. Keep the current (faulty) implementation alive by making sure, that the MySQL returned `DateTime` (with the offset already applied) is converted to a `DateTimeOffset` (with an offset of 0), before it gets returned to the caller/EF (which circumvents the current exception).

For the upcoming 2.2.6 PR, I implemented option 3, though this seems to be the worst one. It also (rightfully so) fails the corresponding tests.

**Comment by crozone** [comment] 2019-09-11 07:27
Under what circumstances are you seeing an exception thrown for `DateTimeOffset`? We have been using `DateTimeOffset` our entities for over a year without issues. With a single exception (that I have already merged a PR for), even the migrations work in the same way as `DateTime`.

As to the lack of offset storage support, I believe this is expected and works as intended. MySQL has no column type that supports any timezone offset. This is the same for Postgresql. Pomelo handles `DateTimeOffset` the same way that `Npgsql` does, which is where the `DateTimeOffset` is converted to UTC 0 and stored in the database as `DATETIME(6)` with UTC 0. This is still highly advantageous compared to using `DateTime` since there is never any ambiguity as to what conversion will occur when going into the database. It has been the de-facto method for storing `DateTimeOffset`s in .NET ORMs for some time.

If you need to store the actual timezone that was set, this should be stored as a separate column. The `DateTimeOffset` can then be adjusted back to this timezone after it is retrieved.

Using the top 5 bits is non-standard and would break any query that expects the time to be a sane value, so I don't like option 2. Option 1 is cumbersome. As far as I was aware, option 3 is close to how it currently already operates, and I'm interested to see your failure case.

**Comment by lauxjpn** [comment] 2019-09-11 14:16
I have not check the behavior in an actual application, but all of the `Query.GearsOfWarQueryMySqlTest.DateTimeOffset_*` tests fail with the following exception:
```
```
I understand, that this is a workaround, that is being used. I think it is worth discussing though, if this is actually appropriate or should be changed with a major release.

My main argument for option 1 would be, that the main reason to use `DateTimeOffset` in the first place, is to have a UTC date/time stored with an offset. If the offset isn't retained, why use a `DateTimeOffset` at all? It can only be appropriately used, if the developer is aware of the fact, that the offset isn't kept and if he is, he could use a `DateTime` in the first place.
I am not arguing, that this isn't practical. It's just not the intended design of a `DateTimeOffset`.

Another solution could be, to supply a specific option to opt-in to, to request the non-standard behavior.

**Comment by crozone** [comment] 2019-09-13 07:32
After some additional research, this scenario should already be supported by using these built in value converters:

[`DateTimeOffsetToBinaryConverter`](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/Storage/ValueConversion/DateTimeOffsetToBinaryConverter.cs) - DateTimeOffset to binary-encoded 64-bit value (stores it as a long, slight reduction in precision)

[`DateTimeOffsetToBytesConverter`](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/Storage/ValueConversion/DateTimeOffsetToBytesConverter.cs) - DateTimeOffset to byte array (stores it as a 12 byte array, 8 bytes for time, 4 bytes for offset. Full precision.)

[`DateTimeOffsetToStringConverter`](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore/Storage/ValueConversion/DateTimeOffsetToStringConverter.cs) - DateTimeOffset to string (ISO 8601 string including timezone)

These can be activated pretty easily:

`builder.Entity<SomeEntity>().Property(del => del.SomeDateTimeOffsetProperty).HasConversion<DateTimeOffsetToBytesConverter>();`

[Source](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)

I'm still investigating ways to have the database automatically store the offset as a separate column using a custom value generator on a shadow property, however this might be a waste of time given the above methods probably work well for most scenarios.

**Comment by lauxjpn** [comment] 2019-09-13 12:34
Great find!
I guess in this case, it's enough to just extend the wiki to document the `DateTimeOffset` behavior and mention the value converters.

**Comment by lauxjpn** [comment] 2019-09-30 00:19
Let's keep this open for a bit, as a reminder to recheck the current `DateTimeOffset` behavior. There were same suspicious test cases, I want to recheck before the GA release of 3.0.0.

**Comment by crozone** [comment] 2019-10-02 01:48
After reviewing the code, I can't actually find anywhere where a conversion to universal time is being done before storage. I suspect this will also lead to differing behaviour depending on column type - `TIMESTAMP` apparently does a conversion from the database connection timezone into UTC 0 as it is saved. `DATETIME` apparently does not, it just saves the time as is and then returns it as is. In the `DATETIME` case, always converting to UTC 0 seems quite necessary.

**Comment by bgrainger** [comment] 2019-10-02 03:38
> I can't actually find anywhere where a conversion to universal time is being done before storage

In the underlying MySQL library, MySqlConnector, a conversion to UTC is performed if `MySqlParameter.Value` is a `DateTimeOffset`: https://github.com/mysql-net/MySqlConnector/blob/05df17a6f4e2f6c899598e00f0790badc7195296/src/MySqlConnector/MySql.Data.MySqlClient/MySqlParameter.cs#L332-L336

The value has to be serialized on the wire somehow, and MySqlConnector elects to coerce everything to UTC, since information will be lost (because MySQL can't store `DateTimeOffset` natively). The alternative would be throwing an exception.

**Comment by lauxjpn** [comment] 2019-10-02 20:15
@bgrainger Thanks for the code reference.
We should implement the same behavior for DateTimeOffset literals then to keep the behavior consistent.

Our current implementation does not explicitly use `UtcDateTime.UtcDateTime` and is probably just using local time then.

We can start by adding a test to check for consistent behavior between queries with and without parameters and go from there to fix our current implementation.

**Comment by crozone** [comment] 2019-10-03 02:20
@bgrainger Cheers for finding that reference. I've also found the conversion on the read for future reference too:

https://github.com/mysql-net/MySqlConnector/blob/9b8f3a4d8259144b52990d804f1dca303314289f/src/MySqlConnector/Core/Row.cs#L334

@lauxjpn Good catch with the literals, I wasn't aware that EF inlined constants like that.

**Comment by bgrainger** [comment] 2019-10-03 02:24
See https://github.com/mysql-net/MySqlConnector/issues/172 and https://github.com/mysql-net/MySqlConnector/issues/175 for the background of the decisions around `DateTimeOffset` in MySqlConnector.

**Closed** 2019-10-03 17:02 UTC

**Comment by VictorioBerra** [comment] 2019-10-26 15:38
> @crozone So our current implementation does not explicitly use DateTimeOffset.UtcDateTime and is probably just using local time then.

So, if someone wanted to use explicitly use DateTimeOffset.UtcDateTime on save, how would they do that?

**Comment by lauxjpn** [comment] 2019-10-27 15:41
This is the default.

**Comment by johnwc** [comment] 2021-11-13 04:40
I know this is a few years old, but I feel that it needs to be made clear that MySQL does know how to handle time zone information. It may not store it, but it DOES know how to handle it when it's given in INSERT and UPDATE statements. If the time zone is given, it will convert it to UTC. Where if it is not given, it assumes it is UTC. The example given below, shows that MySQL will store both inserts as different dates. With the second adjusted to UTC.

```SQL
CREATE TABLE IF NOT EXISTS test_TZ (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DTvalue DATETIME NOT NULL,
	TSvalue TIMESTAMP NOT NULL
);

INSERT INTO test_TZ (DTvalue, TSvalue) VALUES ('2021-11-12 10:30:00', '2021-11-12 10:30:00');
INSERT INTO test_TZ (DTvalue, TSValue) VALUES ('2021-11-12 10:30:00+06:00', '2021-11-12 10:30:00+06:00');
```

**Comment by mguinness** [comment] 2021-11-13 06:49
There's an open issue [Implement value conversions that spread out over multiple columns (value objects)](https://github.com/dotnet/efcore/issues/13947) in the EF Core repo that could be a possible solution.

**Comment by VictorioBerra** [comment] 2021-11-13 15:50
@johnwc That is helpful info, I would like to say that you are providing an offset. An offset is not a time zone https://spin.atomicobject.com/2016/07/06/time-zones-offsets/

**Comment by johnwc** [comment] 2021-11-13 16:43
@VictorioBerra that is why I said time zone 'information'. As in, the offset comes from the time zone. Most of the time, when you're working with DateTimeOffset, you're working with time zone conversion. Always storing a date as UTC and then display it as a users local/preferred time zone. If you need to know what the original time zone was for the date, that's a hole different column to save. But... this is completely off topic of what we're talking about here in regards to DateTimeOffset.

That link reminds me of the grammer police... Everyone knows what the difference between a time zone and offset is, along with knowing a offset can derive from a time zone.

**Comment by crozone** [comment] 2021-11-15 00:52
> If the time zone is given, it will convert it to UTC. Where if it is not given, it assumes it is UTC.

This is inaccurate - if the timezone isn't given, it defaults to interpreting the given time in the timezone set in the current database connection context, which is set in the MySQL server configuration. There is no guarantee that this is UTC, on many MariaDB installs this is just the server host timezone. In order to know for sure what the connection timezone is, it either needs to be queried, or set with `SET time_zone = '+00:00'`.

Complicating things, the actual storage of the timezone differs depending on the column type. `TIMESTAMP` values are converted from their timezone into UTC upon storage, and converted back from UTC into the context timezone upon retrieval.  `DATETIME` (and other time types) columns are *not* converted, and are simply stored verbatim as if their timezone values were stripped.

Ref: https://dev.mysql.com/doc/refman/8.0/en/datetime.html

>MySQL converts TIMESTAMP values from the current time zone to UTC for storage, and back from UTC to the current time zone for retrieval. (This does not occur for other types such as DATETIME.) By default, the current time zone for each connection is the server's time. The time zone can be set on a per-connection basis. As long as the time zone setting remains constant, you get back the same value you store. If you store a TIMESTAMP value, and then change the time zone and retrieve the value, the retrieved value is different from the value you stored. This occurs because the same time zone was not used for conversion in both directions. 

This difference in behaviour obviously presents some complications for the ORM. If storing `DATETIME` columns in UTC is desired for interoperability, they must be manually converted into UTC by the ORM. However, if this conversion is done for `TIMESTAMP` columns, the result will be incorrect unless the context timezone is manually set to UTC, or the timestamp includes the +00:00 timezone. Additionally, if `CURRENT_TIMESTAMP` is used to generate server-side default values, the connection timezone must be aligned. This is a non-issue for `TIMESTAMP`, since the stored value will always be UTC, but with `DATETIME` the connection timezone must be the same as whatever Pomelo is converting the values to, or they'll be misaligned.

**Comment by johnwc** [comment] 2021-11-16 00:56
@crozone Sorry, I left out the important part about why it converts it to UTC for us. All of our MySQL server's have `default-time-zone='+00:00'` set in my.cnf.

**Comment by lauxjpn** [comment] 2021-11-16 16:57
A general way to preserve the time zone information is to use a [Value Converter](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions) like [DateTimeOffsetToBinaryConverter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.datetimeoffsettobinaryconverter?view=efcore-5.0) for `DateTimeOffset` properties:

```c#
myEntity.Property(e => e.MyDateTimeOffsetProperty)
    .HasConversion<long>(); // <-- implicitly uses DateTimeOffsetToBinaryConverter
```

They are represented in the database as a 64 bit value.
