### ISSUE TITLE
ef8 Method not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping

### ISSUE THREAD

**Issue by luffysamk** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1808] opened 2023-11-16 03:51 UTC
### Steps to reproduce
[Other details](https://stackoverflow.com/questions/77492063/ef-core-8-method-not-found-microsoft-entityframeworkcore-storage-relationaltyp)

### The issue
Method not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping 

```
Method not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.Clone(Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo ByRef)'.
      System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.Clone(Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingInfo ByRef)'.
         at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlTypeMappingSource.FindMapping(RelationalTypeMappingInfo& mappingInfo)
         at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.<>c.<FindMappingWithConversion>b__8_0(ValueTuple`4 k, RelationalTypeMappingSource self)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, Type providerClrType, ValueConverter customConverter)
         at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMappingWithConversion(RelationalTypeMappingInfo mappingInfo, IReadOnlyList`1 principals)
         at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSource.FindMapping(MemberInfo member)
         at Microsoft.EntityFrameworkCore.Metadata.Internal.MemberClassifier.IsCandidatePrimitiveProperty(MemberInfo memberInfo, IConventionModel model, CoreTypeMapping& typeMapping)
         at Microsoft.EntityFrameworkCore.Metadata.Conventions.PropertyDiscoveryConvention.Process(IConventionEntityTypeBuilder entityTypeBuilder)
         at Microsoft.EntityFrameworkCore.Metadata.Conventions.PropertyDiscoveryConvention.ProcessEntityTypeAdded(IConventionEntityTypeBuilder entityTypeBuilder, IConventionContext`1 context)
         at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(IConventionEntityTypeBuilder entityTypeBuilder)
         at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnEntityTypeAddedNode.Run(ConventionDispatcher dispatcher)
         at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.DelayedConventionScope.Run(ConventionDispatcher dispatcher)
         at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
         at Microsoft.EntityFrameworkCore.Metadata.Convention
```

### Further technical details

MySQL version: 8.0.20-11
Operating system: win 11  Insider Preview Feature Experience Pack 1000.25992.1000.0
Pomelo.EntityFrameworkCore.MySql version:8.0.0-beta.1
Microsoft.AspNetCore.App version:8.0

[Other details](https://stackoverflow.com/questions/77492063/ef-core-8-method-not-found-microsoft-entityframeworkcore-storage-relationaltyp)

**Comment by fschick** [comment] 2023-11-16 07:14
Can be reproduced by `dbContext.Database.GetPendingMigrationsAsync(cancellationToken)`

**Comment by dlerps** [comment] 2023-11-16 08:32
Same issue here when I try to add a new migration using the EF CLI:

```bash
dotnet ef migrations add \
    -p Data.DbMigration \
    -s Api \
    -c Data.Contexts.DataContext \
    --verbose \
    Init -- --environment Development
```

Stacktrace output and versions are identical to the ones mentioned above.

**Comment by InfinityBlocksUser** [comment] 2023-11-16 10:00
Same problem here trying to migrate to .net 8

**Comment by roji** [comment] 2023-11-16 12:50
Duplicate of #1746

**Comment by mumianhua2008** [comment] 2023-11-16 15:01
Perhaps there are bugs in version 8.0, using 7.0.14 instead

<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.14" />

**Comment by isential-gmbh** [comment] 2023-11-16 17:50
@mumianhua2008
Hey, we're migrating our projects to .NET 8 for the extended support, but now we're running into the same issue. Looks like we'll have to roll back to .NET 7 to use version 7.0.14.

**Comment by luffysamk** [comment] 2023-11-17 01:22
By Follow Mr Poul Bak's step,Here are two temporary solutions:
1.use 'Pomelo 8.0.0-beta.1'. But remove all that starts with: 'Microsoft.EntityFrameWorkCore'
`<ItemGroup>

<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.0-beta.1" />
</ItemGroup>
`

2. First remove/upgrade all 'preview' and 'rc1' packages. The thing is you don't need to explicitly reference those packages, they are included in .net 8. And then DOWNGRADE 'Pomelo.EntityFrameworkCore.MySql' to version 7.0

Method one works for my scenario, method two doesn't work for my scenario. 
It's weird. It may have something to do with the compiled version or environment

**Comment by luffysamk** [comment] 2023-11-17 01:25
Just waiting for the new version for .net 8

**Closed** 2023-11-17 01:24 UTC

**Comment by fschick** [comment] 2023-11-17 06:18
Commenting out 'Microsoft.EntityFrameWorkCore' isn't an option for multi-database applications.

**Comment by isential-gmbh** [comment] 2023-11-17 09:03
Before I give any of those suggested temporary fixes a shot, I'd rather wait for a shared and hopefully glitch-free solution for .NET 8. However, I need to know a timeframe to gauge if I can hold out until then. Otherwise, I might just have to take a step back to .NET 7. Any ballpark on when the version for .NET 8 is expected?

**Comment by fschick** [comment] 2023-11-17 09:07
Release plan: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1746#issuecomment-1814521680
