### ISSUE TITLE
Detecting Changes in table in order to detect when any changes

### ISSUE THREAD

**Issue by Vijaykumarj** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#617] opened 2018-06-22 07:08 UTC
Receive Notifications when a table record changes between an asp.net web application and an instance of mysql like **SQLDependency in SQL Server**. 

If our library is not support, let me know any other libraries are supported of this feature.

thanks in advance

**Comment by bgrainger** [comment] 2018-06-22 14:17
Duplicate of mysql-net/MySqlConnector#522.

**Comment by mguinness** [comment] 2018-06-22 16:37
Closing issue due to cross-posting.

**Closed by mguinness** 2018-06-22 16:37 UTC
