### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping`1' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by stephenhendry** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#354] opened 2017-08-15 13:59 UTC
### Steps to reproduce
`dotnet ef dbcontext scaffold "Server=localhost;User Id=root;Password=123456;Database=eftests" "Pomelo.EntityFrameworkCore.MySql"`
### The issue
The following error is given on a new Core 2 application.

```
Could not load type 'Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping`1' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
```

### Further technical details
This is a Core 2 application.

Pomelo.EntityFrameworkCore.MySql version: 2.0.0-preview3-10055

**Comment by erikbozic** [comment] 2017-08-15 15:09
This seems to be the same issue as: https://github.com/aspnet/EntityFramework/issues/9390 .
The problem is there have been some breaking changes in EF Core.
Good news is that a [PR](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/352) is already open. I'm guessing it will be merged soon.

**Closed** 2017-08-15 15:50 UTC
