### ISSUE TITLE
Updating from alpha.2 to any newer makes connection not closing

### ISSUE THREAD

**Issue by robertsabo0** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1439] opened 2021-06-04 10:47 UTC
We are using 5.0.0-alpha.2 version for a months. And everyting works well.
Connection polling works as expected.

Tried to update to latest 5.0.0. On application startup there are lot of initialization which runs parallel and calls database.
After update, we are getting crash with exception:

```
MySqlConnector.MySqlException (0x80004005): Connect Timeout expired. All pooled connections are in use.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 139
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 892
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 892
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 435
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 380
   at Microsoft.EntityFrameworkCore.ServerVersion.AutoDetect(String connectionString)
   at PersistenceEF.DBModel.chooseProperDatabase[T](DbContextOptionsBuilder`1 optionsBuilder, ConnectionStringSettings dbConn, Boolean& isInMemory) in E:\Projects\inViewWebScada\IwsServer\PersistenceCore\IwsPersistanceCore.Repository\DBModels\DBModel.cs:line 56
   at PersistenceEF.DBModel.createByName(String name, Boolean allowCreating, Boolean isDataTransfer) in E:\Projects\inViewWebScada\IwsServer\PersistenceCore\IwsPersistanceCore.Repository\DBModels\DBModel.cs:line 32
   at PersistenceEF.DBModel.createByName(String name) in E:\Projects\inViewWebScada\IwsServer\PersistenceCore\IwsPersistanceCore.Repository\DBModels\DBModel.cs:line 27
   at PersistenceEF.UnitOfWork.InstanceDBModel(String connName) in E:\Projects\inViewWebScada\IwsServer\PersistenceCore\IwsPersistanceCore.Repository\UnitOfWorks\UnitOfWork.cs:line 175
   at PersistenceEF.UnitOfWork.<>c.<.ctor>b__16_0(String t) in E:\Projects\inViewWebScada\IwsServer\PersistenceCore\IwsPersistanceCore.Repository\UnitOfWorks\UnitOfWork.cs:line 69
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at PersistenceEF.UnitOfWork..ctor(List`1 connectionName, Boolean isForced) in E:\Projects\inViewWebScada\IwsServer\PersistenceCore\IwsPersistanceCore.Repository\UnitOfWorks\UnitOfWork.cs:line 69
   at PersistenceEF.UnitOfWork..ctor(String connectionName) in E:\Projects\inViewWebScada\IwsServer\PersistenceCore\IwsPersistanceCore.Repository\UnitOfWorks\UnitOfWork.cs:line 48
```

While monitoring processlist  on mysql server, looks like every query opens connection and do not close it. While, on previous version looks like it reuse connections.

MySQL version: MariaDB 10.5.9 with Galera cluster
Operating system: windows10, docker mcr.microsoft.com/dotnet/runtime
Pomelo.EntityFrameworkCore.MySql version: 5.0.0
.NET version: 3.1

**Comment by robertsabo0** [comment] 2021-06-04 10:48
Also, tried with version beta.1 and beta.2, problem is present same as 5.0.0.

**Comment by lauxjpn** [comment] 2021-06-04 11:40
It is likely either an application code error, or an unexpectedly high load (e.g. web requests) that exceeds what MariaDB is configured for, but let's investigate this a bit more (it is not entirely impossible, that it is a bug in MySqlConnector or Pomelo, but unlikely):

Lets start with a couple of simple steps/questions, so we get a better picture of the issue:
* What version of MySqlConnector are you using?
* After trying Pomelo 5.0.0 (and the betas), did you retry `5.0.0-alpha.2`? If so, does it still work?
* How are you registering your `DbContext` (paste us some code)?
* How does your connection string looks like (remove sensitive information before pasting)?
* Is the exception thrown immediately during initialization, or later while the app has already been running for some time (if the latter, how long does it take until the exception is being thrown)?
* What is the output of a `SHOW PROCESSLIST` query?
* Has the server/cluster been restarted between tries?

**Comment by robertsabo0** [comment] 2021-06-04 12:03
> * What version of MySqlConnector are you using?
We do not have any specific MySqlConnector added. Only mentioned PomeloEntityFramework installed as Nuget package.

> * After trying Pomelo 5.0.0 (and the betas), did you retry `5.0.0-alpha.2`? If so, does it still work?
Yes, I tried again to set version back to '5.0.0-alpha.2' with other EF libs updated to 5.0.6. And everything works well

> * How are you registering your `DbContext` (paste us some code)?
We are using Repository design pattern.
We have Disposable UnitOfWork which in constructor creates manualy

Creating DbContext looks like this:
`var optionsBuilder = new DbContextOptionsBuilder<DBModel>();
optionsBuilder.UseMySql(dbConn.ConnectionString, ServerVersion.AutoDetect(dbConn.ConnectionString), t => t.EnableRetryOnFailure());
model = new DBModel(optionsBuilder.Options, name, dbConn.ProviderName);`

In Dispose method of UnitOfWork we call `context.Dispose()`

> * How does your connection string looks like (remove sensitive information before pasting)?
Connection string is something like this. 

` Server=ip;Port=3306;Database=dbname;Uid=username;Pwd=****;Pooling=true;Max Pool Size=50;Command Timeout=600`

Also tried with default behaviour and connection string like this:

` Server=ip;Port=3306;Database=dbname;Uid=username;Pwd=****;Command Timeout=600`

> * Is the exception thrown immediately during initialization, or later while the app has already been running for some time (if the latter, how long does it take until the exception is being thrown)?

Exception is thrown while initializing. Initialization is not an fast action.
For me, it's looks like about 30-40s after starting application. Looks like connection timeout happends while waiting some free connection.

> * What is the output of a `SHOW PROCESSLIST` query, when the exceptions are already occurring?
Number of rows in processlist reach limit of max pool size (50 if limited, and 100 if no limit written in connection string)

There are a lot of rows like this one:

`
# ID, USER, HOST, DB, COMMAND, TIME, STATE, INFO, TIME_MS, STAGE, MAX_STAGE, PROGRESS, MEMORY_USED, MAX_MEMORY_USED, EXAMINED_ROWS, QUERY_ID, INFO_BINARY, TID
'619856', 'DB NAME', 'IP ADDRESS:9156', NULL, 'Sleep', '24', '', NULL, '24175.035', '0', '0', '0.000', '81384', '81384', '0', '51398106', ?, '9352'
`
> * Has the server/cluster been restarted between tries?
No, there was no restart between tries. And it do not looks like it's needed because getting back older version works well.
> * Are you using the same connection string, or multiple (possibly changing) connection strings?
Both connection string we tried are written on previous question.
> * Assuming this is a web application, is the app running on a single server, or on multiple servers (how many?) or serverless (e.g. AWS Lambda)?
It's microservice arhitecture. We are debuging only one microservise on which we tried to update pomelo lib

**Comment by lauxjpn** [comment] 2021-06-04 12:19
> It's microservice arhitecture. We are debuging only one microservise on which we tried to update pomelo lib

What does this mean? Does it mean there is only 1 web server that is running the 5.0.0 app, or are there more than 1 web server (e.g. a web server cluster, container swarm etc.) running the 5.0.0 app?

> There are a lot of rows like this one: [...]

* How many?
* Are the IP addresses all the same, or do they differ?
* What is the connection string used in all non-updated (still `5.0.0-alpha.2` using) microservices?

---

There are a couple more questions in my original post.

---

A couple more questions:
* What is the output of a `SELECT @@max_connections, @@max_user_connections;` query?
* Is your UnitOfWork class registered using DI? If so, is it scoped?
* What is the output difference of the `SHOW PROCESSLIST;` query, when running it before initialization, immediately after initialization and later when the exceptions occur?

---

After this, we can probably do some probing/testing.

**Comment by robertsabo0** [comment] 2021-06-04 12:33
There are 8 microservices and everyone communication with database. All of them uses 5.0.0-alpha.2 version. And everyting works well in production. Now, out of production, but on same MySqlServer we are trying to update Pomelo.EFCore.

Max connections on MariaDB server is configured to 500. Max pool size is 50 on each microservice.
So if everyone would use all connection, we could not reach max connections on server.

Output for `SELECT @@max_connections, @@max_user_connections, @@wait_timeout;` is following:
`@@max_connections, @@max_user_connections, @@wait_timeout

'500', '0', '28800'`

No, UnitOfWork has been initialized on request manually. In all uses in code we have `using` block that guarantee us to call dispose after usage.


About proccesslist output, I do not show you all lines, I filter only ones that are assigned to our test. There are other lines, but I'm interested only lines with IP address that shows connection is from this test case.

Before testing, `show proccesslist` is 1 row (it's I guess MySqlWorkbench).
When I run a test and we get the point of failure, it shows MaxPoolSize + 1 (so 51 or 101 lines depends on connectionstring)

No, there are no dynamically added.

**Comment by lauxjpn** [comment] 2021-06-04 12:50
> About proccesslist output, I do not show you all lines, I filter only ones that are assigned to our test. There are other lines, but I'm interested only lines with IP address that shows connection is from this test case.
> 
> Before testing, show proccesslist is 1 row (it's I guess MySqlWorkbench).
> When I run a test and we get the point of failure, it shows MaxPoolSize + 1 (so 51 or 101 lines depends on connectionstring)

How many entries are there over all (the count of _all_ connections, not just the one from this particular test):
```sql
SELECT count(*) FROM INFORMATION_SCHEMA.PROCESSLIST;
```

Also, how many have been sleeping for a long time:

```sql
SELECT count(*) FROM INFORMATION_SCHEMA.PROCESSLIST WHERE TIME_MS > 500.0;
```

**Comment by robertsabo0** [comment] 2021-06-04 12:58
Okey, running these 2 queries before running test has results:
Total count: 127
Sleep long time: 108

When I run test and get error these 2 queries shows:
Total count: 234
Sleep long time: 214

After stopping test, query again shows similar numbers as first one.

**Comment by lauxjpn** [comment] 2021-06-04 13:06
Okay, so you are not hitting the `max_connections` limit.

Next, disable connection pooling for the 5.0.0 app with the additional connection string option `Pooling=false`.
Do the exceptions still occur?

**Comment by robertsabo0** [comment] 2021-06-04 13:13
Last test was with default (100).

Now I have tried with disabling pooling.
And no, there is no exception. Looks like connections are closing when `Pooling=false` 
Also, number of active connection was less then 20 in every execution of `proccesslist` (filtered to connection form test only).

Totals was as this:
Total count: 160
Sleep long time: 130

But, disable pooling is not solution for this problem. We need to limit number of connections per microservice.

**Comment by lauxjpn** [comment] 2021-06-04 13:30
> Now I have tried with disabling pooling.
> And no, there is no exception. Looks like connections are closing when `Pooling=false`

That is correct, there is no blocking with `Pooling=false`, when you reach `MaxPoolSize` active connections.
From https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1322#issuecomment-776756842:

> If `MaxPoolSize=90` (and `Pooling=True`), and all 90 connections are in active use, then `MySqlConnector.Open(Async)` will block for up to `ConnectTimeout` seconds waiting for a connection to be closed (and returned to the pool). If this doesn't happen, a `MySqlException` (with `MySqlErrorCode.UnableToConnectToHost`) will be thrown.

And from [MySQL .NET Connection String Options](https://mysqlconnector.net/connection-options/):

> Name | Default | Description
> -- | -- | --
> Pooling | true | Enables connection pooling. When pooling is enabled, `MySqlConnection.Open`/`OpenAsync` retrieves an open connection from the pool if one is available, and `Close`/`Dispose`/`DisposeAsync` returns the open connection to the pool. If there are no available connections in the pool, and the pool hasn’t reached `MaximumPoolSize` connections, a new connection will be opened; otherwise, the call to `Open`/`OpenAsync` blocks until a connection becomes available or `ConnectionTimeout` is reached.

Is your app using more than 50 connections at the same time (and using the same connection string)?

**Comment by robertsabo0** [comment] 2021-06-07 07:32
Looks like but is present in MySqlConnector 1.3.7

I tried to manually add MySqlConnector dependency to latest version (1.3.9) and everything works well.
______________
On the other side, with updated MySqlConnector I was able to reproduce the problem by setting `MaxPoolSize=10 ` (only test purpose). By added `DeferConnectionReset=true`, no exception with `MaxPoolSize=10`.
______________

To summerize: 
My problem fix was : 

1. Add manualy nuget dependency MySqlConnector version 1.3.9  
2. Add `DeferConnectionReset=true` to connection string.

Thanks you so much

**Comment by lauxjpn** [comment] 2021-06-07 10:45
@bgrainger Seems to be unexpected, that the connection leaks if `DeferConnectionReset=true` is not applied. Do you want me to verify this first, or do you want to take over?

**Comment by bgrainger** [comment] 2021-06-07 14:05
It is quite possibly this bug (https://github.com/mysql-net/MySqlConnector/pull/982) if it's broken in 1.3.7 but fixed in 1.3.9.

**Comment by bgrainger** [comment] 2021-06-07 14:07
> Seems to be unexpected, that the connection leaks if `DeferConnectionReset=true` is not applied.

It's possibly a deadlock of some kind, rather than connections being leaked, per se. I can take it as an item to investigate.

**Comment by bgrainger** [comment] 2021-06-16 15:20
I've changed the default for `DeferConnectionReset` to `true` in [1.3.10](https://github.com/mysql-net/MySqlConnector/releases/tag/1.3.10).

There have been a handful of bug reports about connection pool exhaustion that makes me suspect this setting isn't ready for primetime without some more rigorous testing.

**Comment by lauxjpn** [comment] 2021-06-17 06:47
@bgrainger Thanks! BTW, while I did not spend too much time on it, I was not able to reproduce this issue.

**Comment by lauxjpn** [comment] 2021-06-29 19:15
> I've changed the default for `DeferConnectionReset` to `true` in [1.3.10](https://github.com/mysql-net/MySqlConnector/releases/tag/1.3.10).

Since we have `5.0.1` out, and it is using MySqlConnector `1.3.10`, we are closing this one here for now.

**Closed by lauxjpn** 2021-06-29 19:15 UTC
Labels: external, type-bug
