### ISSUE TITLE
Can not convert Char 36 to string

### ISSUE THREAD

**Issue by phanhuudinh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#783] opened 2019-05-07 01:18 UTC
### Steps to reproduce
I use db first to generate dbcontext from existed db
one of fields in my table user char(36) type, but it is not the `Guid` type, just a `string`, like this:
```c#
   // from my dbcontext config
   modelBuilder.Entity<SampleTable>(entity =>
   {
      //...
      entity.Property(e => e.RefCode).HasColumnType("char(36)");
      //...
   }
```
```
    // my table entity class
    public class SampleTable
    {
        //...
        public string RefCode { get; set; }
        //...
    }
```
Everything still work when I use it to add new row with a string value on this field

### The issue
But when I read data back from db it always throw error

```
Exception message:
FormatException: One of the identified items was in an invalid format.
MySqlConnector.Core.TextRow.GetValueCore(ReadOnlySpan<byte> data, ColumnDefinitionPayload columnDefinition) in TextRow.cs, line 63
```

It also happen when convert from `tinyint(1) unsigned` to `int` or to `Enum`
### Further technical details

MySQL version: 
8.0
Operating system: windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 2.2.0

Other details about my project setup:

**Comment by mguinness** [comment] 2019-05-07 04:35
Possible dupe of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/722.

**Comment by lauxjpn** [comment] 2019-11-01 11:29
With #904 this should be fixed. You can use the connection string option `GuidFormat` to explicitly set the type that is being used to convert a `System.Guid`  to and from (including `MySqlGuidFormat.None`).

**Closed** 2019-11-03 15:15 UTC
Labels: type-bug
