### ISSUE TITLE
Creating migration without connection to database doesn't work

### ISSUE THREAD

**Issue by erwinwildenburg** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#330] opened 2017-07-22 05:07 UTC
### Steps to reproduce
For SqlServer I use the following code:
```
    public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public readonly ApplicationDbContextSettings Options;

        public ApplicationDbContextFactory() { }

        public ApplicationDbContextFactory(IOptions<ApplicationDbContextSettings> options)
        {
            Options = options.Value;
        }

        public ApplicationDbContext CreateDbContext(string[] args)
        {
            DbContextOptionsBuilder<ApplicationDbContext> optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            
            string connectionString = Options?.DefaultConnection;
            optionsBuilder.UseSqlServer(connectionString ?? "Empty");

            return new ApplicationDbContext(optionsBuilder.Options);
        }
    }
```

For MySQL I use the following:
```
    public class ApplicationDbContextFactory : IDesignTimeDbContextFactory<ApplicationDbContext>
    {
        public readonly ApplicationDbContextSettings Options;

        public ApplicationDbContextFactory() { }

        public ApplicationDbContextFactory(IOptions<ApplicationDbContextSettings> options)
        {
            Options = options.Value;
        }

        public ApplicationDbContext CreateDbContext(string[] args)
        {
            DbContextOptionsBuilder<ApplicationDbContext> optionsBuilder = new DbContextOptionsBuilder<ApplicationDbContext>();
            
            string connectionString = Options?.DefaultConnection;
            optionsBuilder.UseMySql(connectionString);

            return new ApplicationDbContext(optionsBuilder.Options);
        }
    }
```

### The issue
The SqlServer version allows me to create a migration without connection to the database.
Running dotnet ef migrations add InitialCreate will give an empty connectionString and allows to create a migration.

When running the same command with the Pomelo MySQL provider I get an error that the connectionString isn't right.
The connectionString will be null in this situation.

Using "Empty" like with the SqlServer version will return an error also.

```
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer,
 Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hash
table synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql(DbContextOptionsBuilder optionsBuilder, String connec
tionString, Action`1 mySqlOptionsAction)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql[TContext](DbContextOptionsBuilder`1 optionsBuilder, S
tring connectionString, Action`1 mySqlOptionsAction)
   at API.Models.ApplicationDbContextFactory.CreateDbContext(String[] args) in C:\Source\PowerShell-DSC-Cloud\src\API\Models\Appli
cationDbContext.cs:line 109
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_0.<FindContextTypes>b__3()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contex
tType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Format of the initialization string does not conform to specification starting at index 0.
```
```
System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql(DbContextOptionsBuilder optionsBuilder, String connec
tionString, Action`1 mySqlOptionsAction)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql[TContext](DbContextOptionsBuilder`1 optionsBuilder, S
tring connectionString, Action`1 mySqlOptionsAction)
   at API.Models.ApplicationDbContextFactory.CreateDbContext(String[] args) in C:\Source\PowerShell-DSC-Cloud\src\API\Models\Appli
cationDbContext.cs:line 109
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_0.<FindContextTypes>b__3()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contex
tType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null.
Parameter name: connectionString
```

### Further technical details

MySQL version: N/A
Operating system: Windows 10 x64
Pomelo.EntityFrameworkCore.MySql version: 2.0.0-preview2-10046

Other details about my project setup:

**Comment by caleblloyd** [comment] 2017-07-22 05:31
Duplicate of #272

**Closed by caleblloyd** 2017-07-22 05:31 UTC
