### ISSUE TITLE
GroupBy inside Select produces wrong SQL

### ISSUE THREAD

**Issue by orjandh** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1678] opened 2022-06-27 13:22 UTC
### Steps to reproduce
Create a query with a `GroupBy` on a navigational property inside a select statement.

```C#
await db.sessions
    .Include(s => s.answers)
    .Select(s => s.answers.GroupBy(a => a.identifier).Count())
    .ToListAsync();
```

<details>
  <summary>Program.cs</summary>

```C#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class Session
    {
        public int id { get; set; }
        public DateTime date { get; set; }
        public IEnumerable<Answer> answers { get; set; }
    }

    public class Answer
    {
        public int id { get; set; }
        public string identifier { get; set; }
        public int sessionId { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Session> sessions { get; set; }
        public DbSet<Answer> answers { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1678";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(connectionString, serverVersion)
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
            //optionsBuilder.UseInMemoryDatabase("Issue1678");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Session>(
                entity =>
                {
                    entity.HasData(
                        new Session
                        {
                            id = 1,
                            date = DateTime.Now
                        });
                });

            modelBuilder.Entity<Answer>(
                entity =>
                {
                    entity.HasData(
                        new Answer
                        {
                            id = 1,
                            sessionId = 1,
                            identifier = "test"
                        });
                });
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();

            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var result = context.sessions
                .Include(s => s.answers)
                .Select(s => s.answers.GroupBy(a => a.identifier).Count())
                .ToList();

            Console.WriteLine(string.Join(",", result));
        }
    }
}
```
</details>

### The issue

A query like the one above produces the following SQL. I believe the problem is that the alias 's' is not available and the inner clause is missing a JOIN statement.

```SQL
SELECT (
    SELECT COUNT(*)
    FROM (
        SELECT `a`.`identifier`
        FROM `answers` AS `a`
        WHERE `s`.`id` = `a`.`sessionId`
        GROUP BY `a`.`identifier`
    ) AS `t`
)
FROM `sessions` AS `s`
```

The exception details are as follows.

`An exception occurred while iterating over the results of a query for context type 'IssueConsoleTemplate.Context'.`

```
MySqlConnector.MySqlException (0x80004005): Unknown column 's.id' in 'where clause'
  at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
  at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 127
  at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 456
  at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
  at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 330
  at MySqlConnector.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in /_/src/MySqlConnector/MySqlCommand.cs:line 272
  at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
  at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
  at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
  at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
```

### Further technical details

MySQL version: 5.7.36
Operating system: Windows 11
Pomelo.EntityFrameworkCore.MySql version: 6.0.1
Microsoft.AspNetCore.App version: 6.0.6

**Comment by orjandh** [comment] 2022-06-28 07:41
Thank you. The issue has been updated with a minimal reproducible program.

**Comment by mguinness** [comment] 2022-06-28 17:11
Thanks for the example.  I also ran it using the SQL Server provider and get the same result, see this [.NET Fiddle](https://dotnetfiddle.net/cjCoi0).

@smitpatel Any pointers?

**Comment by smitpatel** [comment] 2022-06-28 17:15
From T-SQL perspective it is valid SQL. You can use any of the top level aliases from table inside any level nesting in the projection subqueries. So this could be just database specific limitations in terms of generated SQL.
Do you have any alternate translation for the LINQ query?

**Comment by mguinness** [comment] 2022-06-28 18:19
It looks like MySQL added support in 8.0.14, see [Supporting all kinds of outer references in derived tables](https://dev.mysql.com/blog-archive/supporting-all-kinds-of-outer-references-in-derived-tables-lateral-or-not/).  For earlier versions the generated SQL will need to be changed.

**Comment by meriturva** [comment] 2024-04-16 13:33
Hi to all,
any news here? do we have to wait for LATERAL support from MariaDB https://jira.mariadb.org/browse/MDEV-6373 ?

Thanks!

**Comment by lauxjpn** [comment] 2024-04-16 14:28
@meriturva If you write the query like the one in the OP, then for the query to work, there needs to be support for inner queries referencing outer queries in the database server implementation.

The LINQ query in the OP could be written in a different manner though, so that there is no need for the inner query to reference the outer one.

**Comment by meriturva** [comment] 2024-04-16 16:52
@lauxjpn Yes I mean the one in the original post. Rewriting queries to overcome this database limitation produces not-so-maintainable code.

Already done few times and it makes me so sad!

**Comment by lauxjpn** [comment] 2024-04-22 09:24
In case anyone is wondering, how to rewrite the query in a way that does not need a reference to an outer query, here is the rewritten LINQ query from the OP:

```csharp
var numberOfDistinctIdentifiersPerSession = context.answers
    .Select(a => new { a.sessionId, a.identifier })
    .Distinct()
    .GroupBy(t => t.sessionId)
    .Select(g => new { sessionId = g.Key, count = g.Count() });

var numberOfDistinctIdentifiersPerSessionWithoutSessions = numberOfDistinctIdentifiersPerSession
    .Select(t => t.Count)
    .ToList();
```

Which would then be translated to the following SQL:

```sql
SELECT COUNT(*)
FROM (
    SELECT DISTINCT `a`.`sessionId`, `a`.`identifier`
    FROM `answers` AS `a`
) AS `t`
GROUP BY `t`.`sessionId`
```

Or as a sample console app:

<details>
<summary>Program.cs</summary>

```csharp
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate;

public class Session
{
    public int SessionId { get; set; }
    public IEnumerable<Answer> Answers { get; set; }
}

public class Answer
{
    public int AnswerId { get; set; }
    public string GroupName { get; set; }
    public int SessionId { get; set; }
}

public class Context : DbContext
{
    public DbSet<Session> Sessions { get; set; }
    public DbSet<Answer> Answers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;Database=Issue1678";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(connectionString, serverVersion)
                .LogTo(Console.WriteLine, LogLevel.Information)
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Session>(
            entity =>
            {
                entity.HasData(
                    new Session { SessionId = 1 },
                    new Session { SessionId = 2 });
            });

        modelBuilder.Entity<Answer>(
            entity =>
            {
                // Session 1 has 2 distinct groups.
                // Session 2 has 1 distinct group.
                entity.HasData(
                    new Answer { AnswerId = 1, SessionId = 1, GroupName = "GroupA" },
                    new Answer { AnswerId = 2, SessionId = 1, GroupName = "GroupA" },
                    new Answer { AnswerId = 3, SessionId = 1, GroupName = "GroupB" },
                    new Answer { AnswerId = 4, SessionId = 2, GroupName = "GroupA" },
                    new Answer { AnswerId = 5, SessionId = 2, GroupName = "GroupA" });
            });
    }
}

internal static class Program
{
    private static void Main()
    {
        using var context = new Context();
        
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        // var numberOfDistinctGroupNamesPerSession = context.Sessions
        //     .Include(s => s.Answers)
        //     .Select(s => s.Answers.GroupBy(a => a.GroupName).Count())
        //     .ToList();

        var numberOfDistinctGroupNamesPerSession = context.Answers
            .Select(a => new { a.SessionId, a.GroupName })
            .Distinct()
            .GroupBy(t => t.SessionId)
            .Select(g => new { SessionId = g.Key, Count = g.Count() });
        
        var numberOfDistinctGroupNamesPerSessionWithoutSessions = numberOfDistinctGroupNamesPerSession
            .Select(t => t.Count)
            .ToList();

        // Ensure deterministic order for asserts.
        numberOfDistinctGroupNamesPerSessionWithoutSessions = numberOfDistinctGroupNamesPerSessionWithoutSessions
            .OrderDescending()
            .ToList();
        
        Trace.Assert(numberOfDistinctGroupNamesPerSessionWithoutSessions.Count == 2);
        Trace.Assert(numberOfDistinctGroupNamesPerSessionWithoutSessions[0] == 2);
        Trace.Assert(numberOfDistinctGroupNamesPerSessionWithoutSessions[1] == 1);
    }
}
```

</details>

<details>
<summary>Output (SQL)</summary>

```sql
warn: 22.04.2024 11:20:05.353 CoreEventId.SensitiveDataLoggingEnabledWarning[10400] (Microsoft.EntityFrameworkCore.Infrastructure) 
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data; this mode should only be enabled during development.
info: 22.04.2024 11:20:05.836 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (24ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                
      DROP DATABASE `Issue1678`;                                                                                        
info: 22.04.2024 11:20:06.094 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                 
      CREATE DATABASE `Issue1678`;                                                                                      
info: 22.04.2024 11:20:06.305 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                 
      ALTER DATABASE CHARACTER SET utf8mb4;                                                                             
info: 22.04.2024 11:20:06.317 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (11ms) [Parameters=[], CommandType='Text', CommandTimeout='30']                                
      CREATE TABLE `Sessions` (                                                                                         
          `SessionId` int NOT NULL AUTO_INCREMENT,                                                                      
          CONSTRAINT `PK_Sessions` PRIMARY KEY (`SessionId`)
      ) CHARACTER SET=utf8mb4;
info: 22.04.2024 11:20:06.332 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (14ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `Answers` (
          `AnswerId` int NOT NULL AUTO_INCREMENT,
          `GroupName` longtext CHARACTER SET utf8mb4 NULL,
          `SessionId` int NOT NULL,
          CONSTRAINT `PK_Answers` PRIMARY KEY (`AnswerId`),
          CONSTRAINT `FK_Answers_Sessions_SessionId` FOREIGN KEY (`SessionId`) REFERENCES `Sessions` (`SessionId`) ON DELETE CASCADE
      ) CHARACTER SET=utf8mb4;
info: 22.04.2024 11:20:06.336 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command)
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Sessions` (`SessionId`)
      VALUES (1),
      (2);
info: 22.04.2024 11:20:06.339 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Answers` (`AnswerId`, `GroupName`, `SessionId`)
      VALUES (1, 'GroupA', 1),
      (2, 'GroupA', 1),
      (3, 'GroupB', 1),
      (4, 'GroupA', 2),
      (5, 'GroupA', 2);
info: 22.04.2024 11:20:06.364 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (24ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE INDEX `IX_Answers_SessionId` ON `Answers` (`SessionId`);
info: 22.04.2024 11:20:06.691 RelationalEventId.CommandExecuted[20101] (Microsoft.EntityFrameworkCore.Database.Command) 
      Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*)
      FROM (
          SELECT DISTINCT `a`.`SessionId`, `a`.`GroupName`
          FROM `Answers` AS `a`
      ) AS `t`
      GROUP BY `t`.`SessionId`
```

</details>

**Comment by lauxjpn** [comment] 2024-04-22 09:28
Since this is still expected behavior for MariaDB at the moment, we will close this issue.

**Closed by lauxjpn** 2024-04-22 09:28 UTC
Labels: closed-question, type-question
