### ISSUE TITLE
"Cannot Open when State is Connecting." with  AddDbContextPool.

### ISSUE THREAD

**Issue by vaital3000** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1577] opened 2021-12-03 07:42 UTC
### Steps to reproduce
I faced problem on production. I can't reproduce this problem in simple example.
Also not all requests failed with this problem. 
Problem reproduced only with `AddDbContextPool()`. With `AddDbContext()` all are fine.

### The issue
In this case I add new entity using `AddAsync()` and then I call `SaveChangesAsync()`
I fixed problem using `AddDbContext()`.

```
Cannot Open when State is Connecting.
at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 445
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Dodo.Accounting.EfRepository.Repositories.MaterialConsumption.OrderRepository.CreateAsync(Order order, CancellationToken ct) in /home/runner/work/accounting/accounting/src/Dodo.Accounting.EfRepository/Repositories/MaterialConsumption/OrderRepository.cs:line 52
```

### Further technical details

MySQL version: 5.7.28
Operating system: Linux (docker mcr.microsoft.com/dotnet/aspnet:6.0)
Pomelo.EntityFrameworkCore.MySql version: 6.0.0
Microsoft.AspNetCore.App version: 6

**Comment by vaital3000** [comment] 2021-12-03 07:43
Also @kinglionsoft mentioned this problem here https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/85

**Comment by mguinness** [comment] 2021-12-03 16:15
This exception is thrown the underlying [MySqlConnector](https://github.com/mysql-net/MySqlConnector/blob/e82f18f754323177cc27af3bc2157608b34be035/src/MySqlConnector/MySqlConnection.cs#L388) library.

@bgrainger Do you have any insights or suggestions?  Would a retry policy be appropriate?

**Comment by bgrainger** [comment] 2021-12-03 17:06
This is an "API misuse" exception. The most likely cause would be `Open(Async)` called reentrantly (which I don't see in the call stack), or `Open(Async)` being called twice (simultaneously) on the same `MySqlConnection` object.

Does "Problem reproduced only with AddDbContextPool(). With AddDbContext() all are fine." provide a clue to whether the same `MySqlConnection` might be used twice?

**Comment by jxlarrea** [comment] 2021-12-04 01:14
Experiencing exactly the same issue. After migrating to Pomelo.Mysql 6 and  .NET 6. When using AddDbContextPool() in an ASP.NET 6 web application, after a few minutes most requests throw System.InvalidOperationException: Cannot Open when State is Connecting.

`{"Category":"Web.Middleware.ErrorHandlerMiddleware", "EventId":0, "LogLevel":"Error", 
System.InvalidOperationException: Cannot Open when State is Connecting.
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 445
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at ITSD.Services.CacheService.GetServiceStatus(String serviceId, CancellationToken cancellationToken) in /app/ITSD/Caching/CacheService.cs:line 1081
   at ITSD.Web.Controllers.ProblemsController.Map(String shortname, CancellationToken cancellationToken) in /app/ITSD.Web/Controllers/ProblemsController.cs:line 1099
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at ITSD.Web.Middleware.CustomHeadersMiddleware.Invoke(HttpContext httpContext) in /app/ITSD.Web/Middleware/CustomHeadersMiddleware.cs:line 40
   at ITSD.Web.Middleware.ErrorHandlerMiddleware.Invoke(HttpContext context) in /app/ITSD.Web/Middleware/ErrorHandlerMiddleware.cs:line 65", "State":{…}}`

**Comment by bgrainger** [comment] 2021-12-04 19:16
> after migrating to Pomelo.EntityFrameworkCore.MySql 6 / EFCore 6 and .NET 6

Besides updating Pomelo itself, this updated .NET 5 to 6, MySqlConnector 1.3.x to 2.0, and EF Core from 5 to 6. It's possible a regression or incompatibility was introduced in any of these components.

Is there a minimal repro that would help track this down?

**Comment by jxlarrea** [comment] 2021-12-04 19:32
@bgrainger I am not really sure how to create a simple console test app to replicate the issue since it doesn't happen immediately but after several (~100) ASP.NET requests.  It is consistent though, as it always happens in Production given the high throughput of the web app.

Any ideas on how to synthetize that behavior within a simple console app to replicate the issue?

**Comment by vaital3000** [comment] 2021-12-05 09:33
```cs
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

var builder = WebApplication.CreateBuilder(args);
builder.Services.AddDbContextPool<MyDbContext>(opt =>
	opt.UseMySql(
		"Server=localhost;Port=3306;Database=test;Uid=root;SSL Mode=None;Allow User Variables=True",
		new MySqlServerVersion(new Version(5, 7, 28)))
);
builder.Services.AddHostedService<MyHostedService>();
var app = builder.Build();

app.Run();


public class MyHostedService : IHostedService
{
	private readonly IServiceScopeFactory _scopeFactory;
	private readonly ILogger<MyHostedService> _logger;


	public MyHostedService(IServiceScopeFactory scopeFactory, ILogger<MyHostedService> logger)
	{
		_scopeFactory = scopeFactory;
		_logger = logger;
	}

	public async Task StartAsync(CancellationToken _)
	{
		CancellationTokenSource cts = new();
		CancellationToken cancellationToken = cts.Token;

		using var startScope = _scopeFactory.CreateScope();
		var startContext = startScope.ServiceProvider.GetService<MyDbContext>();
		await startContext.Database.EnsureDeletedAsync(cancellationToken);
		await startContext.Database.EnsureCreatedAsync(cancellationToken);
		var task =  Task.Run(AddTask(cancellationToken), cancellationToken);

		await Task.Delay(2000, cancellationToken);
		_logger.LogWarning("Cancel task!!!");
		cts.Cancel();
		await task;
	}

	private Func<Task?> AddTask(CancellationToken cancellationToken)
	{
		return async () =>
		{
			while (true)
			{
				try
				{
					await Task.Delay(1000);
					using var scope = _scopeFactory.CreateScope();
					var context = scope.ServiceProvider.GetService<MyDbContext>();
					await context.Entities.AddAsync(new MyDbContext.MyEntity()
					{
						SomeText = Guid.NewGuid().ToString()
					}, cancellationToken);
					await context.SaveChangesAsync(cancellationToken);
				}
				catch (Exception e)
				{
					_logger.LogError(e.ToString());
				}
			}
		};
	}

	public Task StopAsync(CancellationToken cancellationToken)
	{
		return Task.CompletedTask;
	}
}

public class MyDbContext : DbContext
{
	public MyDbContext(DbContextOptions<MyDbContext> options)
		: base(options)
	{
	}

	public DbSet<MyEntity> Entities { get; set; }

	public sealed class MyEntity
	{
		public int Id { get; set; }
		public string SomeText { get; set; }
	}
}

```

I reproduced this error in this case. Errors happened after calling cts.Cancel().
But I'm not sure what this is the same case that I see in production.

CancellationToken wasn't cancelled in production.
![image](https://user-images.githubusercontent.com/15158048/144741202-f8a03cf0-906b-47b3-b718-5a018e1ce20f.png)

**Comment by vaital3000** [comment] 2021-12-05 09:54
Same example for .net 5 with ef core 5 has another error: "System.OperationCanceledException: The operation was canceled."

Also, when I added "Pooling=false;" into the connection string I saw "The operation was canceled."  exception.

That is target error reproduced only with enabled pool in Ef and MySqlConnector.

**Comment by jxlarrea** [comment] 2021-12-05 16:07
Seems like @vaital3000 found what's causing the issue. It seems like when passing a CancellationToken to DbContext operations and cancelling it (pretty common in ASP.NET Core) causes the contexts in the DbContextPool to get messed up for future uses.

@bgrainger [Here is a repo](https://github.com/jxlarrea/DbContextPoolTest) that reproduces the issue consistently. It kind of replicated a high throughput ASP.NET 6 web app. The moment that a CancellationToken is cancelled, `Cannot Open when State is Connecting.` starts being thrown in subsequent contexts uses.

Hope this helps.

**Comment by bgrainger** [comment] 2021-12-05 22:40
@vaital3000 Thanks for the repro; this is very helpful. The problem is that MySqlConnection isn't setting the state to `Closed` here: https://github.com/mysql-net/MySqlConnector/blob/73b3ddefd8682bfb0dad620ebb487158250f989e/src/MySqlConnector/MySqlConnection.cs#L411-L421

**Comment by bgrainger** [comment] 2021-12-21 21:08
Fixed in [MySqlConnector 2.1.1](https://github.com/mysql-net/MySqlConnector/releases/tag/2.1.1).

**Comment by jxlarrea** [comment] 2021-12-21 21:36
> Fixed in [MySqlConnector 2.1.1](https://github.com/mysql-net/MySqlConnector/releases/tag/2.1.1).

Can we just update MysqlConnector to the fixed version 2.1.1 and continue using Pomelo.EntityFrameworkCore.MySql current version 6.0?

**Comment by mguinness** [comment] 2021-12-21 21:59
Yes, the dependency is MySqlConnector (>= 2.0.0) so just add it to your csproj.

**Comment by nelsonprsousa** [comment] 2021-12-21 22:16
Hi team, I just found this issue, too. I am using `AddPooledDbContextFactory` instead of `AddDbContextPool` and I can say that the issue also happens if I pass a cancellation token (I am using the async versions).

I believe the problem is the same?

**Comment by mguinness** [comment] 2021-12-21 23:52
@nelsonprsousa Since this issue was in the underlying MySqlConnector library, it doesn't necessitate a change to the Pomelo library.  Simply add `<PackageReference Include="MySqlConnector" Version="2.1.1" />` to your csproj file.

**Comment by nelsonprsousa** [comment] 2021-12-22 00:00
> @nelsonprsousa Since this issue was in the underlying MySqlConnector library, it doesn't necessitate a change to the Pomelo library. Simply add `<PackageReference Include="MySqlConnector" Version="2.1.1" />` to your csproj file.

Working as expected 🚀 

Thank you

**Comment by lauxjpn** [comment] 2022-01-06 20:19
> Will the dependency be updated to MySqlConnector (>= 2.1.1) in the next release?

@nelsonprsousa Yes, we will release a `6.0.1` version this weekend, that will reference the latest version of MySqlConnector and EF Core.

**Comment by nelsonprsousa** [comment] 2022-01-06 22:55
> > Will the dependency be updated to MySqlConnector (>= 2.1.1) in the next release?
> 
> @nelsonprsousa Yes, we will release a `6.0.1` version this weekend, that will reference the latest version of MySqlConnector and EF Core.

Cool, I can test a RC if you need 👍

**Closed** 2022-01-13 17:45 UTC
Labels: closed-external, closed-fixed, external

**Comment by nelsonprsousa** [comment] 2022-01-13 23:39
> @nelsonprsousa Took a week longer than planned, but the latest [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) is feature complete in regards to `6.0.1` and references MySqlConnector `2.1.2`, in case you want to give it a spin.

That's awesome @lauxjpn, awesome job 👏 
I'll get back to you as soon as I test it 🚀

**Comment by nelsonprsousa** [comment] 2022-01-14 15:31
> @nelsonprsousa Took a week longer than planned, but the latest [nightly build](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#nightly-builds) is feature complete in regards to `6.0.1` and references MySqlConnector `2.1.2`, in case you want to give it a spin.

I am using Packages.props and Microsoft.Build.CentralPackageVersions to centralize versions. Any idea how to get nightly builds this way?

**Comment by lauxjpn** [comment] 2022-01-16 12:24
@nelsonprsousa Should work pretty much the same as for projects without using `Microsoft.Build.CentralPackageVersions`:

Update the `Nuget.config` file with the nightly build feed.
Then update the referenced package version (in your case located in your `Packages.props` file) to the respective version from the newly added feed (e.g. [6.0.1-servicing.1.ci.20220114125709+sha.1974429](https://dev.azure.com/pomelo-efcore/Pomelo.EntityFrameworkCore.MySql/_packaging?_a=package&feed=pomelo-efcore-public&package=Pomelo.EntityFrameworkCore.MySql&protocolType=NuGet&version=6.0.1-servicing.1.ci.20220114125709%2Bsha.1974429)).

**Comment by nelsonprsousa** [comment] 2022-01-26 12:40
> @nelsonprsousa Should work pretty much the same as for projects without using `Microsoft.Build.CentralPackageVersions`:
> 
> Update the `Nuget.config` file with the nightly build feed. Then update the referenced package version (in your case located in your `Packages.props` file) to the respective version from the newly added feed (e.g. [6.0.1-servicing.1.ci.20220114125709+sha.1974429](https://dev.azure.com/pomelo-efcore/Pomelo.EntityFrameworkCore.MySql/_packaging?_a=package&feed=pomelo-efcore-public&package=Pomelo.EntityFrameworkCore.MySql&protocolType=NuGet&version=6.0.1-servicing.1.ci.20220114125709%2Bsha.1974429)).

Everything's rocking 🚀

**Comment by BigShady187** [comment] 2023-08-31 11:39
I had the same error: 

.Net 7 
Entity Framework 
Pomelo
Angular 

When I use a combineLatest I get this error. 
"This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse"

Solution was not to use combineLatest. 
It is more a workaround than a fix.
