### ISSUE TITLE
Invalid DB query generated

### ISSUE THREAD

**Issue by incolor2** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1180] opened 2020-09-30 13:34 UTC
### Steps to reproduce
Rename a db column

```
using Microsoft.EntityFrameworkCore.Migrations;

namespace Scania.Maintenance.PlanSearch.DbMigration.Migrations
{
    public partial class featuremodelupdate : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "RecalcualationDate",
                table: "Plans",
                newName: "RecalculationDate");

            migrationBuilder.RenameColumn(
                name: "ExecutingWorkshopId",
                table: "Modules",
                newName: "PerformingWorkshopId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "RecalculationDate",
                table: "Plans",
                newName: "RecalcualationDate");

            migrationBuilder.RenameColumn(
                name: "PerformingWorkshopId",
                table: "Modules",
                newName: "ExecutingWorkshopId");
        }
    }
}

```

### The issue
MYSql 8 query being generated. 
Generated: ALTER TABLE `Plans` RENAME COLUMN `RecalcualationDate` TO `RecalculationDate`;

MYSql 5.7
Expected: ALTER TABLE tableName CHANGE `oldcolname` `newcolname` datatype(length);

```
Exception message:  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use ne
Stack trace:


ALTER TABLE `Plans` RENAME COLUMN `RecalcualationDate` TO `RecalculationDate`;
307 | MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COLUMN `RecalcualationDate` TO `RecalculationDate`' at line 1
308 | ---> MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COLUMN `RecalcualationDate` TO `RecalculationDate`' at line 1
309 | at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 51
310 | at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 130
311 | at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
312 | at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
313 | at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 218
314 | at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 68
315 | at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
316 | at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
317 | at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
318 | at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
319 | at Pomelo.EntityFrameworkCore.MySql.Migrations.Internal.MySqlMigrator.Migrate(String targetMigration)
320 | at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
321 | at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String contextType)
322 | at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
323 | at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
324 | You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COLUMN `RecalcualationDate` TO `RecalculationDate`' at line 1
325


```

### Further technical details

MySQL version: aws aurora 5.7.30
Operating system: linux
Pomelo.EntityFrameworkCore.MySql version: 3.2.2
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:

**Comment by lauxjpn** [comment] 2020-09-30 13:48
You need to specify your server version and type. Otherwise, the latest MySQL server version is assumed (which is `8.0.21`, that supports the `RENAME` syntax):

```c#
.UseMySql(
    "server=localhost;user=root;password=1234;database=ef",
    mySqlOptions => mySqlOptions
        .ServerVersion(new Version(8, 0, 21), ServerType.MySql) // <-- specify your server version and type
        .CharSetBehavior(CharSetBehavior.NeverAppend))
```

This is a duplicate of #1116, #1042, #1016 and #971.

**Closed by lauxjpn** 2020-09-30 13:48 UTC
