### ISSUE TITLE
Set default length of string type to 256

### ISSUE THREAD

**Issue by adnan-kamili** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#253] opened 2017-04-08 11:30 UTC
By default pomelo sets all properties to type **LongText** which is not very efficient. How can we change the default type for string using some global setting. I don't want to add data annonation to each property of every model to change the default type for string.

**Comment by Kagamine** [comment] 2017-04-09 00:13
Dupe of #195

**Closed by Kagamine** 2017-04-09 00:13 UTC

**Comment by adnan-kamili** [comment] 2017-04-09 06:34
@Kagamine how is this a duplicate. If I create a simple model class:
```
public class Product : BaseTenantEntity
{
      [Required]
      public string Name { get; set; }
}
```

Corresponding to above "Name" field the data type generated in database is "Long Text" by default. So, I want to change this default of "Long Text" to "varchar(256)" without adding annonation to my model class.

**Comment by Kagamine** [comment] 2017-04-09 08:20
sorry I've misunderstood you.

For your issue, you should create a custom typemapper class like the following code:

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlTypeMapper.cs#L174

and change the line 174, modify it to 256, and add your class into DI collection.

**Comment by adnan-kamili** [comment] 2017-04-09 08:24
How would that change the default string mapping to varchar(256) from longtext. Suppose if need default to be varchar(127) what change would I make?

**Comment by Kagamine** [comment] 2017-04-09 09:10
Create a CustomMySqlTypeMapper to replace the original one https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlTypeMapper.cs

and put your CustomTypeMapper into EF DI Collection.

**Comment by WilvdMerwe** [comment] 2022-12-01 14:03
@yukozh 

Hi there. I am trying to accomplish exactly this, but unfortunately, the provided example links are resulting in a 404. Assuming it is very outdated after so many years.

I am currently using v6.0.2 with .NET 6. 

I see that you can set DefaultDataTypeMappings through the options builder, but no there isn't an option for configuring the mapping for the CLR string. Might I ask why this is not available? 

Also, why is LONGTEXT the default in the first place as it is a very big data type involving the DISK instead of just using in-memory with VARCHAR for example? This is a problem for search performance as well.

![image](https://user-images.githubusercontent.com/38084711/205070166-3f3d3a0a-caf9-4047-b071-a6a0bda8a70f.png)


*PS: Thank you for this amazing library!

**Comment by KirillKaverin** [comment] 2022-12-02 11:10
@WilvdMerwe 
First of all, VARCHAR and TEXT (LONGTEXT) are stored identically in MySQL's InnoDB storage engine. There is no performance difference. But if you will try to make a string index in EF Core (Pomelo) --> it will change the LONGTEXT to VARCHAR.

Secondly, the default string length (and other CLR type) can be configured using [Pre-convention model configuration](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-6.0/whatsnew#pre-convention-model-configuration).
