### ISSUE TITLE
Dropping primary key causes error in POMELO_BEFORE_DROP_PRIMARY_KEY

### ISSUE THREAD

**Issue by hrabatom** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1941] opened 2024-09-18 14:33 UTC
I need to rename a table mapped to an entity. I generated a migration, which first run.
The migration runs migrationBuilder.DropPrimaryKey first, but this fail while running POMELO_BEFORE_DROP_PRIMARY_KEY, with error

```
Failed executing DbCommand (12ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
DROP PROCEDURE IF EXISTS `POMELO_BEFORE_DROP_PRIMARY_KEY`;
CREATE PROCEDURE `POMELO_BEFORE_DROP_PRIMARY_KEY`(IN `SCHEMA_NAME_ARGUMENT` VARCHAR(255), IN `TABLE_NAME_ARGUMENT` VARCHAR(255))
BEGIN
	DECLARE HAS_AUTO_INCREMENT_ID TINYINT(1);
	DECLARE PRIMARY_KEY_COLUMN_NAME VARCHAR(255);
	DECLARE PRIMARY_KEY_TYPE VARCHAR(255);
	DECLARE SQL_EXP VARCHAR(1000);
	SELECT COUNT(*)
		INTO HAS_AUTO_INCREMENT_ID
		FROM `information_schema`.`COLUMNS`
		WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
			AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
			AND `Extra` = 'auto_increment'
			AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
	IF HAS_AUTO_INCREMENT_ID THEN
		SELECT `COLUMN_TYPE`
			INTO PRIMARY_KEY_TYPE
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SELECT `COLUMN_NAME`
			INTO PRIMARY_KEY_COLUMN_NAME
			FROM `information_schema`.`COLUMNS`
			WHERE `TABLE_SCHEMA` = (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA()))
				AND `TABLE_NAME` = TABLE_NAME_ARGUMENT
				AND `COLUMN_KEY` = 'PRI'
			LIMIT 1;
		SET SQL_EXP = CONCAT('ALTER TABLE `', (SELECT IFNULL(SCHEMA_NAME_ARGUMENT, SCHEMA())), '`.`', TABLE_NAME_ARGUMENT, '` MODIFY COLUMN `', PRIMARY_KEY_COLUMN_NAME, '` ', PRIMARY_KEY_TYPE, ' NOT NULL;');
		SET @SQL_EXP = SQL_EXP;
		PREPARE SQL_EXP_EXECUTE FROM @SQL_EXP;
		EXECUTE SQL_EXP_EXECUTE;
		DEALLOCATE PREPARE SQL_EXP_EXECUTE;
	END IF;
END;
MySqlConnector.MySqlException (0x80004005): Cannot load from mysql.proc. The table is probably corrupted
```

We're using Pomelo.EntityFrameworkCore.MySql 7.0.0 and can't upgrade yet to 8.0.2.
Related to #1828?

**Comment by lauxjpn** [comment] 2024-12-14 08:19
> Related to https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1828?

@hrabatom No. The error states:

> MySqlConnector.MySqlException (0x80004005): Cannot load from mysql.proc. The table is probably corrupted

The internal database `mysql` seems to be in an unexpected state. So you need to fix it, before _any_ stored procedure can be added (you can test this by adding _any_ stored procedure to _any_ database, which should fail with the same error).

To fix it, try the following links or do your own google search about the error message (this issue should not be related to Pomelo):

- [Cannot load from mysql.proc. The table is probably corrupted](https://stackoverflow.com/questions/27918764/cannot-load-from-mysql-proc-the-table-is-probably-corrupted)
- [MySQL / MariaDB mysqldump error: Cannot load from mysql.proc. The table is probably corrupted (1728)](https://www.claudiokuenzler.com/blog/1194/mysql-mariadb-mysqldump-error-cannot-load-from-mysql-proc-table-corrupted-1728)
- [Error Code: 1728. Cannot load from mysql.db. The table is probably corrupted](https://dba.stackexchange.com/questions/229353/error-code-1728-cannot-load-from-mysql-db-the-table-is-probably-corrupted)
- [MySQL/MariaDB reports the error on a Plesk for Linux server: Cannot load from mysql.<table_name>. The table is probably corrupted](https://support.plesk.com/hc/en-us/articles/12377965178135-MySQL-MariaDB-reports-the-error-on-a-Plesk-for-Linux-server-Cannot-load-from-mysql-table-name-The-table-is-probably-corrupted)

According to most of those links, the issue can most likely be fixed by running `mysql_upgrade`.

**Comment by hrabatom** [comment] 2024-12-16 05:55
The problem happens even on the newly installed DB with fresh empty tables. If I generate a migration script and run it, all works without a problem. And finally the problem happens also to my colleagues.

**Comment by lauxjpn** [comment] 2024-12-17 00:58
If you think this is a Pomelo issue, please provide a minimum reproducible example project.

**Comment by hrabatom** [comment] 2024-12-17 09:26
I'm using MariaDB 10.11, .NET 8, EF 8.0.11 and Pomelo.EntityFrameworkCore,MySql 8.0.2

**Comment by hrabatom** [comment] 2024-12-17 09:45
Tested now with completely new docker container and all works well.

**Comment by hrabatom** [comment] 2024-12-17 09:58
It seems `mysql_upgrade -u root -p` run on the problematic container fixed the table renaming problem! It seems that the db image the whole team is using to restore the DB is broken. Thank you so much for the support!

**Comment by lauxjpn** [comment] 2024-12-20 00:46
> According to most of those links, the issue can most likely be fixed by running `mysql_upgrade`.

> It seems `mysql_upgrade -u root -p run` on the problematic container fixed the table renaming problem! It seems that the db image the whole team is using to restore the DB is broken. Thank you very much for the support!

@hrabatom I am glad to here you were able to fix the issue. We will close this one then.

**Closed by lauxjpn** 2024-12-20 00:46 UTC
Labels: needs-more-info, could-not-reproduce
