### ISSUE TITLE
Add `HasKeyLength` method (for indices/keys)

### ISSUE THREAD

**Issue by eduardoxvii** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#936] opened 2019-11-12 17:10 UTC
### Steps to reproduce
It's migration of tables for Identity.

```
>              /*migrationBuilder.AlterColumn<string>(
                name: "Id", <-- It's PrimaryKey!
                table: "AspNetUsers",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "varchar(255)");*/
> 
>             /*migrationBuilder.AlterColumn<string>(
>                 name: "LoginProvider", <-- It's Index!
>                 table: "AspNetUserTokens",
>                 nullable: false,
>                 oldClrType: typeof(string),
>                 oldType: "varchar(255)");*/
> 
>             /*migrationBuilder.AlterColumn<string>(
>                 name: "UserId", <-- It's ForeignKey!
>                 table: "AspNetUserTokens",
>                 nullable: false,
>                 oldClrType: typeof(string),
>                 oldType: "varchar(255)");*/
```

### The issue
**LongText can't be PrimaryKey, ForeignKey and Index!**

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 1000 bytes
 ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Specified key was too long; max key length is 1000 bytes
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior)

### Further technical details

MySQL version: 8.0
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc3.final
Microsoft.AspNetCore.App version: 3.0

Other details about my project setup:

**Comment by lauxjpn** [comment] 2019-11-12 18:14
This is a known limitation of the InnoDB engine in MySQL.
A quick google search will produce the following to links:
- [StackOverflow](https://stackoverflow.com/questions/8746207/1071-specified-key-was-too-long-max-key-length-is-1000-bytes)
- [StackExchange](https://dba.stackexchange.com/questions/49913/specified-key-was-too-long-max-key-length-is-1000-bytes-in-mysql-5-6)

The underlying issue is discussed in the official MySQL docs: [15.22 InnoDB Limits](https://dev.mysql.com/doc/refman/8.0/en/innodb-limits.html)

> The index key prefix length limit is 3072 bytes for InnoDB tables that use DYNAMIC or COMPRESSED row format.
>
>The index key prefix length limit is 767 bytes for InnoDB tables that use the REDUNDANT or COMPACT row format. For example, you might hit this limit with a column prefix index of more than 191 characters on a TEXT or VARCHAR column, assuming a utf8mb4 character set and the maximum of 4 bytes for each character.
>
>Attempting to use an index key prefix length that exceeds the limit returns an error.
>
>If you reduce the InnoDB page size to 8KB or 4KB by specifying the innodb_page_size option when creating the MySQL instance, the maximum length of the index key is lowered proportionally, based on the limit of 3072 bytes for a 16KB page size. That is, the maximum index key length is 1536 bytes when the page size is 8KB, and 768 bytes when the page size is 4KB.
>
>The limits that apply to index key prefixes also apply to full-column index keys.

In your case, assuming `utf8mb4` as the default charset used for Id, 255 * 4 bytes = 1020 bytes, which is higher than 1000 bytes. Try a length of 250.

**Comment by mguinness** [comment] 2019-11-12 18:20
This has been discussed previously, for example see [Specified key was too long](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/298).

**Comment by lauxjpn** [comment] 2019-11-12 18:27
We should consider adding support for the `CREATE INDEX index_name ON (col_name(length))` syntax (with the emphasis on `length`), so a column can be longer than the max. possible key length.

**Comment by lauxjpn** [comment] 2019-11-14 07:44
@eduardoxvii Did you expect your types to change from `varchar(255)` to `text`, or is this unexpected?

**Comment by lauxjpn** [comment] 2019-11-18 17:08
@eduardoxvii Also see #937 as your issue could have the same underlying cause (can't tell from the snippets you posted).

**Comment by eduardoxvii** [comment] 2019-11-19 18:21
> @eduardoxvii Did you expect your types to change from `varchar(255)` to `text`, or is this unexpected?

Its was unexpected...
Because Mysql don't allow LongText to be PrimaryKey, ForeignKey and Index.

**Comment by lauxjpn** [comment] 2019-11-19 20:55
Please check, if your issue is the same as in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/937#issuecomment-554582750 and is resolved with the solution there.

If not, please provide us with steps to reproduce your issue (model, migrations, expected output and actual output as a bare minimum).

**Comment by NicolasDorier** [comment] 2019-12-13 06:13
I am unsure yet, but it seems to have happen when I bumped from 2.1.2 to 2.1.4

**Comment by lauxjpn** [comment] 2019-12-13 08:42
@NicolasDorier Which behavior exactly are you talking about here, because this issue did discuss multiple problems? Also please share a model definition of an entity with the described behavior with us.

**Comment by NicolasDorier** [comment] 2019-12-15 12:36
@lauxjpn I will try to dig around...
On my project the generated script use LongText. But another attempt to reproduce this with same version on a blank project result in a Varchar. I am unsure why it happens.

**Comment by lauxjpn** [comment] 2019-12-15 12:44
@NicolasDorier In case you can't figure out the root cause, just post the model class, its related model definition and the generated migration.

**Comment by NicolasDorier** [comment] 2019-12-15 13:00
@lauxjpn if you have time to take a look:

```
git clone https://github.com/NicolasDorier/btcpayserver
cd btcpayserver
git checkout bug/mysqlmigration
cd BTCPayServer.Data
dotnet ef migrations script
```

See any table with id seems to have issue:

```
CREATE TABLE `AspNetRoles` (
    `Id` longtext NOT NULL,
    `ConcurrencyStamp` longtext NULL,
    `Name` varchar(256) NULL,
    `NormalizedName` varchar(256) NULL,
    CONSTRAINT `PK_AspNetRoles` PRIMARY KEY (`Id`)
);
```

**Comment by NicolasDorier** [comment] 2019-12-15 13:07
mmmh strange thing is that even if I go back very far, it is still longtext. I don't understand why, this was working before. 
Maybe it is because I use the SDK  `2.1.14-servicing-32113`

**Comment by lauxjpn** [comment] 2019-12-15 13:08
This is expected behavior in your case. You don't define a maximum length for the `Id` string property, so you force the provider to use `longtext` instead of `varchar(n)`.

**Comment by NicolasDorier** [comment] 2019-12-17 14:37
@lauxjpn that make sense, but those migration files were created in a previous version of .NET Core and that was working fine before.

If I start modifying the old files manually, not only there is the risk I introduce bugs, but my users will start getting different schema for other DBs.

**Comment by NicolasDorier** [comment] 2019-12-17 14:39
I am slightly suspecting that those migration files are fragile to updates (coming from frameworks or dotnet core ef itself)

I don't really know how I should solve this.
Maybe old generating the sql scripts and executing them raw instead of relying on ef migration classes?
It seems all my dbs are supporting idempotent scripts.

**Comment by lauxjpn** [comment] 2019-12-17 15:05
> I am slightly suspecting that those migration files are fragile to updates (coming from frameworks or dotnet core ef itself)

They are. We generally try not to break anything that has been generated before, but as with the move from 2.2.6 to 3.0 for example, breaking changes were inevitable for us.

> Maybe generating the sql scripts and executing them raw instead of relying on ef migration classes?

That is the only safe way to apply migrations. See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/972#issuecomment-559245037 on this one.

> If I start modifying the old files manually, not only there is the risk I introduce bugs, but my users will start getting different schema for other DBs.

If you use the same model (and definition) multiple providers, the EF Core doc's [Migrations with Multiple Providers](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli) (especially *One migration set* might be of interest to you) and [Alternating between multiple models with the same DbContext type](https://docs.microsoft.com/en-us/ef/core/modeling/dynamic-model) articles valid approaches for the issue you are facing.

There is also the more advanced approach (which works for Pomelo 2.2.6+) to provide your Pomelo specific type mapping plugin, with which you could basically override the default string-without-length mapping to `longtext` and make it map to `varchar(n)` instead.

**Comment by NicolasDorier** [comment] 2019-12-17 15:18
Thanks a lot I will look proper way to fix that.

> with which you could basically override the default string-without-length mapping to longtext and make it map to varchar(n) instead

This seems to me the right workaround in the short term, where can I find some info to do it?

> They are. We generally try not to break anything that has been generated before, but as with the move from 2.2.6 to 3.0 for example, breaking changes were inevitable for us.

I feel your pain, EF Core has been a real pain for backward compatibility. If I had to do it again, I would just use Dapper and support a single database rather than using EF Core. :(

**Comment by NicolasDorier** [comment] 2019-12-17 15:20
Thanks so much for this link https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli now I am amazed that what I did actually worked for so long...

**Comment by lauxjpn** [comment] 2019-12-17 15:33
> I feel your pain, EF Core has been a real pain for backward compatibility. If I had to do it again, I would just use Dapper and support a single database rather than using EF Core. :(

I am actually *for* breaking changes in general, because this seems the only way to me to ensure, that technologies can move forward without being held back by obsolete features, which had been a large problem for .NET Framework. Though for 3.0, the EF Core team probably overdid it a bit (though this probably was a "now or never" decision that had to be made).

> This seems to me the right workaround in the short term, where can I find some info to do it?

The code snippet I pasted above should work out-of-the-box (it could be generalized by iterating over the model entities and their respective key properties and apply the max. length only to those of type `System.String`, but this is probably unnecessary). Check the generated script afterwards, it should change all/most relevant Id fields.

This might be safer and easier than to implement a type mapping plugin and I don't expect that you would need to change anything besides either adding the max. length or the actual column type (including the length, like `.HasColumnType("varchar(255)")`. That being said...

To implement a type mapping plugin, take a look at think tecture's [Entity Framework Core - Improved Value Conversion Support](https://www.thinktecture.com/entity-framework/entity-framework-core-improved-value-conversion-support/) (the *Implement the `IRelationalTypeMappingSourcePlugin`* section).

**Comment by mguinness** [comment] 2019-12-17 16:54
> (I would normally paste you some working code right away, but I have to leave for a Christmas party and will be heavily intoxicated soon. 🍷)

Well deserved I might add - thanks for all your hard work on this repo so enjoy!

**Comment by lauxjpn** [comment] 2019-12-21 16:37
@NicolasDorier Were you able to get it to work?

**Comment by NicolasDorier** [comment] 2019-12-22 13:23
@lauxjpn I really appreciate your help. I have still not came back at it.
Will probably this week. I will keep you up-to-date here.

The problem is less specific to Pomelo and more specific that I started supporting several database without creating the different migration files for each.
Now I am thinking about how to solve this issue properly, I don't think this will be easy.

The  type mapping plugin though will be my short term solution.

**Comment by lauxjpn** [comment] 2019-12-22 14:17
I did take a look into your particular problem a couple of days ago.

The first thing you might want to do is to update your references (especially the Pomelo 3.0.0-rc1 one, or plugins will not be supported yet).

Then you should probably refactor your `Main()` method of your Server project to implement a `CreateWebHostBuilder` method, so that the EF Core tools can use your actual `DbContext` configuration (which is not the case at the moment). It could look similar to the following:
<details>
<summary>Program.cs</summary>

```c#
class Program
{
    private static IConfiguration _conf;
    private static ConsoleLoggerProcessor _processor;
    private static CustomConsoleLogProvider _loggerProvider;
    private static ILogger _logger;

    static void Main(string[] args)
    {
        ServicePointManager.DefaultConnectionLimit = 100;
        IWebHost host = null;
        try
        {
            host = CreateWebHostBuilder(args).Build();

            host.StartWithTasksAsync().GetAwaiter().GetResult();
            var urls = host.ServerFeatures.Get<IServerAddressesFeature>().Addresses;
            foreach (var url in urls)
            {
                _logger.LogInformation("Listening on " + url);
            }
            host.WaitForShutdown();
        }
        catch (ConfigException ex)
        {
            if (!string.IsNullOrEmpty(ex.Message))
                Logs.Configuration.LogError(ex.Message);
        }
        finally
        {
            _processor.Dispose();
            if(host == null)
                Logs.Configuration.LogError("Configuration error");
            if (host != null)
                host.Dispose();
            Serilog.Log.CloseAndFlush();
            _loggerProvider.Dispose();
        }
    }
    
    public static IWebHostBuilder CreateWebHostBuilder(string[] args)
    {
        // Debugger.Launch();
        
        _processor = new ConsoleLoggerProcessor();
        _loggerProvider = new CustomConsoleLogProvider(_processor);
        var loggerFactory = new LoggerFactory();
        loggerFactory.AddProvider(_loggerProvider);
        _logger = loggerFactory.CreateLogger("Configuration");

        // This is the only way that LoadArgs can print to console. Because LoadArgs is called by the HostBuilder before Logs.Configure is called
        _conf = new DefaultConfiguration() { Logger = _logger }.CreateConfiguration(args);
        if (_conf == null)
            return null;

        // HACK: Force MySQL as the provider to use.
        _conf["mysql"] = "Server=myServerAddress;Database=myDataBase;Uid=myUsername;Pwd=myPassword;";
        
        Logs.Configure(loggerFactory);
        new BTCPayServerOptions().LoadArgs(_conf);
        
        Logs.Configure(null);
        
        /////
        return new WebHostBuilder()
            .UseKestrel()
            .UseIISIntegration()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseConfiguration(_conf)
            .ConfigureLogging(l =>
            {
                l.AddFilter("Microsoft", LogLevel.Error);
                l.AddFilter("System.Net.Http.HttpClient", LogLevel.Critical);
                l.AddFilter("Microsoft.AspNetCore.Antiforgery.Internal", LogLevel.Critical);
                l.AddFilter("OpenIddict.Server.OpenIddictServerProvider", LogLevel.Error);
                l.AddProvider(new CustomConsoleLogProvider(_processor));
            })
            .UseStartup<Startup>();
    }
}
```
</details>

This will work with the following command then:

```
dotnet ef migrations add MyMigration --verbose --startup-project ..\BTCPayServer --framework netcoreapp3.0
```

---

> The problem is less specific to Pomelo and more specific that I started supporting several database without creating the different migration files for each.

I agree. You have basically to options here:

#### You can continue to use the Sqlite provider as the single source you generate the migrations from:

In this case you can just add the following code to the end of your `OnModelCreating` method (choose any appropriate max. length parameter):

```
builder.Entity<ApplicationUser>()
    .Property(e => e.Id)
    .HasMaxLength(191); // <-- define the max. length the column can have
```

This would keep the model consistent over all database servers by applying the max. length to all schemas in all databases.

This approach is very simple and quick to implement.

#### The other approach is to generate individual migrations for every supported database provider: 

To accomplish that, you can use the suggested `if (Database.IsMySql()) {}` clause to wrap around the code of the first approach.

Switching between different providers could be accomplished by setting an environment variable (or some other mechanism).

---

You could also use an `IRelationalTypeMappingSourcePlugin` implementation instead, but it will require the same amount of plumbing, because it is a singleton implementation and will need to check the used database provider at some point as well.

Keeping the code in the `OnModelCreating` method is probably simpler and more natural, because it is the place where you would expect the model definition to reside, instead of looking for some type mapping hack.

**Comment by NicolasDorier** [comment] 2019-12-23 04:11
> The first thing you might want to do is to update your references (especially the Pomelo 3.0.0-rc1 one, or plugins will not be supported yet).

I am still on .NET 2.1, which does not seem supported by pomelo 3.0.0.
I plan to update to .NET 3.1 though, but I think for the time being, using `HasMaxLength` is the right approach.

I will have to properly think about it when generating the migration script.

**Comment by NicolasDorier** [comment] 2019-12-23 04:51
@lauxjpn the fix won't be so easy I think.

Right now, my migrations generate `BLOB/TEXT column 'Id' used in key specification without a key length`. (https://github.com/btcpayserver/btcpayserver/issues/1224)

This mean that I can't just add `MaxLength` to my ids and generate a new script to alter the size of columns.

I need to add to each migration script the column size, only for MySql.

**Comment by NicolasDorier** [comment] 2019-12-23 06:07
@lauxjpn I ended up implementing https://github.com/btcpayserver/btcpayserver/pull/1231

I will have to be careful to add keylength from now.

I think I should stay away from EntityFramework migration script generation and instead commit the script themselves to prevent breakage like this in the future.

**Comment by lauxjpn** [comment] 2019-12-23 12:58
@NicolasDorier I am glad you found a solution that works for you. But i think it would be easier to just add the max. length for all providers. After all, there should be really no benefit in having possibly huge Id string values anyway. Sqlite supports this (see their [FAQ](https://www.sqlite.org/faq.html#q9)) and you could continue to use their provider for most of your migration generations without the need to modify them.

**Comment by NicolasDorier** [comment] 2019-12-23 14:54
@lauxjpn so I was thinking adding the max length.

The problem is that I can't regenerate all the migration classes. And even if I did, I would still need to make a migration which resize the columns, else I will end up in a situation with different schema for different deployment but same btcpayserver version.

**Comment by NicolasDorier** [comment] 2019-12-23 15:02
btw, I am surprised to see that before `varchar(255)` was generated for string ids without max length.

The current situation is more logical. I think I am still ending up with different schema for MySql because of this change for some columns, but I don't think this will be a big deal.

**Comment by lauxjpn** [comment] 2019-12-23 15:25
> btw, I am surprised to see that before varchar(255) was generated before for string ids without max length.

It would be interesting to know, which of your commits introduced the behavior change. For example, if for some reason the default provider used by your `DbContext` changed (from something else to Sqlite), then the difference in migration script generation would be explained.

**Comment by NicolasDorier** [comment] 2019-12-24 03:57
The strangest thing is that I tried to git checkout the version on which it was working.
I changed the default provider to mysql and did `dotnet ef scripts`. And it was still longtext...

The only explanation I can think of is that recently I moved from 2.1.9 to 2.1.14. Because my computer use 2.1.14 now, I could not reproduce the previous working version.

**Closed** 2020-04-25 14:44 UTC
Labels: type-enhancement, type-question
