### ISSUE TITLE
when is ready first release of version 5.X?

### ISSUE THREAD

**Issue by rchalco** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1315] opened 2021-01-28 20:23 UTC
Hi, first of all congratulation for great nueget!
I use in my project, but i need know when will the full release of version 5, thanks a lot

**Comment by mguinness** [comment] 2021-01-28 20:59
Closing as duplicate of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088.

**Closed by mguinness** 2021-01-28 20:59 UTC
