### ISSUE TITLE
Generate migrations for object embedded as JSON column (e.g. property add / edit / remove)

### ISSUE THREAD

**Issue by mrtnbrst** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1826] opened 2024-01-03 12:08 UTC
### Steps to reproduce
Check the commit [feat: add migration for renamed, added and removed properties of json object](https://github.com/mrtnbrst/EFCoreMySQLJSONMigrationIssueDemo/commit/de3ab7f131f3f0a80f4c8f62e28ebfce6adb80fa)
and the prior commit [feat: setup efcore example with mysql and json column](https://github.com/mrtnbrst/EFCoreMySQLJSONMigrationIssueDemo/commit/c64247026a6190ede10087641e8ca71992cfd297) of the repository created for this issue.

### The issue
The object serialized as JSON has a renamed, added and removed.
Expected behaviour is that EFCore is able to detect those changes and generates the proper migrations.

I guess this is not easy to solve and I have to stick with manual migrations, do I?

Any recommendations on how to handle JSON column migrations?

### Further technical details

MySQL version: 8.0.32
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 7.0.0
Microsoft.AspNetCore.App version: 7.0.14

**Comment by roji** [comment] 2024-01-03 15:38
Duplicate of https://github.com/dotnet/efcore/issues/32301

**Comment by roji** [comment] 2024-01-03 15:39
https://github.com/dotnet/efcore/issues/32301 would cover this, at least when EF's ToJson() support is used (AFAIK the Pomelo provider does not support this yet).

**Comment by mrtnbrst** [comment] 2024-01-03 15:42
Thanks for you quick answer - should we close this issue then or keep it as a reminder once there is progress with the efcore issue you mentioned?

**Comment by roji** [comment] 2024-01-03 16:18
The question of evolving schemas within JSON schemas is a very open and large one, requiring lots of careful designing... For example, it isn't clear whether a model change should cause a bulk update (UPDATE) migration which modifies all columns then and there, or rather whether a version property should be included inside the document, with schema changes applied lazily when the document is loaded from the database; the answer is also probably database-dependent - non-relational document databases frequently have UPDATE equivalent, and eagerly updating all documents is unlikely to be the right answer.

So I'd recommend closing this issue, and when the discussions and implementation happen on the EF side, implementing on MySQL specifically will likely be a pretty minor thing (compared to the general questions).

**Closed** 2024-01-03 20:28 UTC
