### ISSUE TITLE
Migration fails when comment are multi-line

### ISSUE THREAD

**Issue by babyblue2** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1572] opened 2021-11-26 11:34 UTC
### Steps to reproduce

1. Here is the entity code:
```C#
using Microsoft.EntityFrameworkCore;

[Comment(@"ABC
DEF")]
public class TableA
{
    [Comment("123\r\n456")]
    public int FieldA { get; set; }
}
```

2. Generate Migration Script in package management console:

```
Add-Migration U01
Update-Database
```

### The issue

```
Failed executing DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE `TableA` COMMENT CONCAT('ABC', CHAR(13, 10), 'DEF');
MySqlConnector.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CONCAT('ABC', CHAR(13, 10), 'DEF')' at line 1
```

### Further technical details

MySQL version: 8.0.27
Operating system: Windows 11 Home
Pomelo.EntityFrameworkCore.MySql version: 6.0.0
Microsoft.EntityFrameworkCore version: 6.0.0
.NET version: 6.0

**Comment by mguinness** [comment] 2021-11-26 19:20
Duplicate of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1567.

**Closed by mguinness** 2021-11-26 19:20 UTC
