### ISSUE TITLE
Error modifing index when used in FK

### ISSUE THREAD

**Issue by neumartin** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#784] opened 2019-05-08 20:12 UTC
Hi!

If I try to modify an index created automatically by FK, for example adding other field like this:

entityBuilder.HasIndex(e => new { e.IdEstadoPresupuesto, e.Date });

I get this error when migrations run:

'Cannot drop index 'IX_Presupuestos_IdEstadoPresupuesto': needed in a foreign key constraint'

**Comment by mguinness** [comment] 2019-05-08 22:18
Duplicate of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/678.

**Closed by mguinness** 2019-05-08 22:18 UTC
