### ISSUE TITLE
Multiple includes let MySql Server crash

### ISSUE THREAD

**Issue by hrattls** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#901] opened 2019-10-28 16:37 UTC
### Steps to reproduce
Consider the following query:
	var result = await _dbContext.MainTable
		.Include(m => m.Collection1)
		.Include(m => m.Collection2)
		.Include(m => m.Collection3)
		.Include(m => m.Collection4)
		.Include(m => m.Collection5)
		.Include(m => m.Collection6)
		.Include(m => m.Collection7)
		.Include(m => m.Collection8)
		.Include(m => m.Collection9)
		.Include(m => m.Collection10)
		.SingleOrDefaultAsync(m => m.Id == request.Id);

Assume that each related table contains 10 records for the given id.

In version 2.2 a subquery was generated for each collection.
So 10 queries were executed which each returned 10 rows.

In the 3.0  pre-release a single query is generated with a left join for each related table.
Each left join will multiply the number of rows in the temporary result.
So if each related table contains 10 records for the given id, a temporary result of 10000000000 rows is created.

### The issue
My MySql server cannot handle this. 
On my machine MySql claims all available memory
My machine begins to swap memory.
Memory usage goes to 100%
Disk activity goes to 100%
My entire machine hangs. 

### Further technical details
MySQL version: 8.0.16
Operating system: Windows 10 Professional
Pomelo.EntityFrameworkCore.MySql version: 3.0.0-rc1.final
Microsoft.AspNetCore.App version: 3.0

See attached image which shows the memory usage development, immediately after the query is started:
![memory usage](https://user-images.githubusercontent.com/57106402/67697852-848af800-f9a9-11e9-9a96-880463fe12d8.png)

**Comment by lauxjpn** [comment] 2019-10-28 16:50
This is a duplicate of #874 
You will find everything you need to know in there.

**Closed by lauxjpn** 2019-10-28 16:50 UTC

**Comment by mguinness** [comment] 2019-10-29 19:20
Specifically https://github.com/aspnet/EntityFrameworkCore/issues/18017 upstream.
