### ISSUE TITLE
Index/FK Down Migrations wrong with Long Names

### ISSUE THREAD

**Issue by matthewjcooper** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#135] opened 2016-11-29 21:16 UTC
If you have long table names included in a constraint, the Up migrations and Down migration both include the full name in the code. For instance: 

`name: "IX_OrganizationPatientMedications_OrganizationPatientId_MedicalConditionId_Name",`

When the Up migrations runs, you must be truncating the name to allow no error in the generated sql, because the actual constraint name in the database is: 

`"IX_OrganizationPatientMedications_OrganizationPatientId_MedicalC"`

This is fine for the up, but if you revert the migration, because the full name is in the Drop  method it produces an error that the constraint does not exists (presumably becuase it's sending the full name instead of the truncated version). Same if you create a new migrations that would drop the index if it changed.

I can work around this by manually creating the names myself, but I believe your Down code should also truncate the name so that it will work the same way the Up does.

Here are the versions of the libraries i'm using:

```
        "Microsoft.EntityFrameworkCore.Design": "1.1.0",
        "Microsoft.EntityFrameworkCore": "1.1.0",
        "Microsoft.EntityFrameworkCore.Relational": "1.1.0",
  "Microsoft.EntityFrameworkCore.Tools.DotNet": {
          "version": "1.1.0-preview4-*",
          "type": "build"
        },
        "Pomelo.EntityFrameworkCore.MySql": "1.1.0-rtm-10002",

```

**Comment by Kagamine** [comment] 2016-11-29 23:36
dupe of #12

**Closed** 2016-11-29 23:36 UTC

**Comment by matthewjcooper** [comment] 2016-11-29 23:37
Not really a dupe, this one has to do with the Drop of a constraint. #12 only had to do with the creation of the constraint, which works now, but the drop for it wont since it still includes the full name.

**Comment by Kagamine** [comment] 2016-11-29 23:52
MySQL has limited the max IX name, so you must use .HasName to short your ix name.
