### ISSUE TITLE
Auto increment identity column not working

### ISSUE THREAD

**Issue by tobe09** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1582] opened 2021-12-06 13:07 UTC
### Steps to reproduce
Ran initial migration with auto increment functionality.

### The issue
auto increment setting not applied to database.

MySQL version:  8.0.26
Operating system: Windows
Pomelo.EntityFrameworkCore.MySql version: 5.0.3
Microsoft.AspNetCore.App version: Net 5.0

**Comment by mguinness** [comment] 2021-12-06 18:00
Without providing more information (models, DbContext etc) we can't look into this.  Could be related to issue https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/711 or https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/720.

**Comment by tobe09** [comment] 2021-12-08 12:50
Sorry about this. Was under severe time pressure when I tried to use your library to handle renaming of columns for entity framework core migrations. By default, it did not ef core did not have an implementation for MigrationBuilder's RenameColumn method. Your lib fixed it for me but did not apply auto increment to my ids. Unfortunately, I had to remove your lib and use raw sql to rename the column.

Taget framework is .Net 5.0.
 <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.10" />
 <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.3">
 <PackageReference Include="MySql.EntityFrameworkCore" Version="5.0.0" />

**Comment by mguinness** [comment] 2021-12-08 19:38
> By default, EF core did not have an implementation for MigrationBuilder's RenameColumn method.

Can you clarify, do you mean the Oracle `MySql.EntityFrameworkCore` library?

> Your lib fixed it for me but did not apply auto increment to my ids.

Again, without more information we cannot repro and investigate.

> Unfortunately, I had to remove your lib and use raw sql to rename the column.

In general migrations containing rename operations may need to be modified by hand.

**Comment by lauxjpn** [comment] 2021-12-10 10:37
@tobe09 Sound to me like it was the time pressure that was the issue here. Has been working from the beginning and is being used in pretty much every example I post here.

In case you previously used the Oracle implementation, it is possible that your model is configured incorrectly for Pomelo, but that is only speculation since you did not post any code. We would need:
* a sample entity (class)
* its Fluent API if any (e.g. from the `OnModelCreating` method)
* the generated calls from the `Up()` method for that entity for the migration
* the snapshot parts of the migration that are relevant to the entity (Fluent API calls)
* the generated SQL for the calls in the `Up()` method (`dotnet ef migrations script`)
* the SQL that you would have expected to be generated instead

**Comment by h5aaimtron** [comment] 2022-01-14 18:41
I'm actually having an issue in a Parent Child relationship regarding auto-increment of the Child id.

`Public Class Album
{
    Public int Id { get; set; }
    Public List<Image> Images { get; set; }
}

Public Class Image
{
    Public int Id { get; set; }
    Public int AlbumId { get; set; }
    Public string Url { get; set; }
    Public virtual Album Album { get; set; }
}`

I'm using fluent api for the configuration:

// For the Album:
builder.HasMany(x => x.Images).WithOne(x => x.Album)

// For the Image:
builder.HasKey(x => new { x.AlbumId, x.Id });
builder.HasOne(x => x.Album).WithMany(x => x.Images);

I can insert new Albums just fine, however; when I instantiate a new Image (Id initializes to 0, AlbumId set to the Album's Id) and try to insert that child, it inserts the Id value as 0 instead of 1 (or 2 if there is already a child with 1). This of course throws duplicate entry issues. I've reviewed the config and classes in the previous version of my app (using another mysql db) and while the same, works fine. With the latest version, that same configuration no longer works. My workaround was to do a Max on the Id + 1, however; I an upload a lot of images at the same time to the same album and that can also cause duplicate errors due to timing.

**Comment by xiesamgh** [comment] 2022-01-15 22:27
> 

did you solve the problem? I got the same issue. 

get the script by running command: dotnet ef migrations script
I can see the following line. The auto increment included. 
`Id` int NOT NULL AUTO_INCREMENT,

But after I ran the migration command: dotnet ef database update
then I check the table, the AI checkbox is not ticked.

**Comment by mguinness** [comment] 2022-01-15 23:24
@xiesamgh What you describe seems unlikely.  Is this the initial migration, or a subsequent migration?  Were there any errors and did the migration show in `__EFMigrationsHistory` table?  See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1593#issuecomment-1012384412 for an example of a program you can try to reproduce the problem.

**Comment by h5aaimtron** [comment] 2022-01-15 23:32
@xiesamgh I wasn't able to solve the problem unfortunately. For now, I do a .Max(x => x.Id) on the parent instance's Child List and add 1 to it. This works fine if you're actually adding one at a time, but in my cases, these are uploaded images that happen concurrently and so the "tracked" entity may not represent the current db data. I'm hoping someone sheds some light on why this worked in previous versions but not 5.0.2. I may upgrade to .NET 6 and the 6.x release next, but have no guarantees that this issue has been fixed.

**Comment by lauxjpn** [comment] 2022-01-16 13:45
> I can insert new Albums just fine, however; when I instantiate a new Image (Id initializes to 0, AlbumId set to the Album's Id) and try to insert that child, it inserts the Id value as 0 instead of 1 (or 2 if there is already a child with 1). This of course throws duplicate entry issues.

@h5aaimtron I am assuming that the exception you are talking about is similar to the following:

`System.InvalidOperationException: The instance of entity type 'Image' cannot be tracked because another instance with the key value '{AlbumId: 2, Id: 0}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.`

Take a look at the followin code, that contains the additional Fluent API line (with a comment) to make a column/property of a multi-column PK `auto_increment` anyway:

<details>
<summary>Program.cs</summary>

```c#
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class Album
    {
        public int Id { get; set; }

        public List<Image> Images { get; set; }
    }

    public class Image
    {
        public int Id { get; set; }
        public int AlbumId { get; set; }

        public virtual Album Album { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Album> Albums { get; set; }
        public DbSet<Album> Images { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1582";
            var serverVersion = ServerVersion.AutoDetect(connectionString);

            optionsBuilder
                .UseMySql(connectionString, serverVersion)
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Album>(
                builder =>
                {
                    builder.HasMany(x => x.Images).WithOne(x => x.Album);
                });

            modelBuilder.Entity<Image>(
                builder =>
                {
                    builder.HasKey(x => new { x.AlbumId, x.Id });

                    builder.Property(x => x.Id).ValueGeneratedOnAdd(); // <-- make `Id` auto_increment, even though it
                                                                       //     is part of a multi column PK
                    
                    builder.HasOne(x => x.Album).WithMany(x => x.Images);
                });
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var firstNewAlbum = new Album();
                firstNewAlbum.Images = new List<Image>();
                firstNewAlbum.Images.Add(new Image { Album = firstNewAlbum });
                firstNewAlbum.Images.Add(new Image { Album = firstNewAlbum });
                context.Albums.Add(firstNewAlbum);

                var secondNewAlbum = new Album();
                secondNewAlbum.Images = new List<Image>();
                secondNewAlbum.Images.Add(new Image { Album = secondNewAlbum });
                context.Albums.Add(secondNewAlbum);

                context.SaveChanges();

                secondNewAlbum.Images.Add(new Image { Album = secondNewAlbum });

                context.SaveChanges();
            }
            
            using (var context = new Context())
            {
                var albumsWithImages = context.Albums
                    .Include(a => a.Images)
                    .OrderBy(a => a.Id)
                    .ToList();
                
                Trace.Assert(albumsWithImages.Count == 2);
                
                Trace.Assert(albumsWithImages[0].Id == 1);
                Trace.Assert(albumsWithImages[0].Images != null);
                Trace.Assert(albumsWithImages[0].Images.Count == 2);
                Trace.Assert(albumsWithImages[0].Images.OrderBy(i => i.AlbumId).ThenBy(i => i.Id).First().AlbumId == 1);
                Trace.Assert(albumsWithImages[0].Images.OrderBy(i => i.AlbumId).ThenBy(i => i.Id).First().Id == 1);
                Trace.Assert(albumsWithImages[0].Images.OrderBy(i => i.AlbumId).ThenBy(i => i.Id).Last().AlbumId == 1);
                Trace.Assert(albumsWithImages[0].Images.OrderBy(i => i.AlbumId).ThenBy(i => i.Id).Last().Id == 2);

                Trace.Assert(albumsWithImages[1].Id == 2);
                Trace.Assert(albumsWithImages[1].Images != null);
                Trace.Assert(albumsWithImages[1].Images.Count == 2);
                Trace.Assert(albumsWithImages[1].Images.OrderBy(i => i.AlbumId).ThenBy(i => i.Id).First().AlbumId == 2);
                Trace.Assert(albumsWithImages[1].Images.OrderBy(i => i.AlbumId).ThenBy(i => i.Id).First().Id == 3);
                Trace.Assert(albumsWithImages[1].Images.OrderBy(i => i.AlbumId).ThenBy(i => i.Id).Last().AlbumId == 2);
                Trace.Assert(albumsWithImages[1].Images.OrderBy(i => i.AlbumId).ThenBy(i => i.Id).Last().Id == 4);
            }
        }
    }
}
```

</details>

This results it the following SQL statements and table content, which is expected:

<details>
<summary>Log Output (SQL)</summary>

```sql
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE DATABASE `Issue1582`;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      ALTER DATABASE CHARACTER SET utf8mb4;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (21ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `Album` (
          `Id` int NOT NULL AUTO_INCREMENT,
          CONSTRAINT `PK_Album` PRIMARY KEY (`Id`)
      ) CHARACTER SET=utf8mb4;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (28ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE `Image` (
          `Id` int NOT NULL AUTO_INCREMENT,
          `AlbumId` int NOT NULL,
          CONSTRAINT `PK_Image` PRIMARY KEY (`Id`, `AlbumId`),
          CONSTRAINT `FK_Image_Album_AlbumId` FOREIGN KEY (`AlbumId`) REFERENCES `Album` (`Id`) ON DELETE CASCADE
      ) CHARACTER SET=utf8mb4;

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (8ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Album` ()
      VALUES ();
      SELECT `Id`
      FROM `Album`
      WHERE ROW_COUNT() = 1 AND `Id` = LAST_INSERT_ID();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Album` ()
      VALUES ();
      SELECT `Id`
      FROM `Album`
      WHERE ROW_COUNT() = 1 AND `Id` = LAST_INSERT_ID();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (15ms) [Parameters=[@p0='1'], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Image` (`AlbumId`)
      VALUES (@p0);
      SELECT `Id`
      FROM `Image`
      WHERE ROW_COUNT() = 1 AND `AlbumId` = @p0 AND `Id` = LAST_INSERT_ID();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@p0='1'], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Image` (`AlbumId`)
      VALUES (@p0);
      SELECT `Id`
      FROM `Image`
      WHERE ROW_COUNT() = 1 AND `AlbumId` = @p0 AND `Id` = LAST_INSERT_ID();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[@p0='2'], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Image` (`AlbumId`)
      VALUES (@p0);
      SELECT `Id`
      FROM `Image`
      WHERE ROW_COUNT() = 1 AND `AlbumId` = @p0 AND `Id` = LAST_INSERT_ID();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (2ms) [Parameters=[@p0='2'], CommandType='Text', CommandTimeout='30']
      INSERT INTO `Image` (`AlbumId`)
      VALUES (@p0);
      SELECT `Id`
      FROM `Image`
      WHERE ROW_COUNT() = 1 AND `AlbumId` = @p0 AND `Id` = LAST_INSERT_ID();

info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT `a`.`Id`, `i`.`AlbumId`, `i`.`Id`
      FROM `Album` AS `a`
      LEFT JOIN `Image` AS `i` ON `a`.`Id` = `i`.`AlbumId`
      ORDER BY `a`.`Id`, `i`.`AlbumId`
```

</details>


<details>
<summary>SQL tables</summary>

```
mysql> show tables;
+---------------------+
| Tables_in_issue1582 |
+---------------------+
| Album               |
| Image               |
+---------------------+
2 rows in set (0.02 sec)

mysql> select * from Album;
+----+
| Id |
+----+
|  1 |
|  2 |
+----+
2 rows in set (0.00 sec)

mysql> select * from Image;
+----+---------+
| Id | AlbumId |
+----+---------+
|  1 |       1 |
|  2 |       1 |
|  3 |       2 |
|  4 |       2 |
+----+---------+
4 rows in set (0.00 sec)
```

</details>

This will not produce any erros and will strictly increment the `Image.Id` value for every `Image` (independent of the `Album`).

---

As far as I am aware, there is no direct SQL statement in MySQL (or Pomelo support) for sequences that start auto incrementing the `Image.Id` from `1` again for every new `Image.AlbumId` added to the `Image`  table, nor have there been in the past. For this to work reliably in a concurrent environment, you would either need some C# transaction code, or a trigger on `Image` table (both solutions should work if properly implemented).

@h5aaimtron What Pomelo version were you using prior to `5.0.2`?
Please log the SQL that is being generated in that working version, so that we can take a look at it.

**Comment by lauxjpn** [comment] 2022-01-16 13:51
> did you solve the problem? I got the same issue.
> 
> get the script by running command: `dotnet ef migrations script` I can see the following line. The auto increment included.
> 
> `` `Id` int NOT NULL AUTO_INCREMENT ``
> 
> But after I ran the migration command: `dotnet ef database update` then I check the table, the AI checkbox is not ticked.

@xiesamgh This seems to be unrelated to the other discussion here. Please open a new issue for your issue, so we can help you independently. Thanks!

**Comment by h5aaimtron** [comment] 2022-01-16 17:20
@lauxjpn 

> @h5aaimtron I am assuming that the exception you are talking about is similar to the following:

>System.InvalidOperationException: The instance of entity type 'Image' cannot be tracked because another instance with the >key value '{AlbumId: 2, Id: 0}' is already being tracked. When attaching existing entities, ensure that only one entity instance >with a given key value is attached.

Yes, that was the initial error, however; your commented suggestion is what didn't work. When I added that line and created a migration, upon running the migration, I get an error about a foreign key constraint cannot be removed. When I modified the migration code to try to get around that particular error, I got an error that Id cannot be auto_increment as it isn't the first part of a primary key (I'm wording it funny, but same idea). I event went so far as to create a new database and the closest I got was that Id acted like a regular primary key with auto_increment and disregarded the AlbumId altogether. It is weird behavior.

**Comment by lauxjpn** [comment] 2022-01-16 18:20
> [...] your commented suggestion is what didn't work. When I added that line and created a migration, upon running the migration, I get an error about a foreign key constraint cannot be removed. [...]

@h5aaimtron That is an important detail that is completely missing from your original post. Your original post does not talk about migrations at all, but suggests that you are having issues with _querying_ data from the database.

Now, the first thing to check here is, whether my suggested line works actually fine for your application code (I am not talking about any migrations at this point, just the application code, because from what you have posted so far, no database schema change should be necessary for that code change to work, because you wrote earlier that it already worked before you upgraded Pomelo to `5.0.2`).

So please verify first, that querying with my suggested change works now indeed as expected.
Once that is the case, we can take a look at your migrations and table schemas.

---

Also:

> @h5aaimtron What Pomelo version were you using prior to 5.0.2?
> Please log the SQL that is being generated in that working version, so that we can take a look at it.

Thanks!

**Comment by h5aaimtron** [comment] 2022-01-16 20:06
@lauxjpn I was previously using 5.0.0 it appears. I tried something else a little bit ago. I dropped my table and let it recreate instead of migrating and that seems to have cleared it up (had to clear the migrations). Previously when I tried to migrate, it generated code to drop the Foreign Key, change the Primary Key (Add AI), and then add back the Foreign Key and its constraints, however; it couldn't drop the foreign key. At this point since I was able to regenerate everything and reload without issue, I can't replicate the problem without doing a bunch of migrations. I suspect what happened during one of the migrations is that a foreign key constraint wasn't properly removed and that caused this issue. I'll keep an eye out for if it happens again and report in detail at that time.

**Comment by xiesamgh** [comment] 2022-01-16 20:13
> @xiesamgh What you describe seems unlikely. Is this the initial migration, or a subsequent migration? Were there any errors and did the migration show in `__EFMigrationsHistory` table? See [#1593 (comment)](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1593#issuecomment-1012384412) for an example of a program you can try to reproduce the problem.

yes it's the initial migration and the __EFMigrationsHistory table shows the migration step. 
if I run 'dotnet ef database update', the table to AI. But if I call context.Database.Migrate(); The table doesn't have it. 
I asked in ef core communite, I was told it's MySQL provider issue. 

Packages I'm using:
<PackageReference Include="MySql.EntityFrameworkCore" Version="5.0.0" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="5.0.0" />

**Comment by lauxjpn** [comment] 2022-01-16 21:18
@xiesamgh I moved your issue to #1602, because it is likely to be unrelated to the others that have been discussed here.

/cc @mguinness @h5aaimtron

**Comment by lauxjpn** [comment] 2022-01-16 21:20
@h5aaimtron It's good to hear, that the issue is resolved in that instance that you are dealing with.

In that case, we will close this issue for now. Feel free to reopen it, should you have additional information for us.

**Closed by lauxjpn** 2022-01-16 21:20 UTC
Labels: needs-more-info
