### ISSUE TITLE
Database reverse engineering not working

### ISSUE THREAD

**Issue by fabs-rodriguez** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#255] opened 2017-04-10 14:54 UTC
Hi

I am trying to reverse engineer/scaffold a MySQL database in a .Net Core 1.1 / EF 1.1 Web Api from Visual Studio 2017.

In my *.csproj file, I have:

`<PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
`

and

`<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
`

I then run:

**dotnet ef dbcontext scaffold "Server=myserver.com;User Id=john;Password=12345;Database=db1" "Pomelo.EntityFrameworkCore.MySql"**

and it returns:

**Build succeeded.
    0 Warning(s)
    0 Error(s)
Time Elapsed 00:00:02.90**

But nothing happens. I would expect it to create a folder called "Models" and populate it with the models for the tables in the database? Is this not correct?

### Further technical details

MySQL Server version: 5.6.30
Operating system: Windows Server 2012 R2 (server), Windows 10 Creators Update (client)
Pomelo.EntityFrameworkCore.MySql version: 1.1.1
Visual Studio version: 2017 (Version 15.1 (26403.0) Release)

Here is the content of the full *.csproj file:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.1" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>
</Project>
```

**Comment by fabs-rodriguez** [comment] 2017-04-10 14:58
Here is the full *.csproj file:

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PackageTargetFallback>portable-net45+win8</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.1" />

    
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild3-final" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
  </ItemGroup>
</Project>

**Comment by mguinness** [comment] 2017-04-10 18:40
Dupe of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/152.  We suggest you search the existing issues before opening another.

**Closed** 2017-04-10 22:38 UTC

**Comment by fabs-rodriguez** [comment] 2017-04-11 06:32
Thanks for the link and the suggestion.

**Comment by malateshd720** [comment] 2018-02-19 09:13
can i get the source code link bcoz i have the same issue, scaffolding with mysql
