### ISSUE TITLE
Exception when querying foreign key data using lazy loading

### ISSUE THREAD

**Issue by 296370493** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1047] opened 2020-03-20 01:46 UTC
Project:[WebApplication1.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/4357644/WebApplication1.zip)

### The issue
```
Exception message:
    System.InvalidOperationException:“Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.”  
Stack trace:
   at MySql.Data.MySqlClient.MySqlCommand.set_CommandText(String value) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 150
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Load(INavigation navigation, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.Load()
   at Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(Object entity, String navigationName)
   at Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.SongProxy.get_SongLanguage()
   at WebApplication1.Controllers.HomeController.Index() in E:\source\repos\WebApplication1\WebApplication1\Controllers\HomeController.cs:line 28
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()
```

### Further technical details

MySQL version: 8.0.19
Operating system: Windows 10 （1909）
Pomelo.EntityFrameworkCore.MySql version:3.1.1
Microsoft.AspNetCore.App version:3.1.2

**Comment by mguinness** [comment] 2020-03-20 03:01
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/158#issuecomment-416593951

**Comment by 296370493** [comment] 2020-03-20 09:44
> 
> 
> See [#158 (comment)](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/158#issuecomment-416593951)

This project can run normally when ASP.NET Core 3.1.0, and an exception occurs after upgrading ASP.NET Core 3.1.2

**Comment by lauxjpn** [comment] 2020-03-20 22:32
Please post the code of the `HomeController.Index()` method.
This is likely a duplicate of #1041.

**Closed** 2020-03-20 22:43 UTC
Labels: closed-duplicate, closed-question, type-question
