### ISSUE TITLE
Could not find type mapping for column 'location' with data type 'point'. Skipping column.

### ISSUE THREAD

**Issue by franva** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#775] opened 2019-04-16 01:39 UTC
### Steps to reproduce

Here is my table:

CREATE TABLE `apartment` (
  `id` varchar(36) NOT NULL,
  `name` varchar(100) NOT NULL,
  `location` geometry DEFAULT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

### The issue

When I do scaffolding with this command:

>  dotnet ef dbcontext scaffold "server=localhost;port=3306;user=root;password=xxx;database=xxxx;TreatTinyAsBoolean=true;" "Pomelo.EntityFrameworkCore.MySql" -o Models -f

Here is the exception:

```
Exception message:
Could not find type mapping for column 'apartment.location' with data type 'geometry'. Skipping column.
```

### Further technical details

MySQL version: 8.0
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 2.2.0
Microsoft.AspNetCore.App version: 2.2.0

**Comment by mguinness** [comment] 2019-04-16 03:13
That'll likely need mappings added for the following types to `byte[]` in [MySqlTypeMappingSource](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Storage/Internal/MySqlTypeMappingSource.cs) class:

- geometry
- point
- linestring
- polygon
- multipoint
- multilinestring
- multipolygon
- geometrycollection

**Comment by franva** [comment] 2019-04-16 23:20
hi @mguinness  thanks for your response.
Sorry, do you mean the author of Pomelo EF MySql provider needs to do the work you said?

Or do I have to do the work you said?

If it was the 1st case, then are there any workarounds?

Thanks

**Comment by mguinness** [comment] 2019-04-17 00:23
It was meant for the community in general, so adding help wanted label for contributors.

**Comment by franva** [comment] 2019-04-17 02:22
hi @mguinness  I have written a mapping for Point. I was trying to push for Pull Request, but not allowed.

Can you please help

**Comment by caleblloyd** [comment] 2019-05-17 23:14
Duplicate of #488

**Closed by caleblloyd** 2019-05-17 23:14 UTC
Labels: help-wanted
