### ISSUE TITLE
Wrong code generated when using ValueConverters on MySQL

### ISSUE THREAD

**Issue by facundofarias** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#727] opened 2019-01-14 20:46 UTC
Describe what is not working as expected.

When using the ValueConversions described here: https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions, the code generated for MySQL is not correct and leads to an exception. If we remove the default value, then we are allowed to continue, so I think it should not be placed there ever since the beginning.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB, TEXT, GEOMETRY or JSON column 'Type' can't have a default value ---> MySql.Data.MySqlClient.MySqlException (0x80004005): BLOB, TEXT, GEOMETRY or JSON column 'Type' can't have a default value
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ResultSet.cs:line 42
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 74
   at MySql.Data.MySqlClient.MySqlDataReader.ReadFirstResultSetAsync(IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 299
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(MySqlCommand command, CommandBehavior behavior, ResultSetProtocol resultSetProtocol, IOBehavior ioBehavior) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 284
   at MySqlConnector.Core.TextCommandExecutor.ExecuteReaderAsync(String commandText, MySqlParameterCollection parameterCollection, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\TextCommandExecutor.cs:line 37
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 261
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 62
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
BLOB, TEXT, GEOMETRY or JSON column 'Type' can't have a default value
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

ValueConverter used:
```c#
            modelBuilder
                .Entity<SomeObject>()
                .Property(m => m.Type)
                .HasConversion(new EnumToStringConverter<SomeObjectType>());
);
```

Generated code:
```c#
            migrationBuilder.AddColumn<string>(
                name: "Type",
                table: "Memberships",
                nullable: false,
                defaultValue: ""
);
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Pomelo.EntityFrameworkCore.MySql
Operating system: macOS Mojave 10.14
IDE: Visual Studio for Mac 7.7.2 (build 21)

Originally posted here: https://github.com/aspnet/EntityFrameworkCore/issues/14360

**Comment by mguinness** [comment] 2019-01-14 23:35
Closing as duplicate of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/615.

**Closed** 2019-01-14 23:35 UTC
