### ISSUE TITLE
EF Core 3.1 migrationBuilder.RenameColumn generate a wrong sql for mysql5.7, it sames a bug of provider

### ISSUE THREAD

**Issue by byebyebt** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1042] opened 2020-03-16 06:29 UTC
### Steps to reproduce

I'm working on mysql5.7, use EF core3.1 with Pomelo.EntityFrameworkCore.MySql 3.1.0.
When I rename a column in model , and add migration to EF core context, efcore will create two operation：DropColumn and AddColumn. that's not my expectation.
So I delete those two operations and add a RenameColumn Operation, but it generate a sql like `alter table XXX rename column YYY to ZZZ` that can't pass in mysql 5.7("1064 - You have an error in your SQL syntax"),  

### The issue

I submit a [issue](https://github.com/dotnet/efcore/issues/20287) to EF core repository, and I'm told maybe it's a bug of provider.
Has anyone else had this problem? or it has nothing to do with the provider?

### Further technical details

MySQL version: 5.7.22
Operating system: win10
Pomelo.EntityFrameworkCore.MySql version: 3.1.0
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:
 EF Core version: 3.1.0
 IDE: Visual Studio 2019 16.4.6 community

**Comment by mguinness** [comment] 2020-03-16 16:51
Let's start with the basics.  Have you set the correct [configuration options](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options) for your environment in Startup class?

`mysqlOptions => { mysqlOptions.ServerVersion(new Version(5, 7, 22), ServerType.MySql); }`

**Comment by lauxjpn** [comment] 2020-03-17 16:11
This is very likely a duplicate of #1030, #1016 and #971.

**Comment by byebyebt** [comment] 2020-03-20 08:42
> Let's start with the basics. Have you set the correct [configuration options](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/wiki/Configuration-Options) for your environment in Startup class?
> 
> `mysqlOptions => { mysqlOptions.ServerVersion(new Version(5, 7, 22), ServerType.MySql); }`
Thanks a lot! I'm working on a app framework, that will process db operations.  I looked its code over, and found it did not set db version. I will communicate with the author to add it. 
On the other hand, RenameColumn is replaced by DropColumn and AddColumn , is that a bug or a intended operation for some reason?

**Comment by lauxjpn** [comment] 2020-03-20 22:28
> On the other hand, RenameColumn is replaced by DropColumn and AddColumn , is that a bug or a intended operation for some reason?

Take a look at #1030, where the same issues is being discussed.

In a nutshell, in most cases EF Core has no way to tell, whether you dropped an old and added a new column or you renamed a column. So migrations containing rename operations usually need to be modified by hand.

**Comment by byebyebt** [comment] 2020-03-21 02:05
thank you very much!

**Closed** 2020-03-21 02:21 UTC
Labels: closed-duplicate, closed-question, type-question
