### ISSUE TITLE
Table '__efmigrationshistory' doesn't exist

### ISSUE THREAD

**Issue by gravity00** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#68] opened 2016-09-29 16:55 UTC
I'm trying to use ASP.NET Core Identity with MySQL, but when updating the database using the tools I'm getting an error saying the table `__efmigrationshistory` doesn't exist.

If I don't use the migrations, but only the `ctx.Database.EnsureCreated();` it creates the database without any problem.

### Steps to reproduce

Sample code:

```csharp

namespace TestEFCoreMySql
{
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    using Microsoft.Extensions.Configuration;

    public static class Program
    {
        public static IConfigurationRoot ConfigurationRoot { get; }

        static Program()
        {
            var cfgBuilder = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json", false, true);

            ConfigurationRoot = cfgBuilder.Build();
        }

        public static void Main(string[] args)
        {
            Console.WriteLine("Application started...");
            try
            {
                MainAsync(args, CancellationToken.None).Wait();
            }
            catch (Exception e)
            {
                Console.WriteLine("An unhandled exception has occured");
                Console.WriteLine(e);
            }
            finally
            {
                Console.WriteLine("Application terminated. Press <enter> to exit...");
                Console.ReadLine();
            }
        }

        public static async Task MainAsync(string[] args, CancellationToken ct)
        {
            var testSecurityConnection =
                ConfigurationRoot.GetConnectionString("TestSecurityConnection");

            var optionsBuilder = new DbContextOptionsBuilder<TestSecurityContext>()
                .UseMySql(testSecurityConnection);
            using (var ctx = new TestSecurityContext(optionsBuilder.Options))
            {
                //  this works, but no ´__efmigrationshistory´ table is created
                ctx.Database.EnsureCreated();
            }
        }
    }

    public class TestSecurityUser : IdentityUser
    {
        
    }

    public class TestSecurityContext : IdentityDbContext<TestSecurityUser>
    {
        public TestSecurityContext(DbContextOptions options) : base(options)
        {
        }
    }

    public class TestSecurityContextFactory : IDbContextFactory<TestSecurityContext>
    {
        public TestSecurityContext Create(DbContextFactoryOptions options)
        {
            var testSecurityConnection =
                Program.ConfigurationRoot.GetConnectionString("TestSecurityConnection");

            var optionsBuilder = new DbContextOptionsBuilder<TestSecurityContext>()
                .UseMySql(testSecurityConnection);
            return new TestSecurityContext(optionsBuilder.Options);
        }
    }
}

```

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "copyToOutput": {
      "include": [
        "appsettings*.json"
      ]
    }
  },

  "tools": {
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },

  "dependencies": {
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.EntityFrameworkCore.Design": {
      "type": "build",
      "version": "1.0.0-preview2-final"
    },
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Pomelo.EntityFrameworkCore.MySql": "1.0.0"
  },

  "frameworks": {
    "net4.6.2": {}
  }
}
```

### The issue

When running the tools to migrate I get the missing table error

```powershell
dotnet ef migrations add Initial
dotnet ef database update
```

```
Pomelo.Data.MySql.MySqlException (0x80004005): Table 'test_security.__efmigrationshistory' doesn't exist
   at Pomelo.Data.MySql.MySqlStream.ReadPacket()
   at Pomelo.Data.MySql.NativeDriver.GetResult(Int64& affectedRow, Int64& insertedId)
   at Pomelo.Data.MySql.Driver.NextResult(Int32 statementId, Boolean force)
   at Pomelo.Data.MySql.MySqlDataReader.NextResult()
   at Pomelo.Data.MySql.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
Table 'test_security.__efmigrationshistory' doesn't exist
```

### Further technical details

MySQL version: 5.7.15
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 1.0.0

**Comment by Kagamine** [comment] 2016-09-30 00:14
Dupe of #66

**Closed by Kagamine** 2016-09-30 00:14 UTC

**Comment by gravity00** [comment] 2016-09-30 11:02
@Kagamine so to be able to use the tools for the first time, you are telling me I must manually create the `__efmigrationshistory` table?

**Comment by kroniak** [comment] 2016-10-24 15:34
@gravity00 me too misundestanding.

It does not apply any migrations to new fresh db.

**Comment by kroniak** [comment] 2016-10-26 10:06
@Kagamine please comment, need to create this table manually?

**Comment by Kagamine** [comment] 2016-10-26 10:44
If you have used EnsureCreated(), you must drop your database and use DbContext.Migrate() instead of EnsureCreated()

**Comment by kroniak** [comment] 2016-10-26 10:47
@Kagamine I dont use EnsureCreated, I use DbContext.Migrate() for first time (emty db) and later migrations.

**Comment by Kagamine** [comment] 2016-10-26 14:20
Could you show me your startup.cs?

**Comment by kroniak** [comment] 2016-11-17 06:29
@Kagamine 

```c#
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
//...
InitDatabase(app, logger);
//...
}

private static void InitDatabase(IApplicationBuilder app, ILogger logger)
		{
			using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>()
				.CreateScope())
			{
				logger.LogWarning("Turn on databases....");

				var database = serviceScope.ServiceProvider.GetService<ApplicationDbContext>();
				
				
				database.Database.Migrate();

				var userManager = app.ApplicationServices.GetService<UserManager<ApplicationUser>>();
				var roleManager = app.ApplicationServices.GetService<RoleManager<IdentityRole>>();

				var adminUser = Configuration["ADMIN_USER"];
				var adminPassword = Configuration["ADMIN_PASSWORD"];

				serviceScope.ServiceProvider.GetService<ApplicationDbContext>()
					.EnsureSeedData(userManager, roleManager, adminUser, adminPassword);
			}
		}
```

**Comment by Kagamine** [comment] 2016-11-17 10:48
Could you try to remove creating service scope?

**Comment by kroniak** [comment] 2016-11-17 11:11
@Kagamine Why?

When I try run 

```
dotnet ef mirations add...
dotnet ef database update
```
I have some error about migration table if it doesnt exist in database.

**Comment by kroniak** [comment] 2016-11-17 11:24
@Kagamine I can inject ApplicationDbContext to Configure and run database.Database.Migrate();
But I will get error too.

With Postrgres\SQLServer provider I never have this case. __EFMigrationsHistory was created automatically.

**Comment by Kagamine** [comment] 2016-11-17 11:29
Sorry, I could not reproduce your issue, In my machine all things works ok.

**Comment by kroniak** [comment] 2016-11-17 12:06
Please https://github.com/kroniak/temp-pomeloapp
This is vs 2015 webtemplate.

I use mysql on local docker with empty "test" db.

To reproduce

```
dotnet restore
dotnet ef migrations add var1
dotnet ef database update
```

Error:

```
E:\workspaces\_testlab\temp-pomeloapp\src\WebApplication1>dotnet ef database update
Project WebApplication1 (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.
                       MySql.Data.MySqlClient.MySqlException: Table 'test.__EFMigrationsHistory' doesn't exist
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadResultSetHeaderAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteReaderAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Table 'test.__EFMigrationsHistory' doesn't exist
```

**Comment by Kagamine** [comment] 2016-11-23 01:36
@kroniak Sorry, I have run your application. All things are ok.

My machine:

- Windows 10
- .NET Core 1.1
- Pomelo 1.1.0-rtm-10000
- MySQL 5.7.16

![image](https://cloud.githubusercontent.com/assets/2216750/20548653/44a6396e-b160-11e6-9bc0-9fb391adaec1.png)

![image](https://cloud.githubusercontent.com/assets/2216750/20548650/3d940b1a-b160-11e6-9240-b2ea19bb3b1b.png)

**Comment by Kagamine** [comment] 2016-11-23 01:37
![image](https://cloud.githubusercontent.com/assets/2216750/20548663/55bf9fd8-b160-11e6-9afb-68469d404be6.png)

![image](https://cloud.githubusercontent.com/assets/2216750/20548674/66daf02e-b160-11e6-96d0-037dcfb664d8.png)

**Comment by kroniak** [comment] 2016-11-23 10:59
@Kagamine wow. I dont know what happend. What do you think, how I can debug my problem?

**Comment by Kagamine** [comment] 2016-11-23 11:54
I'd like to know which charset are you using?

**Comment by kroniak** [comment] 2016-11-23 12:22
@Kagamine mysql starts with this settings:

--character-set-server=utf8 --collation-server=utf8_unicode_ci

**Comment by Kagamine** [comment] 2016-11-23 12:24
1. Drop your database
2. Remove all files from Migrations
3. Execute `dotnet ef migrations add Init`
4. Execute `dotnet ef database update`

If still not works, please install MySQL in your real machine(not docker).

**Comment by stuartleeks** [comment] 2017-03-09 10:44
@kroniak did you resolve this? I'm trying to run migrations against a MySQL instance in docker and getting the same exception that the __EFMigrationsHistory table doesn't exist

**Comment by kroniak** [comment] 2017-03-09 10:46
@stuartleeks no, I didnt. I have same exception in docker host.

**Comment by caleblloyd** [comment] 2017-03-12 15:56
I'm pretty sure this happens when you have created the database (e.g. `CREATE DATABSE db_name`) already.  If that's the case, you need to manually add the `__EFMigrationsHistory` table.

@Kagamine maybe we should add a check for the `__EFMigrationsHistory` table upon running migrations and add if it does not exist?

**Comment by stuartleeks** [comment] 2017-03-12 21:18
@caleblloyd - yes, when I changed the `docker run` options so that it no longer created the database I didn't get this issue. FWIW, I don't get this with SQL Server migrations if the table exists, so the proposed check for `__EFMigrationsHistory` table and creating it if necessary sounds good to me :-)

**Comment by caleblloyd** [comment] 2017-03-12 21:25
I'm writing a test for this right now and it appears to be fixed upstream. Works on a blank database in the latest `1.1.1-prerelease`

**Comment by stuartleeks** [comment] 2017-03-12 21:26
Ok, I'll give that a try :-)

**Comment by caleblloyd** [comment] 2017-03-13 00:37
Test case that covers this is now at [TestMigrateCommand.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Commands/TestMigrateCommand.cs)

Passing in CI on MySql 5.7 and passing locally against MySql 5.5
