### ISSUE TITLE
SQL script always alter database charset to utf8mb4

### ISSUE THREAD

**Issue by benjamincotrel** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1426] opened 2021-05-14 13:34 UTC
Hi, I'm using EF Core 5 and since the 5.0 update, when I use code-first ef core migration to generate a SQL script, even if my migration code file only contains a `.AddColumn` instruction, the generated SQL file always starts with `﻿ALTER DATABASE CHARACTER SET utf8mb4;`

I tried specifying `.HasCharset("latin1")` but it doesn't remove this statement. (it only adds a migration procedure with an `ALTER DATABASE CHARACTER SET latin1`, which means a future migration would revert the charset to utf8mb4.

This statement isn't event wrapped in a procedure, it's the first line of the SQL script.

The beginning of the script looks like this:

```
ALTER DATABASE CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET utf8mb4;

START TRANSACTION;
```

**Comment by lauxjpn** [comment] 2021-05-14 14:59
@benjamincotrel Please post the model definition (containing the `.HasCharset("latin1")` call you mentioned), so we can take a look at it.

**Comment by lauxjpn** [comment] 2021-05-14 17:03
I can reproduce this in a vanilla project.

> I tried specifying `.HasCharset("latin1")` but it doesn't remove this statement. (it only adds a migration procedure with an `ALTER DATABASE CHARACTER SET latin1`, which means a future migration would revert the charset to utf8mb4.

A fix for this might take a couple of days. In the meanwhile, just specify the charset on the model/database level explicitly via `HasCharSet("latin1")` and keep the `ALTER DATABASE CHARACTER SET latin1;` statement, as it does what you want.

In your case, this just adds an unnecessary statement (the `ALTER DATABASE CHARACTER SET utf8mb4;` statement), that should not do any harm.

A future migration does not revert your charset (as long as you keep the `HasCharSet()` call in your model definition), as can be tested with the following sample code:

<details>
<summary>Program.cs</summary>

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public int IceCreamId { get; set; }
        public string Name { get; set; }
        // public int Kilojoule { get; set; } // <-- add for second migration
    }
    
    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                var connectionString = "server=127.0.0.1;port=3306;user=root;password=;database=Issue1426";
                var serverVersion = ServerVersion.AutoDetect(connectionString); 
                optionsBuilder.UseMySql(
                        connectionString,
                        serverVersion)
                    .UseLoggerFactory(
                        LoggerFactory.Create(
                            configure => configure
                                .AddConsole()
                                .AddFilter(level => level >= LogLevel.Information)))
                    .EnableSensitiveDataLogging()
                    .EnableDetailedErrors();
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasCharSet("latin1");
            
            modelBuilder.Entity<IceCream>()
                .HasData(
                    new IceCream {IceCreamId = 1, Name = "Vanilla"});
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();
        }
    }
}
```

</details>

Activating the commented line before adding the second migration and then creating a script leads to the following full SQL script for all migrations:

<details>
<summary>Migration script (SQL)</summary>

```sql
ALTER DATABASE CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `__EFMigrationsHistory` (
    `MigrationId` varchar(150) CHARACTER SET utf8mb4 NOT NULL,
    `ProductVersion` varchar(32) CHARACTER SET utf8mb4 NOT NULL,
    CONSTRAINT `PK___EFMigrationsHistory` PRIMARY KEY (`MigrationId`)
) CHARACTER SET utf8mb4;

START TRANSACTION;  /* <-- first migration starting */

ALTER DATABASE CHARACTER SET latin1; /* <-- the HasCharSet("latin1") call */

CREATE TABLE `IceCreams` (
    `IceCreamId` int NOT NULL AUTO_INCREMENT,
    `Name` longtext CHARACTER SET latin1 NULL,
    CONSTRAINT `PK_IceCreams` PRIMARY KEY (`IceCreamId`)
) CHARACTER SET latin1;

INSERT INTO `IceCreams` (`IceCreamId`, `Name`)
VALUES (1, 'Vanilla');

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210514164851_Initial', '5.0.5');

COMMIT;

START TRANSACTION;  /* <-- second migration starting */

ALTER TABLE `IceCreams` ADD `Kilojoule` int NOT NULL DEFAULT 0;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20210514165055_NewColumn', '5.0.5');

COMMIT;  /* <-- the HasCharSet("latin1") call is still in effect here; the database charset is still latin1 */
```

</details>

In addition to setting the database charset, the `HasCharSet("latin1")` call (without the second parameter) will explicitly apply `latin1` to all future tables and their columns as well (even if for some reason the database would have setup a different default charset at that time), as long as they are added changed through Pomelo (which is the case for your migrations).

**Comment by benjamincotrel** [comment] 2021-05-14 17:28
Thank you very much for this quick answer, I'll use this workaround until the fix is live.

**Comment by lauxjpn** [comment] 2021-05-14 18:04
A couple of notes for me for later:
* Check whether we can take an optional dependency on the model in the database creator, so we can immediately set the expected charset instead of the default.
* The `__EFMigrationsHistory` table is currently effected by whatever the database is initialized with (which currently is always `utf8mb4)`, and won't change later if the database charset is changed (unless we would include it explicitly), because it is not part of the users model. So keeping `utf8mb4` as the default for this special table does make a lot of sense.
* What is the actual impact of the current behavior? Is there a scenario, where this actually matters? Explicitly check, how idempotent migrations are affected, and whether the initial ALTER DATABASE statement would also run, if only the latest migration would be executed.

**Comment by me-viper** [comment] 2021-06-14 12:33
> In your case, this just adds an unnecessary statement (the `ALTER DATABASE CHARACTER SET utf8mb4;` statement), that should not do any harm.

In our case this breaks migrations for new databases.
We've got a migration that creates table with bunch of varchar(4000) columns. That was fine since database charset expected to be latin1. But because charset is set to "utf8mb4" initially it fails now with:

```
Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. 
This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
``` 

modelBuilder.HasCharSet("latin1") won't help because it will add new migration after failing migration.

**Comment by lauxjpn** [comment] 2021-06-14 13:10
> modelBuilder.HasCharSet("latin1") won't help because it will add new migration after failing migration.

@me-viper The following should work:

1. First, only add the `modelBuilder.HasCharSet("latin1")` (or `modelBuilder.HasCharSet("latin1", DelegationModes.ApplyToDatabases)`) call to your model configuration.
2. Then create a migration.
3. Then add your actual changes to your model configuration.
4. Then add a migration for your actual changes.

**Closed** 2021-06-19 11:51 UTC
Labels: type-bug
