### ISSUE TITLE
Unresolved references

### ISSUE THREAD

**Issue by KevinBurton** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1343] opened 2021-03-09 02:49 UTC
Where do I pull these unresolved methods and fields?

![image](https://user-images.githubusercontent.com/2643566/110411146-a8efed80-804f-11eb-8047-19abc4f5fb55.png)

### Further technical details

Operating system:  Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1.2
Microsoft.AspNetCore.App version: 3.1.2

Other details about my project setup:

**Comment by mguinness** [comment] 2021-03-09 03:46
Duplicate of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1333

**Closed by mguinness** 2021-03-09 03:46 UTC

**Comment by lauxjpn** [comment] 2021-03-09 06:37
@KevinBurton The `master` branch is the default that is being displayed on our repo and it is the most recent one (targeting EF Core 5.0).
If you want to use Pomelo `3.1.2` (why not at least use `3.2.4`?), then you should switch to the `3.1-maint` branch, to display the related instructions.
