### ISSUE TITLE
Scaffolding not working with netcore 1.1 - Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation,...

### ISSUE THREAD

**Issue by ydekova** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#263] opened 2017-04-25 12:44 UTC
Just upgraded to the latest dot net core version as well as VS2017.
Created a simple netcoreapp class library and added 
Pomelo.EntityFrameworkCore.MySql
Pomelo.EntityFrameworkCore.MySql.Design

here is what my csproj file looks like:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.2-preview-10038" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2-preview-10038" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

</Project>
```

When I try to scaffold the model from existing DB I'm getting this error 

System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Extensions.Logging.Console.ConsoleLogger..ctor(String name, Func`3 filter, Boolean includeScopes)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Logging.Logger..ctor(LoggerFactory loggerFactory, String name)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory..ctor(ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Technical details

MySQL version: '5.7.17-log'
Operating system: win10-64bit
Pomelo.EntityFrameworkCore.MySql version: whichever i use

Tried to include System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0 in the project but then I am getting the same error, only for version 4.0.0.0

**Comment by spmorgan** [comment] 2017-05-09 01:39
Did you ever solve this problem?  I'm having the same issue but on mac.

**Comment by ydekova** [comment] 2017-05-09 12:25
Nope. I changed my model manually for now. I hope we can get more information on this soon.

**Comment by dknoodle** [comment] 2017-05-24 02:48
I am having the same issue.  I've been going around in circles for hours on this.  Any help from the development team please?

**Comment by dcbrewster** [comment] 2017-05-31 16:45
Still having this problem. Anyone even looking at it?

**Comment by caleblloyd** [comment] 2017-05-31 17:03
The information posted is not enough for a recreate. For scaffolding issues we need a mysqldump of the schema.

We have a scaffolding test that runs in CI so any issues outside of that we need as much info as possible.

**Comment by dcbrewster** [comment] 2017-05-31 19:27
@caleblloyd I have attached a sample database
[mySQL-TestDB.sql.txt](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/1042676/mySQL-TestDB.sql.txt)

As an outsider, I don't think the error message has anything to do with the structure of the DB.
Anything else, please let me know.

Thanks. Dave

Error Message:

C:\Users\Dave\Downloads>cd C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel

C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel>dotnet ef dbcontext scaffold -o Models "server=localhost;userid=football;password=appfootball463;database=football;" Pomelo.EntityFrameworkCore.MySql

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.08
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Extensions.Logging.Console.ConsoleLogger..ctor(String name, Func`3 filter, Boolean includeScopes)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Logging.Logger..ctor(LoggerFactory loggerFactory, String name)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory..ctor(ILoggerFactory loggerFactory)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by caleblloyd** [comment] 2017-05-31 22:12
I'll try to take a look at it over the next week or so. I agree that the error looks more specific to platform or configuration rather than an issue with the code or schema.

**Comment by mguinness** [comment] 2017-05-31 22:19
@dcbrewster Scaffolding worked fine against the database you had provided, see [Models.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/1043069/Models.zip).

The following was the output from the scaffold command, those columns were ignored in output:

```
warn: Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory[6]
      Could not find type mapping for column 'schedule.GameDate' with data type 'date'. Skipping column.
warn: Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory[6]
      Could not find type mapping for column 'weekcontrol.FirstDay' with data type 'date'. Skipping column.
warn: Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory[6]
      Could not find type mapping for column 'weekcontrol.LastDay' with data type 'date'. Skipping column.
warn: Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory[6]
      Could not find type mapping for column 'weekcontrol.CloseDate' with data type 'date'. Skipping column.
```

Below are references used in .csproj file for a fresh VS 2017 project:

```
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="1.1.2" />
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.1" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.0" />
```

P.S. It appears that you have sensitive information in your database dump, so it may be prudent to remove it - we only needed schema, not data.

**Comment by dcbrewster** [comment] 2017-06-01 18:14
@mguinness. Thanks for your help. I'm making progress but still not there.
I created the ItemGroup as suggested.
I found I also needed to create another ItemGroup:
```
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.1" />
  </ItemGroup>
```

Problem now is the dotnet ef command always hangs. Restore and dotnet command results below. Any suggestions?

Dave

Executed a restore, worked fine:
`C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel>dotnet restore`
  Restoring packages for C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj...
  Restoring packages for C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj...
  Generating MSBuild file C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\FootballDataModel.csproj.nuget.g.props.
  Writing lock file to disk. Path: C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\project.assets.json
  Restore completed in 2.28 sec for C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj.
  Restore completed in 3.53 sec for C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj.

  NuGet Config files used:
      C:\Users\Dave\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Executed dotnet ef but it always hangs. The build part seems to work fine...then stops.
`C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel>dotnet ef dbcontext scaffold -o Models "server=localhost;userid=xxx;password=xxx;database=football;" Pomelo.EntityFrameworkCore.MySql -c "FootballContext" -f --verbose`
Using project 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj'.
Using startup project 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj'.
Writing 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\FootballDataModel.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Dave\AppData\Local\Temp\tmp3CAF.tmp /verbosity:quiet /nologo "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj"
Writing 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\FootballDataModel.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Dave\AppData\Local\Temp\tmp4125.tmp /verbosity:quiet /nologo "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj"
dotnet build "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj" /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.94
dotnet exec --depsfile "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\Football.DataModel.deps.json" --additionalprobingpath C:\Users\Dave\.nuget\packages --fx-version 1.1.2 C:\Users\Dave\.nuget\packages\microsoft.entityframeworkcore.tools.dotnet\1.0.1\tools\netcoreapp1.0\ef.dll dbcontext scaffold -o Models server=localhost;userid=football;password=appfootball463;database=football; Pomelo.EntityFrameworkCore.MySql -c FootballContext -f --assembly "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\Football.DataModel.dll" --startup-assembly "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\Football.DataModel.dll" --project-dir "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\\" --content-root "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\\" --data-dir "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\\" --verbose --root-namespace Football.DataModel
Using assembly 'Football.DataModel'.
Using startup assembly 'Football.DataModel'.
Using application base 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1'.
Using content root 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\'.
Using root namespace 'Football.DataModel'.
Using project directory 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\'.
Using data directory 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\'.

**Comment by mguinness** [comment] 2017-06-01 23:48
@caleblloyd I noticed something odd when running a packet capture during a scaffold.  Two connections are opened to MySQL.  The first interrogates the database schema, but afterwards another connection is created which doesn't appear to do anything.  Can you shed any light why the latter connection occurs?

**Comment by caleblloyd** [comment] 2017-06-02 00:40
I couldn't know for sure without adding some logging in the codebase, but it's possible that it is the version detection connection that determines server capabilities from here: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/Pomelo.EntityFrameworkCore.MySql/Storage/Internal/MySqlConnectionSettings.cs#L38

**Comment by mguinness** [comment] 2017-06-02 18:22
@dcbrewster Can you try running your scaffold again.  If it appears to have hung, say after 5 mins, can you try to stop the MySQL daemon and see if the scaffold completes?

**Comment by dcbrewster** [comment] 2017-06-02 19:00
@mguinness
Ran test as requested.
scaffold immediately exited with "MySqlSession is not connected."
The "Models" sub-directory was not created.
I reran test again with "Models" sub-directory already created - same results.

C:\Dave\Downloads>cd C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel

C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel>dotnet restore
  Restoring packages for C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj...
  Restoring packages for C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj...
  Restore completed in 5.07 sec for C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj.
  Generating MSBuild file C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\FootballDataModel.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\FootballDataModel.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\project.assets.json
  Restore completed in 12.15 sec for C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj.

  NuGet Config files used:
      C:\Users\Dave\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config

  Feeds used:
      https://api.nuget.org/v3/index.json
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel>dotnet ef dbcontext scaffold -o Models "server=localhost;userid=football;password=appfootball463;database=football;" "Pomelo.EntityFrameworkCore.MySql" -c "FootballContext" -f --verbose
Using project 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj'.
Using startup project 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj'.
Writing 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\FootballDataModel.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Dave\AppData\Local\Temp\tmp2F2B.tmp /verbosity:quiet /nologo "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj"
Writing 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\obj\FootballDataModel.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\Dave\AppData\Local\Temp\tmp3372.tmp /verbosity:quiet /nologo "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj"
dotnet build "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\FootballDataModel.csproj" /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.48
dotnet exec --depsfile "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\Football.DataModel.deps.json" --additionalprobingpath C:\Users\Dave\.nuget\packages --fx-version 1.1.2 C:\Users\Dave\.nuget\packages\microsoft.entityframeworkcore.tools.dotnet\1.0.1\tools\netcoreapp1.0\ef.dll dbcontext scaffold -o Models server=localhost;userid=football;password=appfootball463;database=football; Pomelo.EntityFrameworkCore.MySql -c FootballContext -f --assembly "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\Football.DataModel.dll" --startup-assembly "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\Football.DataModel.dll" --project-dir "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\\" --content-root "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\\" --data-dir "C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\\" --verbose --root-namespace Football.DataModel
Using assembly 'Football.DataModel'.
Using startup assembly 'Football.DataModel'.
Using application base 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1'.
Using content root 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\'.
Using root namespace 'Football.DataModel'.
Using project directory 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\'.
Using data directory 'C:\Users\Dave\Documents\Visual Studio 2017\Projects\Football\FootballDataModel\bin\Debug\netcoreapp1.1\'.
**System.InvalidOperationException: MySqlSession is not connected.**
   at MySql.Data.Serialization.MySqlSession.VerifyConnected()
   at MySql.Data.Serialization.MySqlSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.Serialization.MySqlSession.TryAsyncContinuation(Task`1 task)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<>c__DisplayClass8_0.<<ScanRowAsync>g__ScanRowAsyncAwaited0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadEntireAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<NextResultAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.DoClose()
   at MySql.Data.MySqlClient.MySqlDataReader.Dispose(Boolean disposing)
   at MySql.Data.MySqlClient.MySqlConnection.CloseDatabase()
   at MySql.Data.MySqlClient.MySqlConnection.DoClose()
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(DbConnection connection, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlDatabaseModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.RelationalScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.MySqlScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GetMetadataModel(ReverseEngineeringConfiguration configuration)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineeringGenerator.GenerateAsync(ReverseEngineeringConfiguration configuration, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContextAsync(String provider, String connectionString, String outputDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, Boolean useDataAnnotations, Boolean overwriteFiles, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.<ScaffoldContextImpl>d__22.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
**MySqlSession is not connected.**

**Comment by mguinness** [comment] 2017-06-02 19:06
@dcbrewster Did you stop the MySQL daemon before running scaffold?  I meant to keep it running and if the scaffold process had not completed after 5 mins, then stop the MySQL daemon and see what the scaffold process returns.

**Comment by dcbrewster** [comment] 2017-06-02 19:32
@mguinness 
Test was run as requested. Turned off mysql after 5 minutes.
Ran 15 minute test - same results.
Task manager shows 0% CPU activity on mysqld.exe process (At least I didn't see any).

**Comment by dcbrewster** [comment] 2017-06-02 20:02
@mguinness. Ran scaffold for one table (Player) and it worked.
Will process through other tables to see if I can find a problem table.

**Comment by dcbrewster** [comment] 2017-06-02 20:36
@mguinness .
Ran test scaffolding each table separately. Each completed, but those with Foreign Keys gave warning.
MySQL Workbench, changes table names to all lower case on Foreign Keys. Scaffold warn: Referenced table 'division' is not in dictionary because table name is "Division".

The warning was shown for every foreign key in every table.
Curious, but probably not source of this problem.

**Comment by mguinness** [comment] 2017-06-02 20:55
Can you try running [CodeTrack](http://www.getcodetrack.com/) profiler?  Follow [instructions](http://www.getcodetrack.com/howto_profilecore.html) to profile the scaffold process.  You will need to use manual mode as shown below:

![image](https://cloud.githubusercontent.com/assets/14002844/26744361/7712fa9c-479a-11e7-8f31-8a33724531a5.png)

On the final screen check "Trace Child Processes".  Send us the trace file to see if it might provide some clues.

**Comment by dcbrewster** [comment] 2017-06-02 20:58
Correction. One table did hang.
Original table name "Player_Pool". This links player to multiple pools. 1 to Many).
Workbench table create statement:
CREATE TABLE `player_pool` (
  `RecordID` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Record ID',
  `PlayerID` int(11) NOT NULL COMMENT 'PlayerID from player table',
  `PoolID` int(11) NOT NULL COMMENT 'PoolID from pool table',
  `UserLevel` int(11) NOT NULL DEFAULT '0' COMMENT 'User Level For This Pool',
  `DateAdded` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'Date of Record Creation',
  `AddedBy` varchar(45) NOT NULL DEFAULT 'Unknown' COMMENT 'User who created record',
  `DateModified` datetime DEFAULT '0000-00-00 00:00:00' COMMENT 'Date of Last Modification',
  `ModifiedBy` varchar(45) DEFAULT NULL COMMENT 'User who made last modification',
  PRIMARY KEY (`RecordID`),
  UNIQUE KEY `RecordID_UNIQUE` (`RecordID`),
  KEY `PlayerID_idx` (`PlayerID`),
  KEY `PoolID_idx` (`PoolID`),
  CONSTRAINT `PlayerID` FOREIGN KEY (`PlayerID`) REFERENCES `player` (`PlayerID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `PoolID` FOREIGN KEY (`PoolID`) REFERENCES `pool` (`PoolID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8 COMMENT='Link player to pool''s. Player can be in muliple pools.';

**Comment by dcbrewster** [comment] 2017-06-03 18:11
@mguinness Zipped trace file attached.

**Comment by dcbrewster** [comment] 2017-06-03 18:23
@mguinness  Zipped File attached.
[Trace.ZIP.txt](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/1049787/Trace.ZIP.txt)

**Comment by mguinness** [comment] 2017-06-04 02:46
Thanks, but I don't see any code from this library - did you check "Trace Child Processes"?

**Comment by dcbrewster** [comment] 2017-06-04 20:46
@mguinness  I checked the session parameters, and yes Trace Child Processes was turned on. As far as I could see, Codetrack only shows 4 instances of dotnet and they seem to stall right away.

**Comment by mguinness** [comment] 2017-06-05 17:46
Based on that trace, it's not even hitting Pomelo.EntityFramework.MySql so it would indicate an issue with tooling.  It also appears to be hitting [HandleUnexpectedArg](https://github.com/dotnet/cli/blob/master/src/dotnet/CommandLine/CommandLineApplication.cs#L582) which is a red flag.

**Comment by mguinness** [comment] 2017-06-13 18:09
Unable to reproduce therefore closing issue.

**Closed by mguinness** 2017-06-13 18:09 UTC
