### ISSUE TITLE
Using SizeLimit with MemoryCache cause queries to fail

### ISSUE THREAD

**Issue by sanishmistry** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#556] opened 2018-05-27 18:47 UTC
### Steps to reproduce

Use MemoryCache with ASP.NET Core in Startup.cs

            services.AddMemoryCache(o => {
                o.SizeLimit = 5000;
                
            });

Then do a query

        public IActionResult Test([FromServices] AppDbContext db)
        {
            var x = db.PostCodes.Where(p => p.Value == "XXXX").ToList();
    ...
        }

### The issue

You get an exception like this 

                    An unhandled exception has occurred while executing the request
            System.InvalidOperationException: Cache entry must specify a value for Size when SizeLimit is set.
                at Microsoft.Extensions.Caching.Memory.MemoryCache.SetEntry(CacheEntry entry)
                at Microsoft.Extensions.Caching.Memory.CacheEntry.Dispose()
                at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object 
            key, TItem value)
                at 
            Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc] 
            (Object cacheKey, Func`1 compiler)
                at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
                at Remotion.Linq.QueryableBase`1.GetEnumerator()
                at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
                at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

### Further technical details

MySQL version:  5.7.22-0ubuntu0.16.04.1 - (Ubuntu)
Operating system:  Ubuntu 16.04.4 LTS
Pomelo.EntityFrameworkCore.MySql version: 2.0.1

**Comment by mguinness** [comment] 2018-05-29 19:40
Dupe of https://github.com/aspnet/EntityFrameworkCore/issues/12157.

**Closed by mguinness** 2018-05-29 19:40 UTC
