### ISSUE TITLE
Latest version of MySqlConnector v1.0.0 Breaking Change namespace causes Pomelo to throw exception

### ISSUE THREAD

**Issue by baronics** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1130] opened 2020-07-22 15:11 UTC
### Steps to reproduce
Upgrade MySqlConnector from 0.69.8 to 1.0.0

### The issue
Line:    .UseMySql("Server=localhost;Database=ef;User=root;Password=1234;", mySqlOptions => mySqlOptions
           .ServerVersion(new Version(8, 0, 20), ServerType.MySql)
 generates exception

Code inside Pomelo library has "using MySql.Data.MySqlClient;" which no longer exists in MySqlConnector

```
Exception message: Could not load type 'MySql.Data.MySqlClient.MySqlConnectionStringBuilder' from assembly 'MySqlConnector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'.
Stack trace:
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 mySqlOptionsAction)
   at Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions.UseMySql[TContext](DbContextOptionsBuilder`1 optionsBuilder, String connectionString, Action`1 mySqlOptionsAction)

```

### Further technical details

MySQL version: 8.0.20
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1.6

**Comment by lauxjpn** [comment] 2020-07-22 15:24
This is a duplicate of #1126, but thanks for reminding me. I just merged #1127, that will restrict the supported version for MySqlConnector to <1.0.0.
Should be on NuGet as version `3.1.2` within an hour.

**Closed** 2020-07-22 15:25 UTC
Labels: closed-duplicate, type-bug
