### ISSUE TITLE
Scaffold-DbContext tool BIT -> ulong

### ISSUE THREAD

**Issue by jpuebla** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#946] opened 2019-11-18 20:14 UTC
I Tried new final release 3.0.0.0
When I use Scaffold-DbContext tool wirh MariaDb 10.3 all fileds BIT(1) are converted to ulong

It should be converted to bool

MariaDb 10.4: 
Windows 10
Pomelo.EntityFrameworkCore.MySql version: 3.0.0.0
Microsoft.AspNetCore.App version: 3.0

**Comment by lauxjpn** [comment] 2019-11-18 20:15
This is a duplicate of #917.

**Closed by lauxjpn** 2019-11-18 20:15 UTC
Labels: closed-duplicate
