### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by yoyos** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#298] opened 2017-06-26 13:36 UTC
### Steps to reproduce

- Create new ASPNETCORE 1.1 web project in visual studio with Basic User Authentication enabled.
- Add Pomelo.EntityFrameworkCore.MySQL nuget package and change your startup.cs to use MySQL it
- Update-Database.
- Error is shown.

### The issue

It seems, the error 'Specified key was too long; max key length is 767 bytes' is occurring when Migration Tool try to create those index.
When I comment those lines in the first migration, everything works.

            migrationBuilder.CreateIndex(
                name: "UserNameIndex",
                table: "AspNetUsers",
                column: "NormalizedUserName",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "RoleNameIndex",
                table: "AspNetRoles",
                column: "NormalizedName",
                unique: true);
                
            migrationBuilder.CreateIndex(
                name: "IX_AspNetRoleClaims_RoleId",
                table: "AspNetRoleClaims",
                column: "RoleId");
                
            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserClaims_UserId",
                table: "AspNetUserClaims",
                column: "UserId");

            migrationBuilder.CreateIndex(
                name: "IX_AspNetUserLogins_UserId",
                table: "AspNetUserLogins",
                column: "UserId");

### Full error

```
MySql.Data.MySqlClient.MySqlException: Specified key was too long; max key length is 767 bytes
   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet(ResultSet resultSet)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteNonQueryAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Specified key was too long; max key length is 767 bytes
PM> 
```

### Further technical details

MySQL version: 5.6
Operating system: Windows 10, Visual Studio 2017
Pomelo.EntityFrameworkCore.MySql version: 1.2

### My Tries

I tried to update mysql, nothing changed.
I tried to remove all migrations and create first migration again, nothing changed.
I saw this issue https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/81 but I didn't understand how to resolve my issue
MySQL has default settings and I just created the aspnetcore project without coding anything. It should work out of the box I think.

Have something in mind ? :)

**Comment by caleblloyd** [comment] 2017-06-26 14:11
Duplicate of #81 and #136 

Look at this code for a sample of how to fix: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/e18175f3585969c15de3838c8d0967c9bf5e7afc/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppDb.cs#L82-L111

**Closed by caleblloyd** 2017-06-26 14:11 UTC

**Comment by yoyos** [comment] 2017-06-26 14:50
Ok, didn't understand how it worked.
After changes, I need to recreate the migrations ...
Now everything works. Thanks !

**Comment by hokumus** [comment] 2020-11-18 23:00
if you want quickly solution, run below script on the management tool.

[Script Link](https://gist.githubusercontent.com/jambelnet/1ea70236c933d644b36895b296fb44e5/raw/cd272b586d47e9229dee93fdf691e9a54b5ae105/ASP.NET%2520Core%2520Identity%2520script%2520for%2520MySql)

**Comment by lauxjpn** [comment] 2020-11-19 03:14
> if you want quickly solution, run below script on the management tool.
> 
> [Script Link](https://gist.githubusercontent.com/jambelnet/1ea70236c933d644b36895b296fb44e5/raw/cd272b586d47e9229dee93fdf691e9a54b5ae105/ASP.NET%2520Core%2520Identity%2520script%2520for%2520MySql)

See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/81#issuecomment-730099233 for my recommendation nowadays.
