### ISSUE TITLE
Specialize encode and engine during creating tables by ef migration

### ISSUE THREAD

**Issue by mykge** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#217] opened 2017-03-17 09:12 UTC
The generated SQL statement can not be specified encode  and engine

**Comment by Kagamine** [comment] 2017-03-17 09:36
Dupe of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/84

**Closed** 2017-03-17 09:36 UTC
Labels: closed-duplicate
