### ISSUE TITLE
Query: invalid query generated for some cases requiring cast to certain types (e.g. double)

### ISSUE THREAD

**Issue by maumar** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#571] opened 2018-05-30 23:38 UTC
Casting is only supported for handful of types. Currently MySql tries to convert to other types, e.g double to decimal. The problem with this approach is that we get cast exception during materialization (expecting double, got decimal). This could potentially be improved by using value converters. Another approach would be to client eval, but that causes a lot of client eval (perf hit) and exposes a lot of bugs in query pipeline.

**Comment by AdamDotNet** [comment] 2018-07-16 22:55
Double being cast to decimal resulting in exceptions is hitting me hard trying to use `Average` within a `Group By`. ☹ #644

**Comment by LiangZugeng** [comment] 2019-03-30 09:38
After upgraded from EF Core 2.1.x to 2.2.3, the .Sum() previously worked no longer works.

Code Repo:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace efcore22bug
{

    public class Book
    {
        public Guid BookId { get; private set; }
        public float Weight { get; set; }
    }

    public class BloggingContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql(@"Server=localhost;database=EFCore22Test;uid=root;password=Password");
        }

        public DbSet<Book> Books { get; set; }
    }

    public class Program
    {
        public static async Task Main()
        {
            using (var context = new BloggingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var book = new Book
                {
                    Weight = 1.15f
                };

                context.Add(book);
                context.SaveChanges();

                var weight = await context.Books.SumAsync(b => b.Weight);
                Console.WriteLine(weight);
            }
        }
    }
}
```

.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.2.0" />
  </ItemGroup>

</Project>
```

Error text:
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Single'.
   at MySql.Data.MySqlClient.MySqlDataReader.GetFloat(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 224
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.GetResult[TResult](IAsyncEnumerable`1 valueBuffers, Boolean throwOnNullResult, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at efcore22bug.Program.Main() in /Users/james/Projects/temp/efcore22bug/Program.cs:line 45
   at efcore22bug.Program.<Main>()
```

If I changed the query like below it can work but the return value will be converted to an integer instead of a float number.
```
var weight = await context.Books.SumAsync(b => (decimal)b.Weight);
// this can work but weight will be 1 instead of 1.5
```

P.S. I tried the SQL Server EF Core DB Provider and it works fine, so it may be an issue in Polemo MySQL DB Provider, please help check if my issue relates to this one, and could you please suggest a workaround?

**Comment by mguinness** [comment] 2019-03-31 21:53
FWIW this exception also occurs on version 2.1.4 of this library.  Extract from MySQL [documentation](https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html#function_sum):

> The SUM() and AVG() functions return a DECIMAL value for exact-value arguments (integer or DECIMAL), and a DOUBLE value for approximate-value arguments (FLOAT or DOUBLE).

Based on that you could try `SumAsync(b => (double)b.Weight)` as a workaround until a fix is made.

**Comment by LiangZugeng** [comment] 2019-04-01 08:16
@mguinness Thanks for the suggestion, however it didn't work, after I tried `SumAsync(b => (double)b.Weight)` the same exception was thrown.

The reason is probably that the provider applied a conversion to the generated SQL automatically, see the generated SQL below.

```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (17ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT SUM(CAST(`b`.`Weight` AS decimal))
      FROM `Books` AS `b`
```

Do you know why there is a CAST for b.Weight to decimal? I tried to modify Weight to float or double in the EF model, the same conversion was applied, I'm confused here. BTW, before the upgrade (EF core 2.1.x and Polemo 2.1.x) everything works fine.

**Comment by mguinness** [comment] 2019-04-01 18:34
> Do you know why there is a CAST for b.Weight to decimal

https://github.com/aspnet/EntityFrameworkCore/commit/f41fcc98#diff-820ae736fa62b805aac1c89b20b273ba

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/commit/7cc8fbda#diff-414c1f2685912c7ae71531e07803f446

**Comment by caleblloyd** [comment] 2019-05-18 01:00
Closing as this was 2.1 release oriented

**Closed by caleblloyd** 2019-05-18 01:00 UTC
Labels: functional-tests

**Comment by stdatiks** [comment] 2020-04-19 23:04
I reproduce this bug on version 3.1.1!

I took the code above, replace package versions in csproj and run it. And got the same error.
It's critical issue for me.

**Comment by lauxjpn** [comment] 2020-04-20 00:45
@stdatiks I am unable to reproduce this issue with Pomelo 3.1.1. I used the following code and ran it against MySQL 8.0.18 and MySQL 5.7.28 (changing the `ServerVersion` to `5.7.28-mysql` accordingly) without problems:

```c#
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace IssueConsoleTemplate
{
    public class Book
    {
        public int BookId { get; set; }
        public float Weight { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Book> Books { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql(
                    "server=127.0.0.1;port=3306;user=root;password=;database=Issue571",
                    b => b.ServerVersion("8.0.18-mysql"))
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b
                            .AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Book>()
                .HasData(new Book { BookId = 1, Weight = 1.15f});
        }
    }

    internal class Program
    {
        private static void Main()
        {
            using (var context = new Context())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var weight = context.Books.Sum(b => b.Weight);
                
                Debug.Assert(weight == 1.15f);
            }
        }
    }
}
```

For MySQL 8.0.18, the following query was generated:

```sql
SELECT CAST(SUM(`b`.`Weight`) AS double)
FROM `Books` AS `b`
```

This is expected, because MySQL 8.0.17+ supports casting to `double` and `float`. Casting to `float` will however unnecessarily drop precision and round away the last decimal place due to some bug in MySQL, so we cast to `double` inside the query instead and then downcast the result later when retrieved by MySqlConnector to `System.Single`. The end result then is correct. So this behavior is expected.

For MySQL 5.7.28, the following query was generated:

```sql
SELECT (CAST(SUM(`b`.`Weight`) AS decimal(65,30)) + 0e0)
FROM `Books` AS `b`
```

This is also expected, because MySQL < 8.0.17 does not support casting to `double` or `float`. We therefore cast to `decimal` first, and then add `0e0`, which will result in a `double`, and then downcast the result later when retrieved by MySqlConnector to `System.Single`. The end result then is correct and this behavior is expected as well.

---

What is the MySqlConnector version and the database server version (MySQL/MariaDB) you are using?
Also, please post the generated SQL query that is logged by EF Core.

**Comment by stdatiks** [comment] 2020-04-20 01:17
@lauxjpn, OMG! I do not set the "ServerVersion" option.
Sorry to disturb you. I feel so stupid =(

**Comment by lauxjpn** [comment] 2020-04-20 01:47
@stdatiks No problem. `ServerVersion` will become a mandatory parameter of `UseMySql()` in our release targeting EF Core 5 later this year, because we started to use it heavily internally since 3.0.0 to generate tailored SQL statements.

Currently, if no `ServerVersion` is specified, the latest one is assumed (which might generate statements that are not understood by previous versions).
