### ISSUE TITLE
Primary key is not retrieved on SaveChanges()

### ISSUE THREAD

**Issue by CoderProject** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#436] opened 2017-11-08 11:07 UTC
### Steps to reproduce
- Create a mysql table with a primary key named Id (int, auto-increment, pk)
- use Scaffold-DbContext to auto generate entities
- create an instance of entity, add it to dbcontext and call `SaveChanges()`

### The issue
Id property remains `0` after SaveChanges(). Normally this property gets filled by framework as soon as the entity is inserted to db.

### Further technical details

MySQL version: 5.5
Operating system: debian
Pomelo.EntityFrameworkCore.MySql version: 2.0.0.1

**Comment by yukozh** [comment] 2017-11-08 12:23
Dupe of #398

**Closed by yukozh** 2017-11-08 12:23 UTC
