### ISSUE TITLE
Migrated from MySql.Data.EntityFrameworkCore 8.0.19 to Pomelo.EntityFrameworkCore.MySql 3.1.1 and my code is now immensely slower/nonfunctional

### ISSUE THREAD

**Issue by Xythium** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1021] opened 2020-02-05 12:19 UTC
I recently updated my project from .NET Core 2.2 to 3.1, and had to change database provider because it wasn't compatible. Some database operations that used to take less than a second (like, maybe ~100ms for a page load) now take over a minute (for example, 1.2 minute page load).

For example, such an increase in execution time happens in
(couple hundred ms to 1.2 minute)
```csharp
            var artists = context.Artists
                .Include(a => a.People)
                .ThenInclude(a => a.Person)
                .ThenInclude(p => p.Artists)
                .ThenInclude(a => a.Artist)
                .Include(a => a.Albums)
                .ThenInclude(a => a.Album)
                .Include(a => a.Tracks)
                .ThenInclude(t => t.Track)
                .ThenInclude(t => t.Listens)
                .Include(a => a.Tracks)
                .ThenInclude(t => t.Track)
                .ThenInclude(t => t.Albums)
                .ThenInclude(a => a.Album)
                .ThenInclude(a => a.Artists)
                .ThenInclude(a => a.Artist)
                .Single(a => a.ArtistId == id);
```

(couple hundred ms to 4.2 minutes)
```csharp
            var results = context.Users
                .Include(u => u.Listens)
                .ThenInclude(l => l.Track)
                .ThenInclude(t => t.Artists)
                .ThenInclude(a => a.Artist)
                .Include(u => u.Listens)
                .ThenInclude(l => l.Album)
                .ThenInclude(a => a.Artists)
                .ThenInclude(a => a.Artist)
                .Include(u => u.Collection)
                .ThenInclude(c => c.Album)
                .ThenInclude(a => a.Artists)
                .Single(u => string.Equals(u.Name, name, StringComparison.OrdinalIgnoreCase));
```

Model https://pastebin.com/NDNvzP7C

When these queries take a long time, it is usually writing _gigabytes_ of data to my boot drive, and earlier I ran into an issue where the queries couldnt even complete because MySql completely filled up my boot drive ![](https://i.imgur.com/iggtXef.png)

I assume rewriting all my queries to LINQ to SQL would fix this but I haven't been able to figure out how to do that properly with "complex" model structures, while also getting the objects and not just a bunch of IDs.

### Further technical details

MySQL version: 8.0.19
Operating system: Windows 10 Home (build 18363)
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: cant find it

**Comment by mguinness** [comment] 2020-02-05 17:46
See [Significant Query Slowdown When Using Multiple Joins Due To Changes In 3.0](https://github.com/dotnet/efcore/issues/18022).

**Comment by lauxjpn** [comment] 2020-02-05 19:46
This is a duplicate of #874, #887, #901 and possibly others.

**Closed by lauxjpn** 2020-02-05 19:46 UTC
