### ISSUE TITLE
Wrong collation in Migrations after updating to Pomelo 5.0.3

### ISSUE THREAD

**Issue by Ben555555** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1580] opened 2021-12-06 07:50 UTC
### Steps to reproduce
We have updated from Pomelo 5.0.0-alpha.2 to 5.0.3. We are facing some issues now when creating new migrations with foreign keys:

```C#
migrationBuilder.AddColumn<Guid>(
    name: "UserId",
    table: "MyTable",
    type: "char(36)",
    nullable: true,
    collation: "ascii_general_ci");
```

This is our entity configuration:

```C#
public class MyTableEntityConfiguration : 
{
    public override void Configure(EntityTypeBuilder<MyTableEntity> builder)
    {
        base.Configure(builder);

        builder.HasOne(x=> x.User)
            .WithMany()
            .HasForeignKey(x=> x.UserId)
            .HasPrincipalKey(user => user.Id);
    }
}
```

And our entity:

```C#
public class MyTable
{
    public Guid? UserId { get; set; }
    public UserEntity User { get; set; }
}
```

### The issue
A wrong collation ("ascii_general_ci") is now being added causing the migration to fail when it's executed:

`Failed executing DbCommand (5ms) [Parameters=[], CommandType='Text', CommandTimeout='30'] ALTER TABLE MyTable ADD CONSTRAINT FK_MyTable_Users_UserId FOREIGN KEY (UserId) REFERENCES Users (Id) ON DELETE RESTRICT;`

The only solution we have found so far is to remove the "collation: "ascii_general_ci" in the migration. Is there a better solution to not add the collation (or only the correct one) in the migrations automatically? Our database is setup to use the "Default charset".

### Further technical details

MySQL version:  
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: 5.0.3
Microsoft.AspNetCore.App version: 5.0.12

Other details about my project setup:
.NET 5

**Comment by mguinness** [comment] 2021-12-06 08:57
Duplicate of https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1477.

**Closed** 2021-12-06 14:36 UTC
Labels: type-question
