### ISSUE TITLE
Non-deterministic connection interruptions after upgrading from 6.0 to 8.0

### ISSUE THREAD

**Issue by lauxjpn** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1855] opened 2024-02-28 15:35 UTC
Hi, I also have problems with the connection after upgrading from 6.0 to 8.0. From time to time such errors appear in the logs, although this is a local server and it is 100% accessible and productive:
```
03:26:43.4532 [ThreadID: 00006] ERROR Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`2.Log An error occurred using the connection to database 'db1.prices' on server 'localhost'.
03:26:43.4532 [ThreadID: 00027] ERROR Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`3.Log An exception occurred while iterating over the results of a query for context type 'db1.prices.Models.PricesDB.PricesDbContext'.
System.InvalidOperationException: An exception has been raised that is likely due to a transient failure. Consider enabling transient error resiliency by adding 'EnableRetryOnFailure()' to the 'UseMySql' call.
 ---> MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.
   at MySqlConnector.Core.ServerSession.OpenTcpSocketAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 1063
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, MySqlConnection connection, Int64 startingTimestamp, ILoadBalancer loadBalancer, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 425
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, Action`4 logMessage, Int64 startingTimestamp, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 428
   at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync(MySqlConnection connection, Action`4 logMessage, Int64 startingTimestamp, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 433
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int64 startingTimestamp, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 111
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int64 startingTimestamp, Int32 timeoutMilliseconds, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 144
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 919
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 419
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlRelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```

_Originally posted by @alexeygritsenko in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1838#issuecomment-1962293260_

**Comment by lauxjpn** [comment] 2024-02-28 15:48
@alexeygritsenko Please fill-out the following `Further technical details` section:

### Further technical details

MySQL version: 
Operating system: 
Pomelo.EntityFrameworkCore.MySql version:
Microsoft.AspNetCore.App version:

Other details about my project setup:

---

This is likely an environment issue and not an isssue with Pomelo or MySqlConnector. That being, let's troubleshoot:

- Does "local" mean "on the same machine" or on the same local network?
- If on the same machine, is it installed directly on the OS or are you using some kind of container service (e.g. docker)?
- If on the same machine, installed directly on the OS and the OS being Windows, do you experience the same issue when connecting via a [named pipe](https://mysqlconnector.net/connection-options/) (instead of a TCP socket)?
- If on the same machine, installed directly on the OS and the OS being Linux/Unix, do you experience the same issue when connecting via a [Unix socket](https://mysqlconnector.net/connection-options/) (instead of a TCP socket)?
- If you run your 6.0 project again, does it still work without issues?
- If your 6.0 project still runs without issues, do you experience the same connection issues when running your 6.0 project but with an explicit package reference to MySqlConnector `2.3.5`?

**Comment by setoy** [comment] 2024-03-03 19:05
MySQL version: 10.11.5-MariaDB-log
Operating system: Windows Server 2022 (Build 20348.2322)
Pomelo.EntityFrameworkCore.MySql version: 8.0.0 / 8.0.1
Microsoft.AspNetCore.App version: 8.0.2

Other details about my project setup:
"Simple" ASP.NET 8.0.2 application using MVC

This is likely an environment issue and not an isssue with Pomelo or MySqlConnector. That being said, let's troubleshoot:

**Does "local" mean "on the same machine" or on the same local network?**
local

**If on the same machine, is it installed directly on the OS or are you using some kind of container service (e.g. docker)?**
Directly installed

**If on the same machine, installed directly on the OS and the OS being Windows, do you experience the same issue when connecting via a [named pipe](https://mysqlconnector.net/connection-options/) (instead of a TCP socket)?**
Not yet tried.

**If on the same machine, installed directly on the OS and the OS being Linux/Unix, do you experience the same issue when connecting via a [Unix socket](https://mysqlconnector.net/connection-options/) (instead of a TCP socket)?**
Not applicable.

**If you run your 6.0 project again, does it still work without issues?
If your 6.0 project still runs without issues, do you experience the same connection issues when running your 6.0 project but with an explicit package reference to MySqlConnector 2.3.5?**
I'm gonna answer both of them, since it had nothing to do with 6.0 for me. 8.0.0 is working, 8.0.1 is not. I'm getting a plethora of `MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.` exceptions with 8.0.1, and as soon as I reverted, everything worked again.

**How does your connection string look like (sanitize sensitive information)? Any connection string changes between 6.0 and 8.0?**
Simple:
```cs
private static string GetConnectionString(string host, int port, string databaseName, string username, string password, int defaultCommandTimeout, int connectionTimeout)
{
    string result = $"server={host};" +
                    $"port={port};" +
                    $"database={databaseName};" +
                    $"uid={username};" +
                    $"password={password};" +
                    "Allow User Variables=True;" +
                    "Convert Zero Datetime=True;" +
                    $"Default Command Timeout={defaultCommandTimeout};" +
                    $"Connection Timeout={connectionTimeout};";

    return result;
}
```

Hope this helps and thanks for this project!

**Comment by alexeygritsenko** [comment] 2024-03-03 19:16
As for me, I can't reproduce the bug in test environments. Only in production. This makes investigation difficult. I also can’t roll back the project to 6.0 since it was supposed to be a one-way move in a working environment.

**Comment by lauxjpn** [comment] 2024-03-03 19:27
@setoy

> I'm gonna answer both of them, since it had nothing to do with 6.0 for me. 8.0.0 is working, 8.0.1 is not.

There is no difference at all in regards to connections between `8.0.0` and `8.0.1` and both versions also use the same version of MySqlConnector. So it is going to be an environment issue and not an isssue with Pomelo or MySqlConnector.

---

Restart the database server, then retry `8.0.1` without using any `8.0.0` connections or other apps accessing the database server since its restart.

Independently of that, try the named pipe connection method to rule-out any network stack issues.

If both bring not difference to the matter, then we will move forward to checking `max_connections` and related settings.

I am assuming, that you are not using `PrimitiveCollectionsSupport` (or `ToJson`), correct?

**Comment by lauxjpn** [comment] 2024-03-03 19:30
@alexeygritsenko

The following should be possible to answer about or do in your production environment, without much difficulties or negative impact:

- Please fill-out the following Further technical details section
- Does "local" mean "on the same machine" or on the same local network?
- If on the same machine, is it installed directly on the OS or are you using some kind of container service (e.g. docker)?
- If on the same machine, installed directly on the OS and the OS being Windows, do you experience the same issue when connecting via a [named pipe](https://mysqlconnector.net/connection-options/) (instead of a TCP socket)?
- If on the same machine, installed directly on the OS and the OS being Linux/Unix, do you experience the same issue when connecting via a [Unix socket](https://mysqlconnector.net/connection-options/) (instead of a TCP socket)?
- How does your connection string look like (sanitize sensitive information)? Any connection string changes between 6.0 and 8.0?

Just skip the 6.0 related bullet points.

**Comment by lauxjpn** [comment] 2024-03-09 11:20
> @alexeygritsenko
> 
> The following should be possible to answer about or do in your production environment, without much difficulties or negative impact:
> 
> * Please fill-out the `Further technical details` section
> * Does "local" mean "on the same machine" or on the same local network?
> * If on the same machine, is it installed directly on the OS or are you using some kind of container service (e.g. docker)?
> * If on the same machine, installed directly on the OS and the OS being Windows, do you experience the same issue when connecting via a [named pipe](https://mysqlconnector.net/connection-options/) (instead of a TCP socket)?
> * If on the same machine, installed directly on the OS and the OS being Linux/Unix, do you experience the same issue when connecting via a [Unix socket](https://mysqlconnector.net/connection-options/) (instead of a TCP socket)?
> * How does your connection string look like (sanitize sensitive information)? Any connection string changes between 6.0 and 8.0?
> 
> (So just skip the 6.0 related bullet points.)
> 
> In addition check:
> 
> * If on the same machine, does the issue still occur if you add `Pooling=false` to the connection string?

@alexeygritsenko Any update on this?

**Comment by alexeygritsenko** [comment] 2024-03-09 11:44
@lauxjpn hi, I made two test programs on .NET 6 and .NET 8 in a week, and they didn’t produce a error. The bug still occurs in real service, but rarely and spontaneously. It doesn't do much harm because... my worker will just do repetitions. Therefore, I think we can close this topic.

However, I will note one new assumption, with of switching to .NET 8, I switched to a 13600KF CPU and the reason may be energy efficient cores. I've heard from reviewers that these cores can slow down in all sorts of applications and cause unexpected drops in computing performance.

**Comment by lauxjpn** [comment] 2024-03-09 13:02
> Therefore, I think we can close this topic.

@alexeygritsenko Please answer at least the following points for future reference, in case somebody else experiences a similar issue:

> * Please fill-out the `Further technical details` section
> * Does "local" mean "on the same machine" or on the same local network?
> * If on the same machine, is it installed directly on the OS or are you using some kind of container service (e.g. docker)?
> * How does your connection string look like (sanitize sensitive information)? Any connection string changes between 6.0 and 8.0?

After that, we can close the issue for now. Thanks!

---

> It doesn't do much harm because... my worker will just do repetitions.

There is also [connection resiliency](https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency) build into EF Core, that you can configure to let your app retry commands automatically, if the connection suddenly fails.

**Comment by alexeygritsenko** [comment] 2024-03-09 13:56
Ok,

> Does "local" mean "on the same machine" or on the same local network?

on the same machine. but I also caught this error for a remote database

> If on the same machine, is it installed directly on the OS or are you using some kind of container service (e.g. docker)?

it installed directly in same machine (Windows 10), and installed directly in remote case (Ubuntu 20.04)

> How does your connection string look like (sanitize sensitive information)? Any connection string changes between 6.0 and 8.0?

for local case 
`"PricesConnection": "server=localhost;UserId=root;Password=root;database=db1.prices"`
for remote case
`"PricesConnection": "server=176.53.cut.cut;UserId=myuser;database=db1.prices;password=cut"`
I didn't change the connection string between 6.0 and 8.0

> There is also [connection resiliency](https://learn.microsoft.com/en-us/ef/core/miscellaneous/connection-resiliency) build into EF Core, that you can configure to let your app retry commands automatically, if the connection suddenly fails.

Yes, I know. But for now I wrote the repetitions myself.

**Comment by lauxjpn** [comment] 2024-03-09 16:33
@alexeygritsenko Thanks, now please fill-out the following two lines from the `Further technical details` section, that we have not gotten from you yet:

> MySQL version:
> Pomelo.EntityFrameworkCore.MySql version:

**Comment by alexeygritsenko** [comment] 2024-03-09 18:39
> MySQL version:

8.0.30 local, 8.0.36 remote

> Pomelo.EntityFrameworkCore.MySql version:

6.0.2 before update, 8.0.0 after update

**Closed** 2024-03-10 09:17 UTC
Labels: type-investigation, needs-more-info
