### ISSUE TITLE
Unparameterized .Contains query using incorrect values after periods of high traffic

### ISSUE THREAD

**Issue by plittlewood-rpt** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1581] opened 2021-12-06 09:17 UTC
### Steps to reproduce
Unable to reproduce at this time

### The issue
I have an API that switches DbContext from request to request based on the customer accessing it (this is because we use single tenant databases). We are seeing on occasion, after periods of high traffic, that the expressions compiled after using the `Contains()` operator use old values, as though a cache is being exhausted.

To give you some context:

Users might call `GET /myEndpoint?ownerId=ABC&ownerId=DEF`

The query parameters get translated into SQL via LINQ using something similar to:

```C#
if (query.OwnerIds!= null && query.OwnerIds.Any())
{
    predicate = predicate.And(p => query.OwnerIds.Contains(p.OwnerId) || query.OwnerIds.Contains(p.OwnerId2) || query.OwnerIds.Contains(p.OwnerId3));
}
``` 

The predicate then gets used when calling the database context ie: `dbContext.Data.Where(predicate)`

This correctly gets converted to a MySQL statement using `IN ()` as I'd expect. If we take the URL example above (`GET /myEndpoint?ownerId=ABC&ownerId=DEF`) however, the query that gets executed against the database actually uses values from a previous query, so it might run `WHERE ownerId IN ('GHI', 'JKL') OR ownerId2 IN ('GHI', 'JKL') OR ownerId3 IN ('GHI', 'JKL')`.

This only seems to occur after a period of high traffic has hit the API. Restarting the container that the API runs in resolves the issue, until it eventually happens again. The services run on docker containers on AWS ECS Fargate

I can rewrite the LINQ to chain OR conditions together, which then results in a parameterized query but rather horrible SQL. Can anybody suggest anything that might be causing the underlying problem? I'm not bothered if the `IN ()` is not parameterized IF I can explain and resolve what's going on with old values being used.

### Further technical details

MySQL version: 5.7.12
Operating system: Windows 10
Pomelo.EntityFrameworkCore.MySql version: ~~5.0.0~~ **5.0.0-alpha.2**
Microsoft.AspNetCore.App version: 3.1
EntityFrameworkCore version: 5.0.1

**Comment by plittlewood-rpt** [comment] 2021-12-06 11:11
@lauxjpn thanks - I do have the issue logged on the efcore project as well and they suggested it may be a provider issue. I'll update the packages and get it out to production to see if the issue crops back up

**Comment by lauxjpn** [comment] 2021-12-06 12:28
@plittlewood-rpt Please post the link to the upstream issue, so they get cross referenced. Thanks!

**Comment by plittlewood-rpt** [comment] 2021-12-06 12:39
Item also logged on main efcore project at https://github.com/dotnet/efcore/issues/26905

**Comment by mguinness** [comment] 2021-12-06 17:48
> I do have the issue logged on the efcore project as well and they suggested it may be a provider issue.

Based on the issue mentioned, I don't see it being suggested as a provider issue.  Can you post a link to that comment?

**Comment by plittlewood-rpt** [comment] 2021-12-06 18:21
Please see the linked ticket noted in my first sentence on the link I posted (they asked me to log a new item). The comment is in the original ticket
________________________________

**Comment by mguinness** [comment] 2021-12-06 19:06
OK, [comment](https://github.com/dotnet/efcore/issues/13617#issuecomment-985794961) was marked as off-topic which was why I missed it.

**Comment by lauxjpn** [comment] 2022-01-25 08:16
> @plittlewood-rpt This is probably an EF Core issue, and we should get to the bottom of this.
> 
> First, please update to use the latest 5.0 version of EF Core (currently `5.0.12`), since it is possible, that this has been fixed since `5.0.1`. And also update Pomelo to `5.0.3`.
> 
> Then check again, whether the issue still pops up and report back to us.

@plittlewood-rpt Please provide us with the requested information. Otherwise, we will close this issue for now. Thanks!

**Comment by plittlewood-rpt** [comment] 2022-01-25 08:39
Hi @lauxjpn - thanks for coming back to me. I've done that and still see unparameterized queries when using the .Contains operator. We still haven't been able to replicate this on demand which is frustrating, even after throwing 20k requests at one of our services so it feels like we are missing something at the moment.

**Comment by mguinness** [comment] 2022-01-25 16:54
In the upstream closed issue https://github.com/dotnet/efcore/issues/26905 you mentioned the following, was this changed in your project?

> We have a repository class which is registered as scoped. The db context factory class which is injected into the repository is registered as transient.

**Comment by lauxjpn** [comment] 2022-01-26 04:52
> In the upstream closed issue [dotnet/efcore#26905](https://github.com/dotnet/efcore/issues/26905) you mentioned the following, was this changed in your project?
> 
> > We have a repository class which is registered as scoped. The db context factory class which is injected into the repository is registered as transient.

@mguinness That is indeed an interesting detail, since it appears that an older state is being reused somewhere.

---

> The query parameters get translated into SQL via LINQ using something similar to:
> 
> ```cs
> if (query.OwnerIds!= null && query.OwnerIds.Any())
> {
>     predicate = predicate.And(p => query.OwnerIds.Contains(p.OwnerId) || query.OwnerIds.Contains(p.OwnerId2) || query.OwnerIds.Contains(p.OwnerId3));
> }
> ```
> 
> The predicate then gets used when calling the database context ie: `dbContext.Data.Where(predicate)`

@plittlewood-rpt Is the `predicate` being fully reconstructed each time and only used locally in that particular method, or is the predicate or the resulting (non-executed) query object being kept around (e.g. in a class member)?

---

@plittlewood-rpt The first step to narrow down the issue systematically would be to determine in your code, that an incorrect expression or SQL statement has been generated. This could be done with an expression visitor (on the expression level), or with an command interceptor (on the SQL level).

Once your app knows that this issue is occurring at this very moment, you want to output some debug info (especially the predicate expression and the full query expression tree) and maybe even create a dump file, that you can analyze later.

**Comment by Ahmedrz89** [comment] 2022-02-04 13:04
I can confirm that this issue is a provider issue and not efcore itself 
and it seems to happen only in version : 5.0.0-alpha.2
and I was able to reproduce this in a simple console application not sure if it helps 

[efcore_mysql_bug.zip](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/files/8003192/efcore_mysql_bug.zip)

**Comment by plittlewood-rpt** [comment] 2022-02-04 13:07
@Ahmedrz89 thanks for this - Interestingly we _were_ using 5.0.0-alpha.2 but we upgraded as part of troubleshooting this problem. We had however implemented a twice daily service restart at the same time the package update went out which may have well masked the fact the update resolved the problem. I'll check out your code but perhaps I can turn off the twice daily restart to confirm that the later package version also fixes it for us

**Comment by Ahmedrz89** [comment] 2022-02-04 13:12
yes I think updating is enough here, but give it a shot and let us know

**Comment by plittlewood-rpt** [comment] 2022-02-04 16:14
Hi @Ahmedrz89 thanks so much for the sample code, I've been able to replicate it on our actual APIs using your sample as a guide. I'd be really curious to know what changed to alter this behaviour if anyone from the Pomelo team can provide any pointers (just my curious side talking here)

**Comment by lauxjpn** [comment] 2022-02-08 11:51
@plittlewood-rpt Did updating to the latest stable version of Pomelo 5.0 solve the issue for you?

**Comment by plittlewood-rpt** [comment] 2022-02-08 11:55
Hi @lauxjpn - it seems like it will. We haven't been able to get it out to production just yet, but I was able to replicate the issue and confirm it didn't happen any more locally. I'd definitely be interested to understand what it was that got changed between those releases if possible

**Comment by lauxjpn** [comment] 2022-02-08 13:46
> I'd definitely be interested to understand what it was that got changed between those releases if possible

@plittlewood-rpt I have not looked into it, but since it was an `-alpha` release that you were using, a couple of smaller issues are not fully unexpected. If you want to dig deeper, the translation happens in [MySqlStringComparisonMethodTranslator.cs](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/src/EFCore.MySql/Query/ExpressionTranslators/Internal/MySqlStringComparisonMethodTranslator.cs).

> it seems like it will.

We will close the issue then. Feel free to reopen it, if it turns out that the behavior still appears.

**Closed by lauxjpn** 2022-02-08 13:46 UTC
Labels: closed-question, type-question
