### ISSUE TITLE
Is Migrate() supported?

### ISSUE THREAD

**Issue by GuerrillaCoder** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#240] opened 2017-03-30 21:26 UTC
I am using AspNetCore 1.1.1 and Pomelo.EntityFrameworkCore.MySql 1.1.0.

Locally I am developing on windows with visual studio and a local copy of MariaDB and everything works fine.  I can run update-database and the database is created.

My production server is Ubuntu 16.04.  When I publish my website and upload the published files the necessary tables are not created in the production database.

As suggested on Microsoft blog I have added this code to my Startup.Configure() to create database from migrations.

```c#
using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
{
	var context = serviceScope.ServiceProvider.GetService<MobileTestContext>();
	context.Database.Migrate();
}
```

This doesn't work.  When I try to start my website service I get this exception:

```
Unhandled Exception: MySql.Data.MySqlClient.MySqlException: Table 'moboz.__EFMigrationsHistory' doesn't exist
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySql.Data.MySqlClient.Results.ResultSet.<ReadResultSetHeaderAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<ReadFirstResultSetAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlDataReader.<CreateAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.CommandExecutors.TextCommandExecutor.<ExecuteReaderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.<ExecuteReaderAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.MySqlRelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at ScreenshotWebsite.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in E:\Projects\PlacesAPI\ScreenshotWebsite\Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ScreenshotWebsite.Program.Main(String[] args) in E:\Projects\PlacesAPI\ScreenshotWebsite\Program.cs:line 14

   ```
   
 Is Migrate() supported by Pomelo?  If not, what are my alternatives?  If so, why isn't it working?

**Comment by caleblloyd** [comment] 2017-03-30 21:53
Duplicate of #68 , see https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/68#issuecomment-285953872

It's fixed upstream and works in `1-1-1-*`

**Closed by caleblloyd** 2017-03-30 21:53 UTC

**Comment by GuerrillaCoder** [comment] 2017-03-30 22:01
OK, thanks.

For anyone finding this it works if you make table manually:
```
CREATE TABLE `__EFMigrationsHistory` (
  `MigrationId` varchar(150) NOT NULL,
  `ProductVersion` varchar(32) NOT NULL
)
```

**Comment by mguinness** [comment] 2017-03-30 22:03
See https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/99#issuecomment-266344129
