### ISSUE TITLE
 When to upgrade to .net5.0

### ISSUE THREAD

**Issue by ajw333** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1098] opened 2020-06-11 01:48 UTC
When to upgrade to .net5.0

**Comment by mguinness** [comment] 2020-06-11 02:31
Duplicate of [EF Core 5 Preview support](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1088).

**Closed by mguinness** 2020-06-11 02:31 UTC
