### ISSUE TITLE
Cannot map Guid to relational type

### ISSUE THREAD

**Issue by Moxh3** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#1291] opened 2021-01-14 06:34 UTC
### Steps to reproduce
Class has an ID of the type Guid
`[Key]
 [DatabaseGenerated(DatabaseGeneratedOption.None)]
 public Guid ID { get; set; }`

Add an EF migration with `Add-Migration`.

### The issue
```
Exception message: No mapping to a relational type can be found for property 'ArmsAndAmmo.Models.Listing.ID' with the CLR type 'string'.
Strack trace:  at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMappingSourceExtensions.GetMapping(IRelationalTypeMappingSource typeMappingSource, IProperty property)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IProperty source, IProperty target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(TableMapping source, TableMapping target, DiffContext diffContext)+MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.DiffCollection[T](IEnumerable`1 sources, IEnumerable`1 targets, DiffContext diffContext, Func`4 diff, Func`3 add, Func`3 remove, Func`4[] predicates)+MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Sort(IEnumerable`1 operations, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

MySQL version: n/a
Operating system: Windows x86
Pomelo.EntityFrameworkCore.MySql version: 3.2.4
Microsoft.AspNetCore.App version: 3.1
Microsoft.EntityFrameworkCore version: 3.1.8

**Comment by lauxjpn** [comment] 2021-01-14 14:51
I cannot reproduce the exception with the following code:

<details>
<summary>Program.cs</summary>

```c#
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;

namespace IssueConsoleTemplate
{
    public class IceCream
    {
        public Guid IceCreamId { get; set; }
        public string Name { get; set; } 
    }
    
    public class Context : DbContext
    {
        public DbSet<IceCream> IceCreams { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql(
                    "server=127.0.0.1;port=3306;user=root;password=;database=Issue1291",
                    b => b.ServerVersion("8.0.21-mysql")
                          .CharSetBehavior(CharSetBehavior.NeverAppend))
                .UseLoggerFactory(
                    LoggerFactory.Create(
                        b => b.AddConsole()
                            .AddFilter(level => level >= LogLevel.Information)))
                .EnableSensitiveDataLogging()
                .EnableDetailedErrors();
        }
    }

    internal static class Program
    {
        private static void Main()
        {
            using var context = new Context();
        }
    }
}
```

</details>

I successfully create a migration, using the following code:

<details>
<summary>PowerShell output</summary>

```
PS E:\Sources\PomeloIssues\Issue1291\IssueConsoleTemplate> dotnet ef migrations add Initial
Build started...
Build succeeded.
warn: Microsoft.EntityFrameworkCore.Model.Validation[10400]
      Sensitive data logging is enabled. Log entries and exception messages may include sensitive application data, this mode should only be enabled during development.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.10 initialized 'Context' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: ServerVersion 8.0.21 MySql SensitiveDataLoggingEnabled DetailedErrorsEnabled
Done. To undo this action, use 'ef migrations remove'
```

</details>

It generates the following snapshot:

<details>
<summary>Migrations/ContextModelSnapshot.cs</summary>

```c#
// <auto-generated />
using System;
using IssueConsoleTemplate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IssueConsoleTemplate.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IssueConsoleTemplate.IceCream", b =>
                {
                    b.Property<Guid>("IceCreamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("IceCreamId");

                    b.ToTable("IceCreams");
                });
#pragma warning restore 612, 618
        }
    }
}
```

</details>

---

Therefore, we will need more information from your project:

Please post the full `ArmsAndAmmo.Models.Listing` model class, the Fluent API calls if you use any in addition to the data annotations and your `UseMySql()`.
We will also need a full `Add-Migration` or `dotnet ef migrations add` call with the `-Verbose` option (package manager) or `--verbose` option (.NET Core CLI).

---

As a side note, if you explicitly want to specify the `Guid` creation method, it should be `.ValueGeneratedOnAdd()` (Fluent API) or its data annotation equivalent `[DatabaseGenerated(DatabaseGeneratedOption.Identity)]`. This is however not related to the issue you have posted here.

**Comment by sweideh** [comment] 2021-03-24 08:03
Hey, i have the same problem. My migrations are already existing. I guess when i delete all of my migrations and add them again, the error wont appear. Why are your Guids added as "Guid" and my model snapshot shows "string"?

**Comment by lauxjpn** [comment] 2021-04-02 04:19
@sweideh As said in my previous answer, we need more information to investigate this further. Can you share some code, migrations, etc. with us?

I might also be helpful to see the migrations with the issue and then the newly generated ones that don't have the issue, so we can compare the two.

**Comment by sweideh** [comment] 2021-04-06 06:42
> @sweideh As said in my previous answer, we need more information to investigate this further. Can you share some code, migrations, etc. with us?
> 
> I might also be helpful to see the migrations with the issue and then the newly generated ones that don't have the issue, so we can compare the two.

Hey @lauxjpn as you stated in some comments above its not reproduceable. With a newer pomelo version the model snapshot and the migrations showed the correct form of "Guid" instead of "string". Since then i hadn't the problem anymore, but  sadly I had to delete all my earlier migrations to get this problem fixed. I hope this wont be anything I need to do in the future again because deleting all migrations isnt a properly option when the service gets released.

**Comment by lauxjpn** [comment] 2021-04-06 09:52
@Moxh3 Thanks, we will close this one for now then. Feel free to provide us with the old (non-working) and new (working) migrations, so we can take a look at it.

**Closed by lauxjpn** 2021-04-06 09:52 UTC
Labels: closed-could-not-reproduce, could-not-reproduce, needs-more-info
