### ISSUE TITLE
Constructed SQL query is missing most WHERE conditions and LIMIT clause...

### ISSUE THREAD

**Issue by voodoodrul** [PomeloFoundation/Pomelo.EntityFrameworkCore.MySql#696] opened 2018-10-23 21:58 UTC
### The issue
When I write a simple LINQ expression, I expect the SQL that gets compiled to be somewhat sane and include WHERE conditions that can easily be translated into equivalent SQL statements. 

I have the following LINQ expression:
```
var deferralRecords =
                _context.Deferrals
                    .Where(x =>
                        x.DateOfBirth > DateTime.UtcNow.AddYears(-120) &&
                        x.DateOfBirth < DateTime.UtcNow &&
                        !x.FirstName.IsNullOrWhiteSpace() &&
                        !x.LastName.IsNullOrWhiteSpace() &&
                        x.SSN.Length == 4 &&
                        x.DonationCenterId.HasValue &&
                        x.CompanyId.HasValue &&
                        x.IsInvalidated == false &&
                        (!x.HasError.HasValue || x.HasError == false) &&
                        x.EndpointId == null)
                    .OrderBy(x => x.DateCreated)
                    .Take(_maxRecords)
```

I would expect that the rendered SQL to look roughly like this, or some equivalent set of WHERE expressions and LIMIT clause:
```
SELECT * FROM Deferrals
  WHERE DateOfBirth BETWEEN ? AND ?
  AND LENGTH(trim(FirstName)) > 0
  AND LENGTH(trim(LastName)) > 0
  AND LENGTH(SSN) = 4
  AND DonationCenterId IS NOT NULL
  AND CompanyId IS NOT NULL
  AND COALESCE(IsInvalidated,0) = 0
  AND COALESCE(HasError,0) = 0
  AND EndpointId IS NULL
  ORDER BY DateCreated
  LIMIT ?
```

Instead, only one condition actually makes it into the query that gets sent to the DB:

```
SELECT `x`.`Id`,
       `x`.`EndpointId`,
       `x`.`CompanyId`,
       `x`.`DateCreated`,
       `x`.`DateOfBirth`,
       `x`.`DeferralDate`,
       `x`.`DeferralId`,
       `x`.`DeferralReasonCode`,
       `x`.`DeferralReasonId`,
       `x`.`DonationCenterId`,
       `x`.`DonorAutoid`,
       `x`.`EffectiveDate`,
       `x`.`EnteredBy`,
       `x`.`FirstName`,
       `x`.`HasError`,
       `x`.`IndefinitelyDeferred`,
       `x`.`InvalidationReasonCode`,
       `x`.`IsInvalidated`,
       `x`.`LastName`,
       `x`.`LastUpdated`,
       `x`.`SSN`,
       `x`.`VisitDate`,
FROM `Deferrals` AS `x`
WHERE `x`.`EndpointId` IS NULL
ORDER BY `x`.`DateCreated`
```

Notice that there is no LIMIT clause and only one trivially simple WHERE condition gets included. This means that we're likely to load the entire table every single time we execute the LINQ expression. This is not scalable. 

### Further technical details

MySQL version: MariaDB 5.5
Operating system: Windows 10, macOS High Sierra, CentOS
Pomelo.EntityFrameworkCore.MySql version: 2.1.2

Other details about my project setup: .NET Core 2.1

**Comment by mguinness** [comment] 2018-10-23 23:36
Check your logs, I suspect you'll see something like below.

> The LINQ expression 'X' could not be translated and will be evaluated locally.

**Comment by voodoodrul** [comment] 2018-10-24 00:05
@mguinness The entire expression is rejected, even the Take() expression is not properly evaluated:

```
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where ((((((((([x].DateOfBirth > Convert(DateTime.UtcNow.AddYears(-120), Nullable`1)) AndAlso ([x].DateOfBirth < Convert(DateTime.UtcNow, Nullable`1))) AndAlso Not([x].FirstName.IsNullOrWhiteSpace())) AndAlso Not([x].LastNa
me.IsNullOrWhiteSpace())) AndAlso ([x].SSN.Length == 4)) AndAlso ([x].DonationCenterId != null)) AndAlso ([x].CompanyId != null)) AndAlso ([x].IsInvalidated == False)) AndAlso (Not(([x].HasError != null)) OrElse ([x].HasError == False)))' could not be translated and will be evaluated locally.

warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'Take(__p_0)' could not be translated and will be evaluated locally.
```

**Comment by voodoodrul** [comment] 2018-10-24 00:39
The problem is caused by IsNullOrWhiteSpace(), which cannot be translated to SQL. Moving each condition to its own .Where() allows the final query to be more resilient and include all of the conditions that are possible to convert. However, a side effect of doing this:

```
  .Where(x => x.DateOfBirth > DateTime.UtcNow.AddYears(-120))
                .Where(x => x.DateOfBirth < DateTime.UtcNow)
                .Where(x => !x.FirstName.IsNullOrWhiteSpace())
                .Where(x => !x.LastName.IsNullOrWhiteSpace())
                .Where(x => x.SSN.Length == 4)
                .Where(x => x.DonationCenterId.HasValue)
                .Where(x => x.CompanyId.HasValue)
                .Where(x => x.IsInvalidated == false)
                .Where(x => (!x.HasError.HasValue || x.HasError == false))
                .Where(x => x.EndpointId == null)
                .OrderBy(x => x.DateCreated)
                .Take(_maxRecords)
```

Is that the logger still produces warnings:

```
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where Not([x].FirstName.IsNullOrWhiteSpace())' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where Not([x].LastName.IsNullOrWhiteSpace())' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where ([x].SSN.Length == 4)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where ([x].DonationCenterId != null)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where ([x].CompanyId != null)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where ([x].IsInvalidated == False)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where (Not(([x].HasError != null)) OrElse ([x].HasError == False))' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'where (Property([x], "EndpointId") == null)' could not be translated and will be evaluated locally.
warn: Microsoft.EntityFrameworkCore.Query[20500]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      The LINQ expression 'Take(__p_0)' could not be translated and will be evaluated locally.

```

Even though the SQL it produces does in fact contain all the conditions it *could* translate with the exception that the LIMIT clause is still missing.. 

```
SELECT `x`.`Id`,
       `x`.`CodiLiteEndpointId`,
       `x`.`CompanyId`,
       `x`.`DateCreated`,
       `x`.`DateOfBirth`,
       `x`.`DeferralDate`,
       `x`.`DeferralId`,
       `x`.`DeferralReasonCode`,
       `x`.`DeferralReasonId`,
       `x`.`DonationCenterId`,
       `x`.`DonorAutoid`,
       `x`.`EffectiveDate`,
       `x`.`EnteredBy`,
       `x`.`FirstName`,
       `x`.`HasError`,
       `x`.`IndefinitelyDeferred`,
       `x`.`InvalidationReasonCode`,
       `x`.`IsInvalidated`,
       `x`.`LastName`,
       `x`.`LastUpdated`,
       `x`.`SSN`,
       `x`.`VisitDate`
FROM `Deferrals` AS `x`
WHERE (((((((`x`.`DateOfBirth` > DATE_ADD(UTC_TIMESTAMP(), INTERVAL -120 year)) AND
            (`x`.`DateOfBirth` < UTC_TIMESTAMP())) AND (CHAR_LENGTH(`x`.`SSN`) = 4)) AND
          `x`.`DonationCenterId` IS NOT NULL) AND `x`.`CompanyId` IS NOT NULL) AND (`x`.`IsInvalidated` = FALSE)) AND
       (`x`.`HasError` IS NULL OR (`x`.`HasError` = FALSE)))
  AND `x`.`EndpointId` IS NULL
ORDER BY `x`.`DateCreated`     
```

Removing the IsNullOrWhiteSpace() calls entirely allows everything to work as expected.

**Comment by mguinness** [comment] 2018-10-24 01:14
The `IsNullOrWhiteSpace()` must be an extension method you have as there is already a translator for `string.IsNullOrWhiteSpace(x)` which you should use.  Whenever something cannot be translated it will mean `Take()` will be evaluated locally otherwise you won't get the results that you expect.  Closing issue as it's a not a bug but usage related.

**Closed by mguinness** 2018-10-24 01:14 UTC

**Comment by voodoodrul** [comment] 2018-10-24 02:00
@mguinness I'm not using an extension method. It's the default provided in .NET for strings. If there's a translator for it, it's not working for my tests.

**Comment by voodoodrul** [comment] 2018-10-24 02:29
@mguinness Thank you for chasing this with me. Apparently this got injected from Quartz.Util and was completely unexpected. Sorry for the confusion.
